// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"core/helpers"
	"core/mcp"
	"core/repositories"
	"core/routes"
	"core/services/db"
	"core/services/socket"
	services "core/services/user"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	gormDB, err := db.NewDatabase()
	if err != nil {
		return nil, err
	}
	node, err := helpers.NewDefaultNode()
	if err != nil {
		return nil, err
	}
	reader, err := routes.GeoIPDBProvider()
	if err != nil {
		return nil, err
	}
	notificationRepository := repositories.NewNotificationRepository(gormDB, node)
	engagementRepository := repositories.NewEngagementRepository(gormDB)
	userRepository := repositories.NewUserRepository(gormDB, reader, node, engagementRepository, notificationRepository)
	mediaRepository := repositories.NewMediaRepository(gormDB, node)
	postRepository := repositories.NewPostRepository(gormDB, node, mediaRepository, userRepository, notificationRepository)
	userService := services.NewUserService(userRepository, postRepository, mediaRepository, engagementRepository, notificationRepository)
	postService := services.NewPostService(userRepository, postRepository, mediaRepository)
	placeRepository := repositories.NewPlaceRepository(gormDB, node, mediaRepository, userRepository, notificationRepository, postRepository)
	placeService := services.NewPlaceService(userRepository, postRepository, mediaRepository, placeRepository)
	newsRepository := repositories.NewNewsRepository(gormDB, node, mediaRepository, userRepository, notificationRepository, postRepository)
	newsService := services.NewNewsService(userRepository, postRepository, mediaRepository, placeRepository, newsRepository)
	matchesRepository := repositories.NewMatchesRepository(gormDB, engagementRepository)
	matchesService := services.NewMatchService(userRepository, postRepository, mediaRepository, matchesRepository)
	socketService := socket.NewSocketService(gormDB)
	chatRepository := repositories.NewChatRepository(gormDB, node, postRepository, userRepository, notificationRepository)
	chatService := services.NewChatService(socketService, userRepository, postRepository, mediaRepository, matchesRepository, chatRepository, notificationRepository)
	notificationsService := services.NewNotificationsService(notificationRepository)
	paymentRepository := repositories.NewPaymentRepository(gormDB, node, mediaRepository, userRepository, notificationRepository)
	paymentService := services.NewPaymentService(paymentRepository, userRepository, postRepository, mediaRepository)
	mcpServer := mcp.NewMCPServer()
	aiService := services.NewAIService(mcpServer, userRepository, postRepository, mediaRepository, placeRepository, newsRepository)
	sitemapRepository := repositories.NewSitemapRepository(gormDB)
	router := routes.NewRouter(gormDB, node, userService, postService, placeService, newsService, matchesService, chatService, notificationsService, paymentService, aiService, userRepository, notificationRepository, sitemapRepository, reader)
	app := &App{
		DB:            gormDB,
		Router:        router,
		SnowFlakeNode: node,
	}
	return app, nil
}
