package news

import (
	"fmt"
	"net/url"
	"strings"
)

type RSSSource struct {
	ID      string
	Name    string
	URL     string
	Enabled bool
}

type Language struct {
	Code           string   // ex: "tr"
	CountryCode    string   // ex: "TR"
	SearchKeywords []string // LGBT ile ilgili kelimeler listesi
	HL             string
	GL             string
	CEID           string
}

var Languages = []Language{
	{
		Code: "tr", CountryCode: "TR",
		SearchKeywords: []string{"gay", "homoseksüel", "lezbiyen", "biseksüel", "transseksüel", "travesti", "queer", "interseks", "nonbinary", "panseksüel", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "tr", GL: "TR", CEID: "TR:tr",
	},
	{
		Code: "en", CountryCode: "US",
		SearchKeywords: []string{"gay", "homosexual", "lesbian", "bisexual", "transgender", "queer", "intersex", "nonbinary", "pansexual", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "en-US", GL: "US", CEID: "US:en",
	},
	{
		Code: "es", CountryCode: "ES",
		SearchKeywords: []string{"gay", "homosexual", "lesbiana", "bisexual", "transgénero", "travesti", "queer", "intersexual", "no binario", "pansexual", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "es", GL: "ES", CEID: "ES:es",
	},
	{
		Code: "fr", CountryCode: "FR",
		SearchKeywords: []string{"gay", "homosexuel", "lesbienne", "bisexuel", "transgenre", "travesti", "queer", "intersexe", "non binaire", "pansexuel", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "fr", GL: "FR", CEID: "FR:fr",
	},
	{
		Code: "de", CountryCode: "DE",
		SearchKeywords: []string{"schwul", "homosexuell", "lesbisch", "bisexuell", "transgender", "travesti", "queer", "intersexuell", "nichtbinär", "pansexuell", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "de", GL: "DE", CEID: "DE:de",
	},
	{
		Code: "ru", CountryCode: "RU",
		SearchKeywords: []string{"гей", "гомосексуалист", "лесбиянка", "бисексуал", "трансгендер", "квир", "интерсекс", "небинарный", "пансексуал", "ЛГБТ", "ЛГБТК", "ЛГБТКИА"},
		HL:             "ru", GL: "RU", CEID: "RU:ru",
	},
	{
		Code: "pt", CountryCode: "PT",
		SearchKeywords: []string{"gay", "homossexual", "lésbica", "bissexual", "transgênero", "travesti", "queer", "intersexo", "não binário", "pansexual", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "pt", GL: "PT", CEID: "PT:pt",
	},
	{
		Code: "it", CountryCode: "IT",
		SearchKeywords: []string{"gay", "omosessuale", "lesbica", "bisessuale", "transgender", "travestito", "queer", "intersessuale", "non binario", "pansessuale", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "it", GL: "IT", CEID: "IT:it",
	},
	{
		Code: "ja", CountryCode: "JP",
		SearchKeywords: []string{"ゲイ", "レズビアン", "バイセクシャル", "トランスジェンダー", "クィア", "インターセックス", "ノンバイナリー", "パンセクシュアル", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "ja", GL: "JP", CEID: "JP:ja",
	},
	{
		Code: "ko", CountryCode: "KR",
		SearchKeywords: []string{"게이", "레즈비언", "양성애자", "트랜스젠더", "퀴어", "인터섹스", "논바이너리", "범성애자", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "ko", GL: "KR", CEID: "KR:ko",
	},
	{
		Code: "zh", CountryCode: "CN",
		SearchKeywords: []string{"同性恋", "双性恋", "跨性别", "酷儿", "间性人", "非二元", "泛性恋", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "zh-CN", GL: "CN", CEID: "CN:zh-Hans",
	},
	{
		Code: "ar", CountryCode: "SA",
		SearchKeywords: []string{"مثلي", "مثلية", "مزدوج", "متحول", "كوير", "بين الجنسين", "بانسكسوال", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "ar", GL: "SA", CEID: "SA:ar",
	},
	{
		Code: "he", CountryCode: "IL",
		SearchKeywords: []string{"הומו", "לסבית", "ביסקסואל", "טרנסג'נדר", "קוויר", "אינטרסקס", "נון-בינארי", "פנסקסואל", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "he", GL: "IL", CEID: "IL:he",
	},
	{
		Code: "hi", CountryCode: "IN",
		SearchKeywords: []string{"गे", "समलैंगिक", "लेस्बियन", "बाइसेक्शुअल", "ट्रांसजेंडर", "क्वीर", "इंटरसेक्स", "नॉनबाइनरी", "पैनसेक्सुअल", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "hi", GL: "IN", CEID: "IN:hi",
	},
	{
		Code: "id", CountryCode: "ID",
		SearchKeywords: []string{"gay", "lesbian", "biseksual", "transgender", "queer", "interseks", "nonbiner", "panseksual", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "id", GL: "ID", CEID: "ID:id",
	},
	{
		Code: "nl", CountryCode: "NL",
		SearchKeywords: []string{"homo", "lesbisch", "biseksueel", "transgender", "queer", "intersekse", "non-binair", "panseksueel", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "nl", GL: "NL", CEID: "NL:nl",
	},
	{
		Code: "pl", CountryCode: "PL",
		SearchKeywords: []string{"gej", "homoseksualista", "lesbijka", "biseksualista", "transpłciowy", "queer", "interseksualny", "niebinarny", "panseksualny", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "pl", GL: "PL", CEID: "PL:pl",
	},
	{
		Code: "sv", CountryCode: "SE",
		SearchKeywords: []string{"gay", "homosexuell", "lesbisk", "bisexuell", "transgender", "queer", "intersexuell", "ickebinär", "pansexuell", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "sv", GL: "SE", CEID: "SE:sv",
	},
	{
		Code: "ro", CountryCode: "RO",
		SearchKeywords: []string{"gay", "homosexual", "lesbiană", "bisexual", "transgender", "queer", "intersexual", "non-binar", "pansexual", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "ro", GL: "RO", CEID: "RO:ro",
	},
	{
		Code: "vi", CountryCode: "VN",
		SearchKeywords: []string{"đồng tính", "đồng tính nữ", "lưỡng tính", "chuyển giới", "queer", "liên giới tính", "phi nhị phân", "đa giới tính", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "vi", GL: "VN", CEID: "VN:vi",
	},
	{
		Code: "ne", CountryCode: "NP",
		SearchKeywords: []string{"gay", "लेस्बियन", "बाइसेक्सुअल", "ट्रान्सजेन्डर", "क्वियर", "इन्टरसेक्स", "ननबाइनरी", "प्यानसेक्सुअल", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "ne", GL: "NP", CEID: "NP:ne",
	},
	{
		Code: "tw", CountryCode: "TW",
		SearchKeywords: []string{"同志", "同性戀", "跨性別", "酷兒", "變性", "性少數", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "zh-TW", GL: "TW", CEID: "TW:zh-Hant",
	},
	{
		Code: "th", CountryCode: "TH",
		SearchKeywords: []string{"เกย์", "เลสเบี้ยน", "ไบเซ็กชวล", "ทรานส์เจนเดอร์", "ควียร์", "อินเตอร์เซ็กซ์", "โนบินารี", "แพนเซ็กชวล", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "th", GL: "TH", CEID: "TH:th",
	},
	{
		Code: "tl", CountryCode: "PH",
		SearchKeywords: []string{"bakla", "lesbiyana", "biysekswal", "transgender", "queer", "intersex", "nonbinary", "pansexual", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "tl", GL: "PH", CEID: "PH:tl",
	},
	{
		Code: "km", CountryCode: "KH",
		SearchKeywords: []string{"កាម៉េរ៉ូ", "ស្រឡាញ់ផ្លូវភេទដូចគ្នា", "បីភេទ", "បំលែងភេទ", "គួ", "អន្តរភេទ", "អតិបរិមា", "LGBT", "LGBTQ", "LGBTQIA"},
		HL:             "km", GL: "KH", CEID: "KH:km",
	},
}

var GoogleNewsSource = RSSSource{
	ID:      "gnews",
	Name:    "Google News (Dynamic)",
	URL:     "https://news.google.com/rss/search?q=(%s) when:7d&hl=%s&gl=%s&ceid=%s",
	Enabled: true,
}

var StaticRSSSources = []RSSSource{

	// adana
	{ID: "adanahabermerkezi", Name: "adanahabermerkezi", URL: "https://www.adanahabermerkezi.com/rss", Enabled: true},
	{ID: "adanatorosgazetesi", Name: "adanatorosgazetesi", URL: "https://adanatorosgazetesi.net/rss", Enabled: true},
	{ID: "5ocakgazetesi", Name: "5ocakgazetesi", URL: "https://www.5ocakgazetesi.com/rss", Enabled: true},
	{ID: "adananinsesi", Name: "adananinsesi", URL: "https://www.adananinsesi.com/rss.xml", Enabled: true},
	{ID: "kucuksaat", Name: "kucuksaat", URL: "https://www.kucuksaat.com/rss", Enabled: true},
	{ID: "adanapost", Name: "adanapost", URL: "https://www.adanapost.com/service/rss.php", Enabled: true},
	{ID: "haberadanagazetesi-genel", Name: "haberadanagazetesi-Genel", URL: "http://www.haberadanagazetesi.com/rss-genel-0.xml", Enabled: true},
	{ID: "haberadanagazetesi-asayis", Name: "haberadanagazetesi-Asayiş", URL: "http://www.haberadanagazetesi.com/rss-asayis-7.xml", Enabled: true},
	{ID: "haberadanagazetesi-bilim", Name: "haberadanagazetesi-Bilim", URL: "http://www.haberadanagazetesi.com/rss-bilim-17.xml", Enabled: true},
	{ID: "haberadanagazetesi-cocuk", Name: "haberadanagazetesi-Çocuk", URL: "http://www.haberadanagazetesi.com/rss-cocuk-19.xml", Enabled: true},
	{ID: "haberadanagazetesi-diger", Name: "haberadanagazetesi-Diğer", URL: "http://www.haberadanagazetesi.com/rss-diger-50.xml", Enabled: true},
	{ID: "haberadanagazetesi-dunya", Name: "haberadanagazetesi-Dünya", URL: "http://www.haberadanagazetesi.com/rss-dunya-2.xml", Enabled: true},
	{ID: "haberadanagazetesi-egitim", Name: "haberadanagazetesi-Eğitim", URL: "http://www.haberadanagazetesi.com/rss-egitim-11.xml", Enabled: true},
	{ID: "haberadanagazetesi-ekonomi", Name: "haberadanagazetesi-Ekonomi", URL: "http://www.haberadanagazetesi.com/rss-ekonomi-3.xml", Enabled: true},
	{ID: "haberadanagazetesi-gundem", Name: "haberadanagazetesi-Gündem", URL: "http://www.haberadanagazetesi.com/rss-gundem-15.xml", Enabled: true},
	{ID: "haberadanagazetesi-kultur", Name: "haberadanagazetesi-Kültür", URL: "http://www.haberadanagazetesi.com/rss-kultur-6.xml", Enabled: true},
	{ID: "haberadanagazetesi-ilan", Name: "haberadanagazetesi-Resmi İlan", URL: "http://www.haberadanagazetesi.com/rss-resmi_ilan-16.xml", Enabled: true},
	{ID: "haberadanagazetesi-saglik", Name: "haberadanagazetesi-Sağlık", URL: "http://www.haberadanagazetesi.com/rss-saglik-9.xml", Enabled: true},
	{ID: "haberadanagazetesi-sanat", Name: "haberadanagazetesi-Sanat", URL: "http://www.haberadanagazetesi.com/rss-sanat-18.xml", Enabled: true},
	{ID: "haberadanagazetesi-siyaset", Name: "haberadanagazetesi-Siyaset", URL: "http://www.haberadanagazetesi.com/rss-siyaset-10.xml", Enabled: true},
	{ID: "haberadanagazetesi-spor", Name: "haberadanagazetesi-Spor", URL: "http://www.haberadanagazetesi.com/rss-spor-5.xml", Enabled: true},
	{ID: "haberadanagazetesi-teknoloji", Name: "haberadanagazetesi-Teknoloji", URL: "http://www.haberadanagazetesi.com/rss-teknoloji-4.xml", Enabled: true},
	{ID: "haberadanagazetesi-turizm", Name: "haberadanagazetesi-Turizm", URL: "http://www.haberadanagazetesi.com/rss-turizm-21.xml", Enabled: true},
	{ID: "haberadanagazetesi-yasam", Name: "haberadanagazetesi-Yaşam", URL: "http://www.haberadanagazetesi.com/rss-yasam-8.xml", Enabled: true},

	//bingol
	{ID: "bingolsurmanset", Name: "bingolsurmanset", URL: "https://www.bingolsurmanset.com/rss", Enabled: true},
	{ID: "bingolkenthaber", Name: "bingolkenthaber", URL: "https://www.bingolkenthaber.com/rss", Enabled: true},
	{ID: "bingolonline", Name: "bingolonline", URL: "https://www.bingolonline.com/rss/", Enabled: true},
	{ID: "bingolnethaber", Name: "bingolnethaber", URL: "https://www.bingolnethaber.com/rss.xml", Enabled: true},
	{ID: "bingolunsesi", Name: "bingolunsesi", URL: "https://bingolunsesi.com/rss.xml", Enabled: true},
	{ID: "capakcurgazetesi", Name: "capakcurgazetesi", URL: "https://www.capakcurgazetesi.com.tr/rss.xml", Enabled: true},
	{ID: "gencinsesi", Name: "gencinsesi", URL: "https://www.gencinsesi.com/feed/", Enabled: true},

	//izmir
	{ID: "egedesonsoz", Name: "egedesonsoz", URL: "https://www.egedesonsoz.com/rss", Enabled: true},
	{ID: "izgazete", Name: "izgazete", URL: "https://www.izgazete.net/rss", Enabled: true},
	{ID: "dokuzeylul", Name: "dokuzeylul", URL: "https://www.dokuzeylul.com/rss", Enabled: true},
	{ID: "izmirhaberajansi", Name: "izmirhaberajansi", URL: "https://www.izmirhaberajansi.com/rss", Enabled: true},

	//bursa
	{ID: "yesilgazete", Name: "yesilgazete", URL: "https://yesilgazete.org/feed/", Enabled: true},
	{ID: "bursadabugun", Name: "bursadabugun", URL: "https://www.bursadabugun.com/rss/?feed=haberler", Enabled: true},
	{ID: "bursahaber", Name: "bursahaber", URL: "https://www.bursahaber.com/rss", Enabled: true},
	{ID: "olay", Name: "olay", URL: "https://www.olay.com.tr/feed", Enabled: true},

	//ankara
	{ID: "daktilo1984", Name: "daktilo1984", URL: "https://daktilo1984.com/feed/", Enabled: true},
	{ID: "haberankara", Name: "haberankara", URL: "https://www.haberankara.com/rss", Enabled: true},
	{ID: "baskentgazete", Name: "baskentgazete", URL: "https://www.baskentgazete.com.tr/rss", Enabled: true},
	{ID: "yeniankara", Name: "yeniankara", URL: "https://www.yeniankara.com.tr/export/rss", Enabled: true},
	{ID: "ankaradar", Name: "ankaradar", URL: "https://ankaradar.com/rss", Enabled: true},
	{ID: "ilefdergisi EN", Name: "ilefdergisi EN", URL: "http://ilefdergisi.ankara.edu.tr/tr/pub/rss/lastissue/en", Enabled: true},
	{ID: "ilefdergisi TR", Name: "ilefdergisi TR", URL: "http://ilefdergisi.ankara.edu.tr/tr/pub/rss/lastissue/tr", Enabled: true},
	{ID: "haberglobal", Name: "haberglobal", URL: "https://haberglobal.com/rss", Enabled: true},
	{ID: "medyaankara", Name: "medyaankara", URL: "https://medyaankara.com/rss", Enabled: true},
	{ID: "evrensel", Name: "evrensel", URL: "https://www.evrensel.net/rss/haber.xml", Enabled: true},
	{ID: "bizimankara", Name: "bizimankara", URL: "https://www.bizimankara.com.tr/rss", Enabled: true},

	{ID: "islamianaliz", Name: "islamianaliz", URL: "https://islamianaliz.com/rss.xml", Enabled: true},
	{ID: "tevhidhaber", Name: "tevhidhaber", URL: "https://www.tevhidhaber.com/service/rss.php", Enabled: true},
	{ID: "mirathaber", Name: "mirathaber", URL: "https://www.mirathaber.com/feed/", Enabled: true},
	{ID: "haksozhaber", Name: "haksozhaber", URL: "https://www.haksozhaber.net/rss/", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/editors_pick_rss", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss/tag/bitcoin", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss/tag/altcoin", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss/tag/blockchain", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss/tag/regulation", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss/tag/monero", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss/category/analysis", Enabled: true},
	{ID: "cointelegraph", Name: "cointelegraph", URL: "https://cointelegraph.com/rss/category/top-10-cryptocurrencies", Enabled: true},
	{ID: "coindesk", Name: "coindesk", URL: "https://www.coindesk.com/arc/outboundfeeds/rss", Enabled: true},
	{ID: "ambcrypto", Name: "ambcrypto", URL: "https://ambcrypto.com/feed/", Enabled: true},
	{ID: "bitcoinist", Name: "bitcoinist", URL: "https://bitcoinist.com/feed/", Enabled: true},
	{ID: "coincodex", Name: "coincodex", URL: "https://coincodex.com/rss", Enabled: true},
	{ID: "dailyhodl", Name: "dailyhodl", URL: "https://dailyhodl.com/feed/", Enabled: true},
	{ID: "decrypt", Name: "decrypt", URL: "https://decrypt.co/feed", Enabled: true},
	{ID: "theblock", Name: "theblock", URL: "https://www.theblock.co/rss.xml", Enabled: true},
	{ID: "mynet", Name: "mynet", URL: "https://www.mynet.com/rss/publisher-finans.rss", Enabled: true},
	{ID: "ft", Name: "ft", URL: "https://www.ft.com/rss/home/international", Enabled: true},
	{ID: "fortune", Name: "fortune", URL: "https://fortune.com/feed/fortune-feeds/?id=3230629", Enabled: true},
	{ID: "business-standard", Name: "business-standard", URL: "https://www.business-standard.com/rss/latest.rss", Enabled: true},
	{ID: "thestreet", Name: "thestreet", URL: "https://www.thestreet.com/.rss/feed/a4a58455-5a41-4dfa-899c-86c49b653ed8.xml", Enabled: true},
	{ID: "money", Name: "money", URL: "https://money.com/money/feed/", Enabled: true},
	{ID: "gfmag", Name: "gfmag", URL: "https://gfmag.com/feed/", Enabled: true},
	{ID: "worldfinance", Name: "worldfinance", URL: "https://www.worldfinance.com/feed", Enabled: true},
	{ID: "nasdaq", Name: "nasdaq", URL: "https://www.nasdaq.com/feed/rssoutbound?category=Cryptocurrencies", Enabled: true},
	{ID: "nasdaq", Name: "nasdaq", URL: "https://www.nasdaq.com/feed/nasdaq-original/rss.xml", Enabled: true},
	{ID: "nasdaq", Name: "nasdaq", URL: "https://www.nasdaq.com/feed/rssoutbound?category=Stocks", Enabled: true},
	{ID: "bloomberg", Name: "bloomberg", URL: "https://feeds.bloomberg.com/markets/news.rss", Enabled: true},
	{ID: "bloomberght", Name: "Bloomberg HT", URL: "https://www.bloomberght.com/rss", Enabled: true},
	{ID: "bigpara", Name: "Bigpara", URL: "https://bigpara.hurriyet.com.tr/rss/", Enabled: true},
	{ID: "cnbce", Name: "CNBC-e", URL: "https://www.cnbce.com/rss", Enabled: true},
	{ID: "doviz", Name: "Döviz", URL: "https://www.doviz.com/news/rss", Enabled: true},
	{ID: "ekonomigazetesi", Name: "Ekonomi Gazetesi", URL: "https://www.ekonomigazetesi.com/rss.xml", Enabled: true},
	{ID: "forbestr", Name: "Forbes Türkiye", URL: "https://www.forbes.com.tr/rss", Enabled: true},
	{ID: "foreks", Name: "Foreks", URL: "https://www.foreks.com/rss/", Enabled: true},
	{ID: "investing_genel", Name: "Investing Genel", URL: "https://tr.investing.com/rss/market_overview.rss", Enabled: true},
	{ID: "investing_kripto", Name: "Investing Kripto", URL: "https://tr.investing.com/rss/302.rss", Enabled: true},
	{ID: "investing_doviz", Name: "Investing Döviz", URL: "https://tr.investing.com/rss/forex.rss", Enabled: true},
	{ID: "investing_hisse", Name: "Investing Hisse Senedi", URL: "https://tr.investing.com/rss/stock.rss", Enabled: true},
	{ID: "investing_emtia", Name: "Investing Emtia", URL: "https://tr.investing.com/rss/commodities.rss", Enabled: true},
	{ID: "investing_tahvil", Name: "Investing Tahvil", URL: "https://tr.investing.com/rss/bonds.rss", Enabled: true},
	{ID: "investing_haberler", Name: "Investing Haberler", URL: "https://tr.investing.com/rss/news.rss", Enabled: true},
	{ID: "megabayt_ekonomi", Name: "Megabayt Ekonomi", URL: "https://www.megabayt.com/rss/categorynews/ekonomi", Enabled: true},
	{ID: "megabayt_kripto", Name: "Megabayt Kripto Para", URL: "https://www.megabayt.com/rss/categorynews/kripto-para", Enabled: true},
	{ID: "sozcu_borsa", Name: "Sözcü Borsa", URL: "https://www.sozcu.com.tr/feeds-rss-category-borsa", Enabled: true},
	{ID: "sozcu_ekonomi", Name: "Sözcü Ekonomi", URL: "https://www.sozcu.com.tr/feeds-rss-category-ekonomi", Enabled: true},
	{ID: "sozcu_emlak", Name: "Sözcü Emlak", URL: "https://www.sozcu.com.tr/feeds-rss-category-emlak", Enabled: true},
	{ID: "sozcu_emtia", Name: "Sözcü Emtia", URL: "https://www.sozcu.com.tr/feeds-rss-category-emtia", Enabled: true},
	{ID: "sozcu_finans", Name: "Sözcü Finans", URL: "https://www.sozcu.com.tr/feeds-rss-category-finans", Enabled: true},
	{ID: "sozcu_kripto", Name: "Sözcü Kripto", URL: "https://www.sozcu.com.tr/feeds-rss-category-kripto", Enabled: true},
	{ID: "isindetayi", Name: "İşin Detayı", URL: "https://www.isindetayi.com/rss", Enabled: true},
	{ID: "isindetayi_borsa", Name: "İşin Detayı Borsa", URL: "https://www.isindetayi.com/rss/borsa", Enabled: true},
	{ID: "isindetayi_ekonomi", Name: "İşin Detayı Ekonomi", URL: "https://www.isindetayi.com/rss/ekonomi", Enabled: true},
	{ID: "isindetayi_finans", Name: "İşin Detayı Finans", URL: "https://www.isindetayi.com/rss/finans", Enabled: true},
	{ID: "isindetayi_gayrimenkul", Name: "İşin Detayı Gayrimenkul", URL: "https://www.isindetayi.com/rss/gayrimenkul", Enabled: true},
	{ID: "isindetayi_isdunyasi", Name: "İşin Detayı İş Dünyası", URL: "https://www.isindetayi.com/rss/is-dunyasi", Enabled: true},
	{ID: "isindetayi_lojistik", Name: "İşin Detayı Lojistik", URL: "https://www.isindetayi.com/rss/lojistik", Enabled: true},
	{ID: "isindetayi_sirkethaberleri", Name: "İşin Detayı Şirket Haberleri", URL: "https://www.isindetayi.com/rss/sirket-haberleri", Enabled: true},
	{ID: "megabayt_sirkethaberleri", Name: "Megabayt Şirket Haberleri", URL: "https://www.megabayt.com/rss/categorynews/sirket-haberleri", Enabled: true},
	{ID: "midas", Name: "Midas", URL: "https://www.getmidas.com/feed/", Enabled: true},
	{ID: "ntv_gundem", Name: "NTV Gündem", URL: "https://www.ntv.com.tr/gundem.rss", Enabled: true},
	{ID: "ntv_dunya_kupasi_2018", Name: "NTV Dünya Kupası 2018", URL: "https://www.ntv.com.tr/dunya-kupasi-2018.rss", Enabled: true},
	{ID: "ntv_turkiye", Name: "NTV Türkiye", URL: "https://www.ntv.com.tr/turkiye.rss", Enabled: true},
	{ID: "ntv_dunya", Name: "NTV Dünya", URL: "https://www.ntv.com.tr/dunya.rss", Enabled: true},
	{ID: "ntv_ekonomi", Name: "NTV Ekonomi", URL: "https://www.ntv.com.tr/ekonomi.rss", Enabled: true},
	{ID: "ntv_spor", Name: "NTV Spor", URL: "https://www.ntv.com.tr/spor.rss", Enabled: true},
	{ID: "ntv_teknoloji", Name: "NTV Teknoloji", URL: "https://www.ntv.com.tr/teknoloji.rss", Enabled: true},
	{ID: "ntv_yasam", Name: "NTV Yaşam", URL: "https://www.ntv.com.tr/yasam.rss", Enabled: true},
	{ID: "ntv_seyahat", Name: "NTV Seyahat", URL: "https://www.ntv.com.tr/seyahat.rss", Enabled: true},
	{ID: "ntv_saglik", Name: "NTV Sağlık", URL: "https://www.ntv.com.tr/saglik.rss", Enabled: true},
	{ID: "ntv_sanat", Name: "NTV Sanat", URL: "https://www.ntv.com.tr/sanat.rss", Enabled: true},
	{ID: "ntv_otomobil", Name: "NTV Otomobil", URL: "https://www.ntv.com.tr/otomobil.rss", Enabled: true},
	{ID: "ntv_egitim", Name: "NTV Eğitim", URL: "https://www.ntv.com.tr/egitim.rss", Enabled: true},
	{ID: "aa_guncel", Name: "Anadolu Ajansı Güncel", URL: "https://www.aa.com.tr/tr/rss/default?cat=guncel", Enabled: true},
	{ID: "anayurt_sondakika", Name: "Anayurt Son Dakika", URL: "http://www.anayurtgazetesi.com/sondakika.xml", Enabled: true},
	{ID: "cumhuriyet_sondakika", Name: "Cumhuriyet Son Dakika", URL: "http://www.cumhuriyet.com.tr/rss/son_dakika.xml", Enabled: true},
	{ID: "cumhuriyet_6", Name: "Cumhuriyet Kategori 6", URL: "http://www.cumhuriyet.com.tr/rss/6.xml", Enabled: true},
	{ID: "cumhuriyet_17", Name: "Cumhuriyet Kategori 17", URL: "http://www.cumhuriyet.com.tr/rss/17.xml", Enabled: true},
	{ID: "cumhuriyet_73", Name: "Cumhuriyet Kategori 73", URL: "http://www.cumhuriyet.com.tr/rss/73.xml", Enabled: true},
	{ID: "cumhuriyet_24", Name: "Cumhuriyet Kategori 24", URL: "http://www.cumhuriyet.com.tr/rss/24.xml", Enabled: true},
	{ID: "cumhuriyet_32", Name: "Cumhuriyet Kategori 32", URL: "http://www.cumhuriyet.com.tr/rss/32.xml", Enabled: true},
	{ID: "cumhuriyet_33", Name: "Cumhuriyet Kategori 33", URL: "http://www.cumhuriyet.com.tr/rss/33.xml", Enabled: true},
	{ID: "cumhuriyet_34", Name: "Cumhuriyet Kategori 34", URL: "http://www.cumhuriyet.com.tr/rss/34.xml", Enabled: true},
	{ID: "cumhuriyet_35", Name: "Cumhuriyet Kategori 35", URL: "http://www.cumhuriyet.com.tr/rss/35.xml", Enabled: true},
	{ID: "cumhuriyet_36", Name: "Cumhuriyet Kategori 36", URL: "http://www.cumhuriyet.com.tr/rss/36.xml", Enabled: true},
	{ID: "cumhuriyet_46", Name: "Cumhuriyet Kategori 46", URL: "http://www.cumhuriyet.com.tr/rss/46.xml", Enabled: true},
	{ID: "cumhuriyet_70", Name: "Cumhuriyet Kategori 70", URL: "http://www.cumhuriyet.com.tr/rss/70.xml", Enabled: true},
	{ID: "cumhuriyet_19", Name: "Cumhuriyet Kategori 19", URL: "http://www.cumhuriyet.com.tr/rss/19.xml", Enabled: true},
	{ID: "cumhuriyet_7", Name: "Cumhuriyet Kategori 7", URL: "http://www.cumhuriyet.com.tr/rss/7.xml", Enabled: true},
	{ID: "cumhuriyet_14", Name: "Cumhuriyet Kategori 14", URL: "http://www.cumhuriyet.com.tr/rss/14.xml", Enabled: true},
	{ID: "cumhuriyet_15", Name: "Cumhuriyet Kategori 15", URL: "http://www.cumhuriyet.com.tr/rss/15.xml", Enabled: true},
	{ID: "cumhuriyet_16", Name: "Cumhuriyet Kategori 16", URL: "http://www.cumhuriyet.com.tr/rss/16.xml", Enabled: true},
	{ID: "cumhuriyet_20", Name: "Cumhuriyet Kategori 20", URL: "http://www.cumhuriyet.com.tr/rss/20.xml", Enabled: true},
	{ID: "cumhuriyet_72", Name: "Cumhuriyet Kategori 72", URL: "http://www.cumhuriyet.com.tr/rss/72.xml", Enabled: true},
	{ID: "cumhuriyet_12", Name: "Cumhuriyet Kategori 12", URL: "http://www.cumhuriyet.com.tr/rss/12.xml", Enabled: true},
	{ID: "cumhuriyet_3", Name: "Cumhuriyet Kategori 3", URL: "http://www.cumhuriyet.com.tr/rss/3.xml", Enabled: true},
	{ID: "cumhuriyet_9", Name: "Cumhuriyet Kategori 9", URL: "http://www.cumhuriyet.com.tr/rss/9.xml", Enabled: true},
	{ID: "cumhuriyet_11", Name: "Cumhuriyet Kategori 11", URL: "http://www.cumhuriyet.com.tr/rss/11.xml", Enabled: true},
	{ID: "cumhuriyet_10", Name: "Cumhuriyet Kategori 10", URL: "http://www.cumhuriyet.com.tr/rss/10.xml", Enabled: true},
	{ID: "dunya_com", Name: "Dünya.com", URL: "https://www.dunya.com/rss?dunya", Enabled: true},
	{ID: "haberturk", Name: "Habertürk", URL: "http://www.haberturk.com/rss", Enabled: true},
	{ID: "hurriyet_anasayfa", Name: "Hürriyet Anasayfa", URL: "http://www.hurriyet.com.tr/rss/anasayfa", Enabled: true},
	{ID: "hurriyet_gundem", Name: "Hürriyet Gündem", URL: "http://www.hurriyet.com.tr/rss/gundem", Enabled: true},
	{ID: "hurriyet_ekonomi", Name: "Hürriyet Ekonomi", URL: "http://www.hurriyet.com.tr/rss/ekonomi", Enabled: true},
	{ID: "hurriyet_magazin", Name: "Hürriyet Magazin", URL: "http://www.hurriyet.com.tr/rss/magazin", Enabled: true},
	{ID: "hurriyet_spor", Name: "Hürriyet Spor", URL: "http://www.hurriyet.com.tr/rss/spor", Enabled: true},
	{ID: "hurriyet_dunya", Name: "Hürriyet Dünya", URL: "http://www.hurriyet.com.tr/rss/dunya", Enabled: true},
	{ID: "hurriyet_teknoloji", Name: "Hürriyet Teknoloji", URL: "http://www.hurriyet.com.tr/rss/teknoloji", Enabled: true},
	{ID: "hurriyet_astroloji", Name: "Hürriyet Astroloji", URL: "http://www.hurriyet.com.tr/rss/astroloji", Enabled: true},
	{ID: "milat", Name: "Milat Gazetesi", URL: "http://www.milatgazetesi.com/rss.php", Enabled: true},
	{ID: "milliyet_magazin", Name: "Milliyet Magazin", URL: "http://www.milliyet.com.tr/rss/rssNew/magazinRss.xml", Enabled: true},
	{ID: "milliyet_gundem", Name: "Milliyet Gündem", URL: "http://www.milliyet.com.tr/rss/rssNew/gundemRss.xml", Enabled: true},
	{ID: "milliyet_kitap", Name: "Milliyet Kitap", URL: "http://www.milliyet.com.tr/rss/rssNew/kitapRss.xml", Enabled: true},
	{ID: "milliyet_egitim", Name: "Milliyet Eğitim", URL: "http://www.milliyet.com.tr/rss/rssNew/egitimRss.xml", Enabled: true},
	{ID: "milliyet_dunya", Name: "Milliyet Dünya", URL: "http://www.milliyet.com.tr/rss/rssNew/dunyaRss.xml", Enabled: true},
	{ID: "milliyet_ekonomi", Name: "Milliyet Ekonomi", URL: "http://www.milliyet.com.tr/rss/rssNew/ekonomiRss.xml", Enabled: true},
	{ID: "milliyet_siyaset", Name: "Milliyet Siyaset", URL: "http://www.milliyet.com.tr/rss/rssNew/siyasetRss.xml", Enabled: true},
	{ID: "milliyet_otomobil", Name: "Milliyet Otomobil", URL: "http://www.milliyet.com.tr/rss/rssNew/otomobilRss.xml", Enabled: true},
	{ID: "milliyet_teknoloji", Name: "Milliyet Teknoloji", URL: "http://www.milliyet.com.tr/rss/rssNew/teknolojiRss.xml", Enabled: true},
	{ID: "milliyet_milliyettatil", Name: "Milliyet Tatil", URL: "http://www.milliyet.com.tr/rss/rssNew/milliyettatilRss.xml", Enabled: true},
	{ID: "milliyet_konutemlak", Name: "Milliyet Konut Emlak", URL: "http://www.milliyet.com.tr/rss/rssNew/konutemlakRss.xml", Enabled: true},
	{ID: "milliyet_aile", Name: "Milliyet Aile", URL: "http://www.milliyet.com.tr/rss/rssNew/aileRss.xml", Enabled: true},
	{ID: "milliyet_saglik", Name: "Milliyet Sağlık", URL: "http://www.milliyet.com.tr/rss/rssNew/saglikRss.xml", Enabled: true},
	{ID: "milliyet_yemek", Name: "Milliyet Yemek", URL: "http://www.milliyet.com.tr/rss/rssNew/yemekRss.xml", Enabled: true},
	{ID: "milliyet_diyet", Name: "Milliyet Diyet", URL: "http://www.milliyet.com.tr/rss/rssNew/diyetRss.xml", Enabled: true},
	{ID: "milliyet_sondakika", Name: "Milliyet Son Dakika", URL: "http://www.milliyet.com.tr/rss/rssNew/SonDakikaRss.xml", Enabled: true},
	{ID: "sabah_ekonomi", Name: "Sabah Ekonomi", URL: "https://www.sabah.com.tr/rss/ekonomi.xml", Enabled: true},
	{ID: "sabah_spor", Name: "Sabah Spor", URL: "https://www.sabah.com.tr/rss/spor.xml", Enabled: true},
	{ID: "sabah_gundem", Name: "Sabah Gündem", URL: "https://www.sabah.com.tr/rss/gundem.xml", Enabled: true},
	{ID: "sabah_yasam", Name: "Sabah Yaşam", URL: "https://www.sabah.com.tr/rss/yasam.xml", Enabled: true},
	{ID: "sabah_dunya", Name: "Sabah Dünya", URL: "https://www.sabah.com.tr/rss/dunya.xml", Enabled: true},
	{ID: "sabah_teknoloji", Name: "Sabah Teknoloji", URL: "https://www.sabah.com.tr/rss/teknoloji.xml", Enabled: true},
	{ID: "sabah_turizm", Name: "Sabah Turizm", URL: "https://www.sabah.com.tr/rss/turizm.xml", Enabled: true},
	{ID: "sabah_otomobil", Name: "Sabah Otomobil", URL: "https://www.sabah.com.tr/rss/otomobil.xml", Enabled: true},
	{ID: "sabah_anasayfa", Name: "Sabah Anasayfa", URL: "https://www.sabah.com.tr/rss/anasayfa.xml", Enabled: true},
	{ID: "sabah_saglik", Name: "Sabah Sağlık", URL: "https://www.sabah.com.tr/rss/saglik.xml", Enabled: true},
	{ID: "sabah_gununicinden", Name: "Sabah Günün İçinden", URL: "https://www.sabah.com.tr/rss/gununicinden.xml", Enabled: true},
	{ID: "sabah_sondakika", Name: "Sabah Son Dakika", URL: "https://www.sabah.com.tr/rss/sondakika.xml", Enabled: true},
	{ID: "sabah_galatasaray", Name: "Sabah Galatasaray", URL: "https://www.sabah.com.tr/rss/galatasaray.xml", Enabled: true},
	{ID: "sabah_fenerbahce", Name: "Sabah Fenerbahçe", URL: "https://www.sabah.com.tr/rss/fenerbahce.xml", Enabled: true},
	{ID: "sabah_besiktas", Name: "Sabah Beşiktaş", URL: "https://www.sabah.com.tr/rss/besiktas.xml", Enabled: true},
	{ID: "sabah_trabzonspor", Name: "Sabah Trabzonspor", URL: "https://www.sabah.com.tr/rss/trabzonspor.xml", Enabled: true},
	{ID: "sabah_bursaspor", Name: "Sabah Bursaspor", URL: "https://www.sabah.com.tr/rss/bursaspor.xml", Enabled: true},
	{ID: "sabah_kultursanat", Name: "Sabah Kültür Sanat", URL: "https://www.sabah.com.tr/rss/kultur-sanat.xml", Enabled: true},
	{ID: "sabah_oyun", Name: "Sabah Oyun", URL: "https://www.sabah.com.tr/rss/oyun.xml", Enabled: true},
	{ID: "sabah_adana", Name: "Sabah Adana", URL: "https://www.sabah.com.tr/rss/adana.xml", Enabled: true},
	{ID: "star_anasayfa", Name: "Star Anasayfa", URL: "http://www.star.com.tr/rss/rss.asp", Enabled: true},
	{ID: "star_cid_500", Name: "Star Kategori 500", URL: "http://www.star.com.tr/rss/rss.asp?cid=500", Enabled: true},
	{ID: "star_cid_13", Name: "Star Kategori 13", URL: "http://www.star.com.tr/rss/rss.asp?cid=13", Enabled: true},
	{ID: "star_cid_15", Name: "Star Kategori 15", URL: "http://www.star.com.tr/rss/rss.asp?cid=15", Enabled: true},
	{ID: "star_cid_16", Name: "Star Kategori 16", URL: "http://www.star.com.tr/rss/rss.asp?cid=16", Enabled: true},
	{ID: "star_cid_17", Name: "Star Kategori 17", URL: "http://www.star.com.tr/rss/rss.asp?cid=17", Enabled: true},
	{ID: "star_cid_19", Name: "Star Kategori 19", URL: "http://www.star.com.tr/rss/rss.asp?cid=19", Enabled: true},
	{ID: "star_cid_125", Name: "Star Kategori 125", URL: "http://www.star.com.tr/rss/rss.asp?cid=125", Enabled: true},
	{ID: "star_cid_223", Name: "Star Kategori 223", URL: "http://www.star.com.tr/rss/rss.asp?cid=223", Enabled: true},

	{ID: "star_cid_130", Name: "Star Kategori 130", URL: "http://www.star.com.tr/rss/rss.asp?cid=130", Enabled: true},
	{ID: "star_cid_170", Name: "Star Kategori 170", URL: "http://www.star.com.tr/rss/rss.asp?cid=170", Enabled: true},
	{ID: "takvim_anasayfa", Name: "Takvim Anasayfa", URL: "https://www.takvim.com.tr/rss/anasayfa.xml", Enabled: true},
	{ID: "takvim_son24saat", Name: "Takvim Son 24 Saat", URL: "https://www.takvim.com.tr/rss/son24saat.xml", Enabled: true},
	{ID: "takvim_guncel", Name: "Takvim Güncel", URL: "https://www.takvim.com.tr/rss/guncel.xml", Enabled: true},
	{ID: "takvim_ekonomi", Name: "Takvim Ekonomi", URL: "https://www.takvim.com.tr/rss/ekonomi.xml", Enabled: true},
	{ID: "takvim_otomobil", Name: "Takvim Otomobil", URL: "https://www.takvim.com.tr/rss/otomobil.xml", Enabled: true},
	{ID: "takvim_saklambac", Name: "Takvim Saklambac", URL: "https://www.takvim.com.tr/rss/saklambac.xml", Enabled: true},
	{ID: "takvim_spor", Name: "Takvim Spor", URL: "https://www.takvim.com.tr/rss/spor.xml", Enabled: true},
	{ID: "takvim_yasam", Name: "Takvim Yaşam", URL: "https://www.takvim.com.tr/rss/yasam.xml", Enabled: true},
	{ID: "takvim_video", Name: "Takvim Video", URL: "https://www.takvim.com.tr/rss/video.xml", Enabled: true},
	{ID: "takvim_televizyon", Name: "Takvim Televizyon", URL: "https://www.takvim.com.tr/rss/televizyon.xml", Enabled: true},
	{ID: "turkiyegazetesi", Name: "Türkiye Gazetesi", URL: "https://www.turkiyegazetesi.com.tr/rss", Enabled: true},
	{ID: "vatan", Name: "Vatan Gazetesi", URL: "http://mix.chimpfeedr.com/68482-Vatan-Gazetesi", Enabled: true},
	{ID: "yeniasir_anasayfa", Name: "Yeni Asır Anasayfa", URL: "https://www.yeniasir.com.tr/rss/anasayfa.xml", Enabled: true},
	{ID: "yenimesaj", Name: "Yeni Mesaj", URL: "http://www.yenimesaj.com.tr/rss.php", Enabled: true},
	{ID: "yenisafak", Name: "Yeni Şafak", URL: "https://www.yenisafak.com/Rss", Enabled: true},
	{ID: "yenisafak_manset", Name: "Yeni Şafak Manşet", URL: "https://www.yenisafak.com/rss?xml=manset", Enabled: true},
	{ID: "yenisafak_gundem", Name: "Yeni Şafak Gündem", URL: "https://www.yenisafak.com/rss?xml=gundem", Enabled: true},
	{ID: "yenisafak_spor", Name: "Yeni Şafak Spor", URL: "https://www.yenisafak.com/rss?xml=spor", Enabled: true},
	{ID: "yenisafak_ekonomi", Name: "Yeni Şafak Ekonomi", URL: "https://www.yenisafak.com/rss?xml=ekonomi", Enabled: true},
	{ID: "yenisafak_teknoloji", Name: "Yeni Şafak Teknoloji", URL: "https://www.yenisafak.com/rss?xml=teknoloji", Enabled: true},
	{ID: "yenisafak_hayat", Name: "Yeni Şafak Hayat", URL: "https://www.yenisafak.com/rss?xml=hayat", Enabled: true},
	{ID: "yenisafak_dunya", Name: "Yeni Şafak Dünya", URL: "https://www.yenisafak.com/rss?xml=dunya", Enabled: true},
	{ID: "yenisafak_yazarlar", Name: "Yeni Şafak Yazarlar", URL: "https://www.yenisafak.com/rss?xml=yazarlar", Enabled: true},
	{ID: "ahaber_anasayfa", Name: "A Haber Anasayfa", URL: "https://www.ahaber.com.tr/rss/anasayfa.xml", Enabled: true},
	{ID: "ahaber_gundem", Name: "A Haber Gündem", URL: "https://www.ahaber.com.tr/rss/gundem.xml", Enabled: true},
	{ID: "ahaber_ekonomi", Name: "A Haber Ekonomi", URL: "https://www.ahaber.com.tr/rss/ekonomi.xml", Enabled: true},
	{ID: "ahaber_spor", Name: "A Haber Spor", URL: "https://www.ahaber.com.tr/rss/spor.xml", Enabled: true},
	{ID: "ahaber_yasam", Name: "A Haber Yaşam", URL: "https://www.ahaber.com.tr/rss/yasam.xml", Enabled: true},
	{ID: "ahaber_dunya", Name: "A Haber Dünya", URL: "https://www.ahaber.com.tr/rss/dunya.xml", Enabled: true},
	{ID: "ahaber_son24saat", Name: "A Haber Son 24 Saat", URL: "https://www.ahaber.com.tr/rss/son24saat.xml", Enabled: true},
	{ID: "ahaber_teknoloji", Name: "A Haber Teknoloji", URL: "https://www.ahaber.com.tr/rss/teknoloji.xml", Enabled: true},
	{ID: "ahaber_magazin", Name: "A Haber Magazin", URL: "https://www.ahaber.com.tr/rss/magazin.xml", Enabled: true},
	{ID: "ahaber_otomobil", Name: "A Haber Otomobil", URL: "https://www.ahaber.com.tr/rss/otomobil.xml", Enabled: true},
	{ID: "ahaber_haberler", Name: "A Haber Haberler", URL: "https://www.ahaber.com.tr/rss/haberler.xml", Enabled: true},
	{ID: "ahaber_din", Name: "A Haber Din", URL: "https://www.ahaber.com.tr/rss/din.xml", Enabled: true},
	{ID: "ahaber_tarih", Name: "A Haber Tarih", URL: "https://www.ahaber.com.tr/rss/tarih.xml", Enabled: true},
	{ID: "ahaber_analiz", Name: "A Haber Analiz", URL: "https://www.ahaber.com.tr/rss/analiz.xml", Enabled: true},
	{ID: "ahaber_saglik", Name: "A Haber Sağlık", URL: "https://www.ahaber.com.tr/rss/saglik.xml", Enabled: true},
	{ID: "cnnturk_all_news", Name: "CNN Türk Tüm Haberler", URL: "https://www.cnnturk.com/feed/rss/all/news", Enabled: true},
	{ID: "cnnturk_turkiye_news", Name: "CNN Türk Türkiye Haberleri", URL: "https://www.cnnturk.com/feed/rss/turkiye/news", Enabled: true},
	{ID: "cnnturk_dunya_news", Name: "CNN Türk Dünya Haberleri", URL: "https://www.cnnturk.com/feed/rss/dunya/news", Enabled: true},
	{ID: "cnnturk_kultursanat_news", Name: "CNN Türk Kültür Sanat Haberleri", URL: "https://www.cnnturk.com/feed/rss/kultur-sanat/news", Enabled: true},
	{ID: "cnnturk_bilim_teknoloji_news", Name: "CNN Türk Bilim Teknoloji Haberleri", URL: "https://www.cnnturk.com/feed/rss/bilim-teknoloji/news", Enabled: true},
	{ID: "cnnturk_yasam_news", Name: "CNN Türk Yaşam Haberleri", URL: "https://www.cnnturk.com/feed/rss/yasam/news", Enabled: true},
	{ID: "cnnturk_magazin_news", Name: "CNN Türk Magazin Haberleri", URL: "https://www.cnnturk.com/feed/rss/magazin/news", Enabled: true},
	{ID: "cnnturk_ekonomi_news", Name: "CNN Türk Ekonomi Haberleri", URL: "https://www.cnnturk.com/feed/rss/ekonomi/news", Enabled: true},
	{ID: "cnnturk_spor_news", Name: "CNN Türk Spor Haberleri", URL: "https://www.cnnturk.com/feed/rss/spor/news", Enabled: true},
	{ID: "cnnturk_saglik_news", Name: "CNN Türk Sağlık Haberleri", URL: "https://www.cnnturk.com/feed/rss/saglik/news", Enabled: true},
	{ID: "cnnturk_otomobil_news", Name: "CNN Türk Otomobil Haberleri", URL: "https://www.cnnturk.com/feed/rss/otomobil/news", Enabled: true},
	{ID: "cnnturk_seyahat_news", Name: "CNN Türk Seyahat Haberleri", URL: "https://www.cnnturk.com/feed/rss/seyahat/news", Enabled: true},
	{ID: "cnnturk_all_video", Name: "CNN Türk Tüm Videolar", URL: "https://www.cnnturk.com/feed/rss/all/video", Enabled: true},
	{ID: "cnnturk_turkiye_video", Name: "CNN Türk Türkiye Videoları", URL: "https://www.cnnturk.com/feed/rss/turkiye/video", Enabled: true},
	{ID: "cnnturk_dunya_video", Name: "CNN Türk Dünya Videoları", URL: "https://www.cnnturk.com/feed/rss/dunya/video", Enabled: true},
	{ID: "cnnturk_kultursanat_video", Name: "CNN Türk Kültür Sanat Videoları", URL: "https://www.cnnturk.com/feed/rss/kultur-sanat/video", Enabled: true},
	{ID: "cnnturk_bilim_teknoloji_video", Name: "CNN Türk Bilim Teknoloji Videoları", URL: "https://www.cnnturk.com/feed/rss/bilim-teknoloji/video", Enabled: true},
	{ID: "cnnturk_yasam_video", Name: "CNN Türk Yaşam Videoları", URL: "https://www.cnnturk.com/feed/rss/yasam/video", Enabled: true},
	{ID: "cnnturk_magazin_video", Name: "CNN Türk Magazin Videoları", URL: "https://www.cnnturk.com/feed/rss/magazin/video", Enabled: true},
	{ID: "cnnturk_ekonomi_video", Name: "CNN Türk Ekonomi Videoları", URL: "https://www.cnnturk.com/feed/rss/ekonomi/video", Enabled: true},
	{ID: "cnnturk_spor_video", Name: "CNN Türk Spor Videoları", URL: "https://www.cnnturk.com/feed/rss/spor/video", Enabled: true},
	{ID: "cnnturk_saglik_video", Name: "CNN Türk Sağlık Videoları", URL: "https://www.cnnturk.com/feed/rss/saglik/video", Enabled: true},
	{ID: "cnnturk_otomobil_video", Name: "CNN Türk Otomobil Videoları", URL: "https://www.cnnturk.com/feed/rss/otomobil/video", Enabled: true},
	{ID: "cnnturk_seyahat_video", Name: "CNN Türk Seyahat Videoları", URL: "https://www.cnnturk.com/feed/rss/seyahat/video", Enabled: true},
	{ID: "cnnturk_all_gallery", Name: "CNN Türk Tüm Galeriler", URL: "https://www.cnnturk.com/feed/rss/all/gallery", Enabled: true},
	{ID: "cnnturk_turkiye_gallery", Name: "CNN Türk Türkiye Galerileri", URL: "https://www.cnnturk.com/feed/rss/turkiye/gallery", Enabled: true},
	{ID: "cnnturk_dunya_gallery", Name: "CNN Türk Dünya Galerileri", URL: "https://www.cnnturk.com/feed/rss/dunya/gallery", Enabled: true},
	{ID: "cnnturk_kultursanat_gallery", Name: "CNN Türk Kültür Sanat Galerileri", URL: "https://www.cnnturk.com/feed/rss/kultur-sanat/gallery", Enabled: true},
	{ID: "cnnturk_bilim_teknoloji_gallery", Name: "CNN Türk Bilim Teknoloji Galerileri", URL: "https://www.cnnturk.com/feed/rss/bilim-teknoloji/gallery", Enabled: true},
	{ID: "cnnturk_yasam_gallery", Name: "CNN Türk Yaşam Galerileri", URL: "https://www.cnnturk.com/feed/rss/yasam/gallery", Enabled: true},
	{ID: "cnnturk_magazin_gallery", Name: "CNN Türk Magazin Galerileri", URL: "https://www.cnnturk.com/feed/rss/magazin/gallery", Enabled: true},
	{ID: "cnnturk_ekonomi_gallery", Name: "CNN Türk Ekonomi Galerileri", URL: "https://www.cnnturk.com/feed/rss/ekonomi/gallery", Enabled: true},
	{ID: "cnnturk_spor_gallery", Name: "CNN Türk Spor Galerileri", URL: "https://www.cnnturk.com/feed/rss/spor/gallery", Enabled: true},
	{ID: "cnnturk_saglik_gallery", Name: "CNN Türk Sağlık Galerileri", URL: "https://www.cnnturk.com/feed/rss/saglik/gallery", Enabled: true},
	{ID: "cnnturk_otomobil_gallery", Name: "CNN Türk Otomobil Galerileri", URL: "https://www.cnnturk.com/feed/rss/otomobil/gallery", Enabled: true},
	{ID: "cnnturk_seyahat_gallery", Name: "CNN Türk Seyahat Galerileri", URL: "https://www.cnnturk.com/feed/rss/seyahat/gallery", Enabled: true},
	{ID: "haberturk", Name: "Habertürk", URL: "http://www.haberturk.com/rss", Enabled: true},
	{ID: "trthaber_sondakika", Name: "TRT Haber Son Dakika", URL: "http://www.trthaber.com/sondakika.rss", Enabled: true},
	{ID: "ulusal", Name: "Ulusal", URL: "http://www.ulusal.com.tr/rss.php", Enabled: true},
	{ID: "acikgazete", Name: "Açık Gazete", URL: "http://www.acikgazete.com/feed/", Enabled: true},
	{ID: "bbc_turkce", Name: "BBC Türkçe", URL: "http://feeds.bbci.co.uk/turkce/rss.xml", Enabled: true},
	{ID: "dw_turkce", Name: "Deutsche Welle Türkçe", URL: "http://rss.dw.com/rdf/rss-tur-all", Enabled: true},
	{ID: "ensonhaber", Name: "En Son Haber", URL: "http://www.ensonhaber.com/rss/ensonhaber.xml", Enabled: true},
	{ID: "mynet_magazin", Name: "Mynet Magazin", URL: "https://www.mynet.com/magazin/rss", Enabled: true},
	{ID: "mynet_sinema_en_yeniler", Name: "Mynet Sinema En Yeniler", URL: "http://sinema.mynet.com/rss/RSS-enyeniler/rss.xml", Enabled: true},
	{ID: "mynet_spor", Name: "Mynet Spor", URL: "http://spor.mynet.com/rss", Enabled: true},
	{ID: "mynet_sondakika", Name: "Mynet Son Dakika", URL: "http://www.mynet.com/haber/rss/sondakika", Enabled: true},
	{ID: "mynet_gunun_ozeti", Name: "Mynet Günün Özeti", URL: "http://www.mynet.com/haber/rss/gununozeti/", Enabled: true},
	{ID: "mynet_politika", Name: "Mynet Politika", URL: "http://www.mynet.com/haber/rss/kategori/politika/", Enabled: true},
	{ID: "mynet_teknoloji", Name: "Mynet Teknoloji", URL: "http://www.mynet.com/haber/rss/kategori/teknoloji/", Enabled: true},
	{ID: "mynet_dunya", Name: "Mynet Dünya", URL: "http://www.mynet.com/haber/rss/kategori/dunya/", Enabled: true},
	{ID: "mynet_yasam", Name: "Mynet Yaşam", URL: "http://www.mynet.com/haber/rss/kategori/yasam/", Enabled: true},
	{ID: "mynet_magazin_kategori", Name: "Mynet Magazin Kategori", URL: "http://www.mynet.com/haber/rss/kategori/magazin/", Enabled: true},
	{ID: "mynet_saglik", Name: "Mynet Sağlık", URL: "http://www.mynet.com/haber/rss/kategori/saglik/", Enabled: true},
	{ID: "sputnik_turkce", Name: "Sputnik Türkçe", URL: "https://tr.sputniknews.com/export/rss2/archive/index.xml", Enabled: true},
	{ID: "turkiyehaberajansi", Name: "Türkiye Haber Ajansı", URL: "http://www.turkiyehaberajansi.com/rss.xml", Enabled: true},
	{ID: "internethaber", Name: "İnternet Haber", URL: "http://www.internethaber.com/rss", Enabled: true},
	{ID: "finasgundem", Name: "Finans Gündem", URL: "http://www.finansgundem.com/rss", Enabled: true},
	{ID: "tobb_haberler", Name: "TOBB Haberler", URL: "https://www.tobb.org.tr/Sayfalar/RssFeeder.php?List=Haberler", Enabled: true},
	{ID: "tobb_duyurular", Name: "TOBB Duyurular", URL: "https://www.tobb.org.tr/Sayfalar/RssFeeder.php?List=DuyurularListesi", Enabled: true},
	{ID: "tobb_manset", Name: "TOBB Manşet", URL: "https://www.tobb.org.tr/Sayfalar/RssFeeder.php?List=MansetListesi", Enabled: true},
	{ID: "bigpara", Name: "Big Para", URL: "http://bigpara.hurriyet.com.tr/rss/", Enabled: true},
	{ID: "teknoseyir", Name: "teknoseyir", URL: "https://teknoseyir.com/feed", Enabled: true},

	{ID: "beetekno", Name: "Beetekno", URL: "https://www.beetekno.com/feed/posts", Enabled: true},
	{ID: "campaign_turkiye", Name: "Campaign Türkiye", URL: "https://www.campaigntr.com/feed/", Enabled: true},
	{ID: "chip_online", Name: "CHIP Online", URL: "https://www.chip.com.tr/rss", Enabled: true},
	{ID: "cozumpark", Name: "ÇözümPark", URL: "https://www.cozumpark.com/feed/", Enabled: true},
	{ID: "dijitaliyidir", Name: "Dijitaliyidir", URL: "https://dijitaliyidir.com/feed/", Enabled: true},
	{ID: "donanim_haber", Name: "Donanım Haber", URL: "https://www.donanimhaber.com/rss/tum/", Enabled: true},
	{ID: "donanim_gunlugu", Name: "Donanım Günlüğü", URL: "https://donanimgunlugu.com/feed", Enabled: true},
	{ID: "foundern", Name: "FounderN", URL: "https://foundern.com/feed/", Enabled: true},
	{ID: "hardware_plus", Name: "Hardware Plus", URL: "https://hwp.com.tr/feed", Enabled: true},
	{ID: "investing_teknoloji", Name: "Investing Teknoloji", URL: "https://tr.investing.com/rss/news_288.rss", Enabled: true},
	{ID: "indir", Name: "İndir", URL: "https://www.indir.com/haber/feed/", Enabled: true},
	{ID: "log", Name: "LOG", URL: "https://www.log.com.tr/feed/", Enabled: true},
	{ID: "megabayt", Name: "Megabayt", URL: "https://www.megabayt.com/rss/news", Enabled: true},
	{ID: "megabayt_bilgisayar", Name: "Megabayt Bilgisayar", URL: "https://www.megabayt.com/rss/categorynews/bilgisayar", Enabled: true},
	{ID: "megabayt_bilim_teknoloji", Name: "Megabayt Bilim ve Teknoloji", URL: "https://www.megabayt.com/rss/categorynews/bilim-ve-teknoloji", Enabled: true},
	{ID: "megabayt_donanim", Name: "Megabayt Donanım", URL: "https://www.megabayt.com/rss/categorynews/donanim", Enabled: true},
	{ID: "megabayt_nasil_yapilir", Name: "Megabayt Nasıl Yapılır?", URL: "https://www.megabayt.com/rss/categorynews/nasil-yapilir", Enabled: true},
	{ID: "megabayt_siber_guvenlik", Name: "Megabayt Siber Güvenlik", URL: "https://www.megabayt.com/rss/categorynews/siber-guvenlik", Enabled: true},
	{ID: "megabayt_sosyal_medya", Name: "Megabayt Sosyal Medya", URL: "https://www.megabayt.com/rss/categorynews/sosyal-medya", Enabled: true},
	{ID: "megabayt_teknoloji", Name: "Megabayt Teknoloji", URL: "https://www.megabayt.com/rss/categorynews/teknoloji", Enabled: true},
	{ID: "megabayt_yazilim", Name: "Megabayt Yazılım", URL: "https://www.megabayt.com/rss/categorynews/yazilim", Enabled: true},
	{ID: "pc_hocasi", Name: "PC Hocası", URL: "https://pchocasi.com.tr/feed", Enabled: true},
	{ID: "sordum", Name: "Sordum", URL: "https://www.sordum.net/feed/", Enabled: true},
	{ID: "swipeline", Name: "Swipeline", URL: "https://swipeline.co/feed/", Enabled: true},
	{ID: "techolay", Name: "Techolay", URL: "https://techolay.net/feed/", Enabled: true},
	{ID: "technopat", Name: "Technopat", URL: "https://www.technopat.net/feed/", Enabled: true},
	{ID: "teknoblog", Name: "Teknoblog", URL: "https://www.teknoblog.com/feed/", Enabled: true},
	{ID: "teknolojioku", Name: "Teknolojioku", URL: "https://www.teknolojioku.com/export/rss", Enabled: true},
	{ID: "teknoburada", Name: "TeknoBurada", URL: "https://www.teknoburada.net/feed/", Enabled: true},
	{ID: "tam_indir", Name: "Tam İndir", URL: "https://feeds.feedburner.com/tamindir/stream", Enabled: true},
	{ID: "voicetekno", Name: "VoiceTekno", URL: "https://voicetekno.com/feed/", Enabled: true},
	{ID: "webmasto", Name: "Webmasto", URL: "https://webmasto.com/feed", Enabled: true},
	{ID: "webrazzi", Name: "Webrazzi", URL: "https://webrazzi.com/feed", Enabled: true},
	{ID: "webtekno", Name: "Webtekno", URL: "https://www.webtekno.com/rss.xml", Enabled: true},
	{ID: "22dakika", Name: "22 Dakika", URL: "https://22dakika.org/feed/", Enabled: true},
	{ID: "atarita", Name: "Atarita", URL: "https://www.atarita.com/feed/", Enabled: true},
	{ID: "altyazi", Name: "Altyazı", URL: "https://altyazi.net/feed/", Enabled: true},
	{ID: "bagimsiz_sinema", Name: "Bağımsız Sinema", URL: "https://www.bagimsizsinema.com/feed", Enabled: true},
	{ID: "beyaz_perde", Name: "Beyaz Perde", URL: "https://www.beyazperde.com/rss/haberler.xml", Enabled: true},
	{ID: "bigumigu", Name: "Bigumigu", URL: "https://bigumigu.com/feed/", Enabled: true},
	{ID: "bilimkurgu_kulubu", Name: "Bilimkurgu Kulübü", URL: "https://www.bilimkurgukulubu.com/feed/", Enabled: true},
	{ID: "fantastik_canavarlar", Name: "Fantastik Canavarlar", URL: "https://fantastikcanavarlar.com/feed/", Enabled: true},
	{ID: "frpnet", Name: "FRPNET", URL: "https://frpnet.net/feed", Enabled: true},
	{ID: "geekyapar", Name: "Geekyapar", URL: "https://geekyapar.com/feed/", Enabled: true},
	{ID: "ign_turkiye", Name: "IGN Türkiye", URL: "https://tr.ign.com/feed.xml", Enabled: true},
	{ID: "kayip_rihtim", Name: "Kayıp Rıhtım", URL: "https://kayiprihtim.com/feed/", Enabled: true},
	{ID: "kesif_asya", Name: "Keşif Asya", URL: "https://kesifasya.com/feed/", Enabled: true},
	{ID: "listelist", Name: "ListeList", URL: "https://listelist.com/feed/", Enabled: true},
	{ID: "marjinal_sinema", Name: "Marjinal Sinema", URL: "https://marjinalsinema.com/feed/", Enabled: true},
	{ID: "merlinin_kazani", Name: "Merlin'in Kazanı", URL: "https://www.merlininkazani.com/feed/", Enabled: true},
	{ID: "megabayt_dijital_platformlar", Name: "Megabayt Dijital Platformlar", URL: "https://www.megabayt.com/rss/categorynews/dijital-platformlar", Enabled: true},
	{ID: "megabayt_dizi_sinema", Name: "Megabayt Dizi-sinema", URL: "https://www.megabayt.com/rss/categorynews/dizi-sinema", Enabled: true},
	{ID: "megabayt_oyun", Name: "Megabayt Oyun", URL: "https://www.megabayt.com/rss/categorynews/oyun", Enabled: true},
	{ID: "megabayt_sinema", Name: "Megabayt Sinema", URL: "https://www.megabayt.com/rss/categorynews/sinema", Enabled: true},
	{ID: "megabayt_televizyon", Name: "Megabayt Televizyon", URL: "https://www.megabayt.com/rss/categorynews/televizyon", Enabled: true},
	{ID: "megabayt_youtube", Name: "Megabayt Youtube", URL: "https://www.megabayt.com/rss/categorynews/youtube", Enabled: true},
	{ID: "mister_noob", Name: "Mister Noob", URL: "https://www.misternoob.com/feed/", Enabled: true},
	{ID: "mobidictum", Name: "Mobidictum", URL: "https://mobidictum.com/tr/feed/", Enabled: true},
	{ID: "onedio", Name: "Onedio", URL: "https://onedio.com/Publisher/publisher-daily.rss", Enabled: true},
	{ID: "oteki_sinema", Name: "Öteki Sinema", URL: "https://www.otekisinema.com/feed/", Enabled: true},
	{ID: "sofos", Name: "Sofos", URL: "https://blog.sofos.com.tr/feed/", Enabled: true},
	{ID: "sinetopya", Name: "Sinetopya", URL: "https://sinetopya.com/rss/", Enabled: true},
	{ID: "the_geyik", Name: "The Geyik", URL: "https://www.thegeyik.com/feed/", Enabled: true},
	{ID: "turkmmo", Name: "Turkmmo", URL: "https://www.turkmmo.com/feed", Enabled: true},
	{ID: "turuncu_levye", Name: "Turuncu Levye", URL: "https://www.turunculevye.com/feed/", Enabled: true},
	{ID: "c4defence", Name: "4 Defence", URL: "https://www.c4defence.com/tr/feed/", Enabled: true},
	{ID: "defenceturk", Name: "DefenceTurk", URL: "https://www.defenceturk.net/feed", Enabled: true},
	{ID: "mavi_savunma", Name: "Mavi Savunma", URL: "https://mavisavunma.com/feed/", Enabled: true},
	{ID: "sanayi_gazetesi", Name: "Sanayi Gazetesi", URL: "https://sanayigazetesi.com.tr/kategori/savunma-haberleri/feed/", Enabled: true},
	{ID: "savunma_sanayi_gazetesi", Name: "Savunma Sanayi Gazetesi", URL: "https://savunmasanayigazetesi.com.tr/feed/", Enabled: true},
	{ID: "savunmasanayist", Name: "SavunmaSanayiST", URL: "https://www.savunmasanayist.com/feed/", Enabled: true},
	{ID: "savunmatr", Name: "SavunmaTR", URL: "https://www.savunmatr.com/feed/", Enabled: true},

	{ID: "pinknews", Name: "PinkNews", URL: "https://www.pinknews.co.uk/feed/", Enabled: true},
	{ID: "scenemag", Name: "SceneMag", URL: "https://www.scenemag.co.uk/rss/", Enabled: true},
	{ID: "hrw", Name: "hrw", URL: "https://www.hrw.org/rss/news", Enabled: true},
	{ID: "gayety", Name: "gayety", URL: "https://gayety.com/feed", Enabled: true},
	{ID: "queerguru", Name: "queerguru", URL: "https://queerguru.com/feed/", Enabled: true},
	{ID: "advocate", Name: "advocate", URL: "https://www.advocate.com/customfeeds/js/feed/rss", Enabled: true},
	{ID: "glaad", Name: "glaad", URL: "https://glaad.org/feed/", Enabled: true},
	{ID: "metroweekly", Name: "metroweekly", URL: "https://www.metroweekly.com/feed/", Enabled: true},
	{ID: "equallywed", Name: "equallywed", URL: "https://equallywed.com/feed/", Enabled: true},
	{ID: "sageusa", Name: "sageusa", URL: "https://www.sageusa.org/feed/", Enabled: true},
	{ID: "lesbian", Name: "lesbian", URL: "https://www.lesbian.com/feed/", Enabled: true},
	{ID: "therandyreport", Name: "therandyreport", URL: "https://therandyreport.com/feed/", Enabled: true},
	{ID: "lgbtqandall", Name: "lgbtqandall", URL: "https://www.lgbtqandall.com/feed/", Enabled: true},
	{ID: "meaws", Name: "meaws", URL: "https://meaws.com/rss", Enabled: true},
	{ID: "lgbtlifecenter", Name: "lgbtlifecenter", URL: "https://lgbtlifecenter.org/feed/", Enabled: true},
	{ID: "thepridela", Name: "thepridela", URL: "https://thepridela.com/feed/", Enabled: true},
	{ID: "main-stream", Name: "main-stream", URL: "https://main-stream.org/feed/", Enabled: true},
	{ID: "pghlesbian", Name: "pghlesbian", URL: "https://www.pghlesbian.com/feed/", Enabled: true},
	{ID: "lavendermagazine", Name: "lavendermagazine", URL: "https://lavendermagazine.com/feed/", Enabled: true},
	{ID: "gayinthecle", Name: "gayinthecle", URL: "https://gayinthecle.com/feed/", Enabled: true},
	{ID: "bicommunitynews", Name: "bicommunitynews", URL: "https://bicommunitynews.co.uk/feed/", Enabled: true},
	{ID: "gaycitynews", Name: "gaycitynews", URL: "https://gaycitynews.com/feed/", Enabled: true},
	{ID: "antonysimpson", Name: "antonysimpson", URL: "https://antonysimpson.com/feed/", Enabled: true},
	{ID: "queerlittlefamily", Name: "queerlittlefamily", URL: "https://queerlittlefamily.co.uk/feed/", Enabled: true},
	{ID: "bearworldmag", Name: "bearworldmag", URL: "https://bearworldmag.com/feed/", Enabled: true},
	{ID: "blgbt", Name: "blgbt", URL: "https://blgbt.org/feed/", Enabled: true},
	{ID: "ruelon", Name: "ruelon", URL: "https://ruelon.com/feed/", Enabled: true},
	{ID: "terrybaum", Name: "terrybaum", URL: "https://terrybaum.blogspot.com/feeds/posts/default?alt=rss", Enabled: true},
	{ID: "thomascwaters", Name: "thomascwaters", URL: "https://thomascwaters.com/feed/", Enabled: true},
	{ID: "aspiraldance", Name: "aspiraldance", URL: "https://www.aspiraldance.com/feed/", Enabled: true},
	{ID: "queeradventurers", Name: "queeradventurers", URL: "https://queeradventurers.com/feed/", Enabled: true},
	{ID: "itgetsbetter", Name: "itgetsbetter", URL: "https://itgetsbetter.org/feed/", Enabled: true},
	{ID: "lgbtmap", Name: "lgbtmap", URL: "https://medium.com/feed/@lgbtmap", Enabled: true},
	{ID: "lgbthealth", Name: "lgbthealth", URL: "https://www.lgbthealth.org.uk/feed/", Enabled: true},
	{ID: "letsqueerthingsup", Name: "letsqueerthingsup", URL: "https://letsqueerthingsup.com/feed/", Enabled: true},
	{ID: "lgbtie", Name: "lgbtie", URL: "https://lgbt.ie/feed/", Enabled: true},
	{ID: "lgbttech", Name: "lgbttech", URL: "https://www.lgbttech.org/blog-feed.xml", Enabled: true},
	{ID: "queerty", Name: "queerty", URL: "https://www.queerty.com/feed/", Enabled: true},
	{ID: "lgbt.foundation", Name: "lgbt.foundation", URL: "https://lgbt.foundation/feed/", Enabled: true},
	{ID: "lesbianearth", Name: "lesbianearth", URL: "https://lesbianearth.com/feed/", Enabled: true},
	{ID: "glreview", Name: "glreview", URL: "https://glreview.org/feed/", Enabled: true},
	{ID: "rainbowandco", Name: "rainbowandco", URL: "https://rainbowandco.uk/blogs/what-were-saying.atom", Enabled: true},
	{ID: "michaelandmatt", Name: "michaelandmatt", URL: "https://www.michaelandmatt.com/blog?format=rss", Enabled: true},
	{ID: "gaythrive", Name: "gaythrive", URL: "https://gaythrive.com/blog/feed/", Enabled: true},
	{ID: "misterbandb", Name: "misterbandb", URL: "https://www.misterbandb.com/gay-blog/feed", Enabled: true},
	{ID: "gaytravelinformation", Name: "gaytravelinformation", URL: "https://gaytravelinformation.com/feed/", Enabled: true},
	{ID: "coupleofmen", Name: "coupleofmen", URL: "https://coupleofmen.com/feed/", Enabled: true},
	{ID: "gay.blog", Name: "gay.blog", URL: "https://gay.blog.br/en/feed/", Enabled: true},
	{ID: "biresource", Name: "biresource", URL: "https://biresource.org/feed/", Enabled: true},
	{ID: "bimedia", Name: "bimedia", URL: "https://bimedia.org/blogs/feed/", Enabled: true},
	{ID: "cool2btrans", Name: "cool2btrans", URL: "https://cool2btrans.co.uk/feed/", Enabled: true},
	{ID: "trans-survivors", Name: "trans-survivors", URL: "https://trans-survivors.com/feed/", Enabled: true},
	{ID: "stephaniebattaglino", Name: "stephaniebattaglino", URL: "https://stephaniebattaglino.com/feed/", Enabled: true},
	{ID: "gendergp", Name: "gendergp", URL: "https://www.gendergp.com/feed/", Enabled: true},
	{ID: "ragemonthly", Name: "ragemonthly", URL: "https://ragemonthly.com/feed/", Enabled: true},
	{ID: "instinctmagazine", Name: "instinctmagazine", URL: "https://instinctmagazine.com/feed/", Enabled: true},
	{ID: "spod", Name: "SpoD", URL: "https://spod.org.tr/feed/", Enabled: true},
	{ID: "lgbtqnation", Name: "LGBTQ Nation", URL: "https://www.lgbtqnation.com/feed/", Enabled: true},
	{ID: "guardian-lgbt", Name: "The Guardian - LGBT rights", URL: "https://www.theguardian.com/world/lgbt-rights/rss", Enabled: true},
	{ID: "out-mag", Name: "OUT (尝试)", URL: "https://www.out.com/rss.xml", Enabled: true},
	{ID: "gcn.ie", Name: "gcn.ie", URL: "https://gcn.ie/feed/", Enabled: true},

	{ID: "lgbtqreads", Name: "lgbtqreads", URL: "https://lgbtqreads.com/feed/", Enabled: true},
	{ID: "opentable", Name: "opentable", URL: "https://opentable.lgbt/our-blog?format=rss", Enabled: true},
	{ID: "pride", Name: "pride", URL: "https://www.pride.com/feeds/feed.rss", Enabled: true},
	{ID: "pridepalace", Name: "pridepalace", URL: "https://pridepalace.lgbt/blogs/news.atom", Enabled: true},
	{ID: "gaydesertguide", Name: "gaydesertguide", URL: "https://gaydesertguide.com/feed/", Enabled: true},
	{ID: "naglrep", Name: "naglrep", URL: "https://naglrep.com/feed/", Enabled: true},
	{ID: "mombian", Name: "mombian", URL: "https://mombian.com/feed/", Enabled: true},
	{ID: "lgbtqfresno", Name: "lgbtqfresno", URL: "https://www.lgbtqfresno.com/feed/", Enabled: true},
	{ID: "outsmartmagazine", Name: "outsmartmagazine", URL: "https://www.outsmartmagazine.com/feed/", Enabled: true},
	{ID: "haber", Name: "haber", URL: "https://www.haber.com/rss", Enabled: true},

	{ID: "arabnews", Name: "arabnews", URL: "https://www.arabnews.com/rss.xml", Enabled: true},
	{ID: "arabnews", Name: "arabnews", URL: "https://www.arabnews.com/cat/1/rss.xml", Enabled: true},
	{ID: "arabnews", Name: "arabnews", URL: "https://www.arabnews.com/cat/2/rss.xml", Enabled: true},
	{ID: "arabnews", Name: "arabnews", URL: "https://www.arabnews.com/cat/3/rss.xml", Enabled: true},
	{ID: "arabnews", Name: "arabnews", URL: "https://www.arabnews.com/cat/4/rss.xml", Enabled: true},
	{ID: "arabnews", Name: "arabnews", URL: "https://www.arabnews.com/cat/5/rss.xml", Enabled: true},
	{ID: "arabnews", Name: "arabnews", URL: "https://www.arabnews.com/cat/8/rss.xml", Enabled: true},

	{ID: "nikkei", Name: "nikkei", URL: "https://asia.nikkei.com/rss/feed/nar", Enabled: true},
	{ID: "japantimes", Name: "japantimes", URL: "https://www.japantimes.co.jp/feed/", Enabled: true},
	{ID: "japantoday", Name: "japantoday", URL: "https://japantoday.com/feed", Enabled: true},
	{ID: "mainichi", Name: "mainichi", URL: "https://mainichi.jp/rss/etc/english_latest.rss", Enabled: true},

	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Africa.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Americas.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/AsiaPacific.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Europe.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/US.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Education.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Upshot.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/NYRegion.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/EnergyEnvironment.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/SmallBusiness.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Dealbook.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/MediaandAdvertising.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/YourMoney.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/PersonalTech.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Baseball.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/CollegeBasketball.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/CollegeFootball.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Golf.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Hockey.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/ProBasketball.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/ProFootball.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Soccer.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Space.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Well.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Weather.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/ArtandDesign.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Books/Review.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Dance.xml", Enabled: true},

	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Movies.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Music.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Television.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Weddings.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/tmagazine.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Jobs.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/RealEstate.xml", Enabled: true},
	{ID: "nytimes", Name: "nytimes", URL: "https://rss.nytimes.com/services/xml/rss/nyt/Automobiles.xml", Enabled: true},

	{ID: "aljazeera", Name: "aljazeera", URL: "https://www.aljazeera.com/xml/rss/all.xml", Enabled: true},
}

func GenerateGoogleNewsRSSURL(lang Language) string {
	baseURL := "https://news.google.com/rss/search"
	query := "(" + strings.Join(lang.SearchKeywords, " OR ") + ") when:7d"
	encodedQuery := url.QueryEscape(query)

	return fmt.Sprintf("%s?q=%s&hl=%s&gl=%s&ceid=%s", baseURL, encodedQuery, lang.HL, lang.GL, lang.CEID)
}

func GenerateBingNewsRSSURL(lang Language) string {
	baseURL := "https://www.bing.com/news/search"

	// Her arama kelimesini feed:"kelime" olarak yap, sonra OR ile bağla
	quotedTerms := make([]string, len(lang.SearchKeywords))
	for i, w := range lang.SearchKeywords {
		quotedTerms[i] = fmt.Sprintf("feed:%q", w) // örn: feed:"gay"
	}

	query := strings.Join(quotedTerms, " OR ")
	encoded := url.QueryEscape(query)

	return fmt.Sprintf("%s?q=%s&format=rss&setlang=%s&mkt=%s", baseURL, encoded, lang.HL, lang.HL)

}

func GenerateAllRSSSources() []RSSSource {
	var rssSources []RSSSource

	// Önce statik kaynakları ekle
	rssSources = append(rssSources, StaticRSSSources...)

	return rssSources
	// Sonra dillerin Google News kaynaklarını ekle
	for _, lang := range Languages {
		rssSources = append(rssSources, RSSSource{
			ID:      "gnews-" + lang.Code + "-" + strings.ToLower(lang.CountryCode),
			Name:    fmt.Sprintf("Google News (%s, %s)", lang.CountryCode, lang.Code),
			URL:     GenerateGoogleNewsRSSURL(lang),
			Enabled: true,
		})
	}

	for _, lang := range Languages {
		rssSources = append(rssSources, RSSSource{
			ID:      "bingnews-" + lang.Code + "-" + strings.ToLower(lang.CountryCode),
			Name:    fmt.Sprintf("Bing News (%s, %s)", lang.CountryCode, lang.Code),
			URL:     GenerateBingNewsRSSURL(lang),
			Enabled: false,
		})
	}

	return rssSources
}

var DefaultRSSSources = GenerateAllRSSSources()
