package reportkinds

import (
	report "coolvibes/models"
	"coolvibes/models/utils"

	"gorm.io/gorm"
)

func SeedReportKinds(db *gorm.DB) error {
	kinds := []report.ReportKind{
		{
			Key:          report.ReportKindSpam,
			DisplayOrder: 1,
			Name: utils.LocalizedString{
				"en": "Spam", "tr": "Spam", "es": "Spam", "he": "ספאם", "ar": "رسائل غير مرغوب فيها",
				"zh": "垃圾信息", "ja": "スパム", "hi": "स्पैम", "de": "Spam", "th": "สแปม",
				"ru": "Спам", "pl": "Spam", "fr": "Spam", "pt": "Spam", "id": "Spam", "bn": "স্প্যাম",
			},
			Description: utils.LocalizedString{
				"en": "Unwanted repetitive or automated content.",
				"tr": "Gereksiz, tekrarlayan veya otomatik içerikler.",
				"es": "Contenido no deseado o repetitivo.",
				"he": "תוכן חוזר או לא רצוי.",
				"ar": "محتوى متكرر أو غير مرغوب فيه.",
				"zh": "不需要的重复或自动内容。",
				"ja": "不要な繰り返しまたは自動化されたコンテンツ。",
				"hi": "अनचाहा दोहराव या स्वचालित सामग्री।",
				"de": "Unerwünschte wiederholte oder automatisierte Inhalte.",
				"th": "เนื้อหาที่ไม่ต้องการหรือซ้ำซาก",
				"ru": "Нежелательный повторяющийся или автоматизированный контент.",
				"pl": "Niechciana, powtarzalna lub automatyczna treść.",
				"fr": "Contenu non désiré ou répétitif.",
				"pt": "Conteúdo indesejado ou repetitivo.",
				"id": "Konten yang tidak diinginkan atau berulang.",
				"bn": "অপ্রয়োজনীয় বা স্বয়ংক্রিয় পুনরাবৃত্ত বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindHateSpeech,
			DisplayOrder: 2,
			Name: utils.LocalizedString{
				"en": "Hate Speech", "tr": "Nefret Söylemi", "es": "Discurso de odio", "he": "דיבור שנאה", "ar": "خطاب الكراهية",
				"zh": "仇恨言论", "ja": "ヘイトスピーチ", "hi": "घृणा भाषण", "de": "Hassrede", "th": "คำพูดที่เกลียดชัง",
				"ru": "Речь ненависти", "pl": "Mowa nienawiści", "fr": "Discours haineux", "pt": "Discurso de ódio", "id": "Ujaran kebencian", "bn": "ঘৃণা বক্তৃতা",
			},
			Description: utils.LocalizedString{
				"en": "Content promoting hatred against individuals or groups.",
				"tr": "Bireylere veya gruplara karşı nefret içeren içerikler.",
				"es": "Contenido que promueve el odio contra individuos o grupos.",
				"he": "תוכן שמעודד שנאה כלפי יחידים או קבוצות.",
				"ar": "محتوى يروج للكراهية ضد أفراد أو مجموعات.",
				"zh": "针对个人或群体的仇恨内容。",
				"ja": "個人やグループに対する憎悪を助長するコンテンツ。",
				"hi": "व्यक्तियों या समूहों के खिलाफ नफ़रत फैलाने वाली सामग्री।",
				"de": "Inhalte, die Hass gegen Einzelpersonen oder Gruppen fördern.",
				"th": "เนื้อหาที่ส่งเสริมความเกลียดชังต่อบุคคลหรือกลุ่ม.",
				"ru": "Контент, пропагандирующий ненависть к отдельным лицам или группам.",
				"pl": "Treści promujące nienawiść wobec osób lub grup.",
				"fr": "Contenu promouvant la haine envers des individus ou des groupes.",
				"pt": "Conteúdo que promove ódio contra indivíduos ou grupos.",
				"id": "Konten yang mempromosikan kebencian terhadap individu atau kelompok.",
				"bn": "ব্যক্তি বা গোষ্ঠীর বিরুদ্ধে ঘৃণা প্রচার করে এমন বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindNudity,
			DisplayOrder: 3,
			Name: utils.LocalizedString{
				"en": "Nudity", "tr": "Çıplaklık", "es": "Desnudez", "he": "עירום", "ar": "عري",
				"zh": "裸体", "ja": "ヌード", "hi": "नग्नता", "de": "Nacktheit", "th": "เปลือย",
				"ru": "Нагота", "pl": "Nagość", "fr": "Nudité", "pt": "Nudez", "id": "Ketelanjangan", "bn": "অশ্লীলতা",
			},
			Description: utils.LocalizedString{
				"en": "Sexual or explicit nudity.",
				"tr": "Cinsel veya müstehcen çıplaklık.",
				"es": "Desnudez sexual o explícita.",
				"he": "עירום מיני או מפורש.",
				"ar": "عري جنسي أو صريح.",
				"zh": "性或露骨的裸体。",
				"ja": "性的または露骨なヌード。",
				"hi": "यौन या स्पष्ट नग्नता।",
				"de": "Sexuelle oder explizite Nacktheit.",
				"th": "การเปลือยทางเพศหรือชัดเจน.",
				"ru": "Сексуальная или явная нагота.",
				"pl": "Nagość seksualna lub explicite.",
				"fr": "Nudité sexuelle ou explicite.",
				"pt": "Nudez sexual ou explícita.",
				"id": "Ketelanjangan seksual atau eksplisit.",
				"bn": "যৌন বা স্পষ্ট নগ্নতা।",
			},
		},
		{
			Key:          report.ReportKindViolenceThreat,
			DisplayOrder: 4,
			Name: utils.LocalizedString{
				"en": "Violence / Threat", "tr": "Şiddet / Tehdit", "es": "Violencia / Amenaza", "he": "אלימות / איום", "ar": "العنف / التهديد",
				"zh": "暴力 / 威胁", "ja": "暴力 / 脅威", "hi": "हिंसा / धमकी", "de": "Gewalt / Bedrohung", "th": "ความรุนแรง / การข่มขู่",
				"ru": "Насилие / Угроза", "pl": "Przemoc / Zagrożenie", "fr": "Violence / Menace", "pt": "Violência / Ameaça", "id": "Kekerasan / Ancaman", "bn": "হিংসা / হুমকি",
			},
			Description: utils.LocalizedString{
				"en": "Threats or encouragement of physical harm.",
				"tr": "Fiziksel zarar tehdidi veya teşviki.",
				"es": "Amenazas o fomento de daño físico.",
				"he": "איומים או עידוד לפגיעה פיזית.",
				"ar": "تهديدات أو تشجيع على الأذى الجسدي.",
				"zh": "威胁或鼓励身体伤害。",
				"ja": "身体的な危害の脅迫または奨励。",
				"hi": "शारीरिक नुकसान की धमकी या प्रोत्साहन।",
				"de": "Androhung oder Förderung körperlicher Schäden.",
				"th": "การข่มขู่หรือสนับสนุนความรุนแรงทางร่างกาย.",
				"ru": "Угрозы или поощрение физического вреда.",
				"pl": "Groźby lub zachęcanie do krzywdy fizycznej.",
				"fr": "Menaces ou encouragements à des dommages physiques.",
				"pt": "Ameaças ou incentivo a danos físicos.",
				"id": "Ancaman atau dorongan untuk melakukan kerusakan fisik.",
				"bn": "শারীরিক ক্ষতির হুমকি বা উৎসাহ।",
			},
		},
		{
			Key:          report.ReportKindFraud,
			DisplayOrder: 5,
			Name: utils.LocalizedString{
				"en": "Fraud", "tr": "Dolandırıcılık", "es": "Fraude", "he": "רמאות", "ar": "احتيال",
				"zh": "欺诈", "ja": "詐欺", "hi": "धोखा", "de": "Betrug", "th": "ฉ้อโกง",
				"ru": "Мошенничество", "pl": "Oszustwo", "fr": "Fraude", "pt": "Fraude", "id": "Penipuan", "bn": "প্রতারণা",
			},
			Description: utils.LocalizedString{
				"en": "Scams, deception or financial fraud.",
				"tr": "Aldatma, dolandırıcılık veya finansal hile.",
				"es": "Estafas, engaños o fraudes financieros.",
				"he": "הונאות, תרמיות או הונאה פיננסית.",
				"ar": "عمليات احتيال أو خداع أو تزوير مالي.",
				"zh": "诈骗、欺骗或金融欺诈。",
				"ja": "詐欺、欺瞞、または金融詐欺。",
				"hi": "धोखाधड़ी, छल या वित्तीय धोखाधड़ी।",
				"de": "Betrügereien, Täuschung oder finanzieller Betrug.",
				"th": "การหลอกลวง การโกง หรือการฉ้อโกงทางการเงิน.",
				"ru": "Мошенничество, обман или финансовое мошенничество.",
				"pl": "Oszustwa, oszustwa finansowe lub oszustwa.",
				"fr": "Arnaques, tromperies ou fraudes financières.",
				"pt": "Golpes, enganos ou fraudes financeiras.",
				"id": "Penipuan, tipu daya, atau kecurangan finansial.",
				"bn": "প্রতারণা, ছল বা আর্থিক প্রতারণা।",
			},
		},
		{
			Key:          report.ReportKindHarassment,
			DisplayOrder: 6,
			Name: utils.LocalizedString{
				"en": "Harassment", "tr": "Taciz", "es": "Acoso", "he": "הטרדה", "ar": "مضايقة",
				"zh": "骚扰", "ja": "嫌がらせ", "hi": "उत्पीड़न", "de": "Belästigung", "th": "การคุกคาม",
				"ru": "Домогательства", "pl": "Nękanie", "fr": "Harcèlement", "pt": "Assédio", "id": "Pelecehan", "bn": "উত্যক্ত করা",
			},
			Description: utils.LocalizedString{
				"en": "Offensive or targeted harassment.",
				"tr": "Hedef gösteren veya rahatsız edici taciz.",
				"es": "Acoso ofensivo o dirigido.",
				"he": "הטרדה פוגענית או ממוקדת.",
				"ar": "مضايقة هجومية أو مستهدفة.",
				"zh": "冒犯性或针对性的骚扰。",
				"ja": "攻撃的またはターゲットにされた嫌がらせ。",
				"hi": "अपमानजनक या लक्षित उत्पीड़न।",
				"de": "Beleidigende oder gezielte Belästigung.",
				"th": "การคุกคามที่เป็นการโจมตีหรือมุ่งเป้า.",
				"ru": "Оскорбительные или целенаправленные домогательства.",
				"pl": "Obraźliwe lub celowane nękanie.",
				"fr": "Harcèlement offensant ou ciblé.",
				"pt": "Assédio ofensivo ou direcionado.",
				"id": "Pelecehan yang menyerang atau ditargetkan.",
				"bn": "আপত্তিকর বা লক্ষ্যভিত্তিক হয়রানি।",
			},
		},
		{
			Key:          report.ReportKindPersonalInfo,
			DisplayOrder: 7,
			Name: utils.LocalizedString{
				"en": "Personal Info", "tr": "Kişisel Bilgi", "es": "Información personal", "he": "מידע אישי", "ar": "معلومات شخصية",
				"zh": "个人信息", "ja": "個人情報", "hi": "व्यक्तिगत जानकारी", "de": "Persönliche Informationen", "th": "ข้อมูลส่วนบุคคล",
				"ru": "Личная информация", "pl": "Informacje osobiste", "fr": "Informations personnelles", "pt": "Informações pessoais", "id": "Informasi pribadi", "bn": "ব্যক্তিগত তথ্য",
			},
			Description: utils.LocalizedString{
				"en": "Sharing of private or sensitive information.",
				"tr": "Özel veya hassas bilgilerin paylaşılması.",
				"es": "Compartir información privada o sensible.",
				"he": "שיתוף מידע פרטי או רגיש.",
				"ar": "مشاركة معلومات خاصة أو حساسة.",
				"zh": "分享私人或敏感信息。",
				"ja": "個人情報の共有。",
				"hi": "निजी या संवेदनशील जानकारी साझा करना।",
				"de": "Weitergabe von privaten oder sensiblen Informationen.",
				"th": "การแบ่งปันข้อมูลส่วนตัวหรือข้อมูลที่ละเอียดอ่อน",
				"ru": "Распространение личной или конфиденциальной информации.",
				"pl": "Udostępnianie prywatnych lub wrażliwych informacji.",
				"fr": "Partage d'informations privées ou sensibles.",
				"pt": "Compartilhamento de informações privadas ou sensíveis.",
				"id": "Berbagi informasi pribadi atau sensitif.",
				"bn": "ব্যক্তিগত বা সংবেদনশীল তথ্য শেয়ার করা।",
			},
		},
		{
			Key:          report.ReportKindFalseInfo,
			DisplayOrder: 8,
			Name: utils.LocalizedString{
				"en": "False Info", "tr": "Yanlış Bilgi", "es": "Información falsa", "he": "מידע שגוי", "ar": "معلومات خاطئة",
				"zh": "虚假信息", "ja": "誤った情報", "hi": "गलत जानकारी", "de": "Falsche Informationen", "th": "ข้อมูลเท็จ",
				"ru": "Ложная информация", "pl": "Fałszywe informacje", "fr": "Informations fausses", "pt": "Informações falsas", "id": "Informasi palsu", "bn": "মিথ্যা তথ্য",
			},
			Description: utils.LocalizedString{
				"en": "Spreading false or misleading information.",
				"tr": "Yanlış veya yanıltıcı bilgi yaymak.",
				"es": "Difundir información falsa o engañosa.",
				"he": "הפצת מידע שגוי או מטעה.",
				"ar": "نشر معلومات خاطئة أو مضللة.",
				"zh": "传播虚假或误导性信息。",
				"ja": "虚偽または誤解を招く情報の拡散。",
				"hi": "गलत या भ्रामक जानकारी फैलाना।",
				"de": "Verbreitung falscher oder irreführender Informationen.",
				"th": "แพร่กระจายข้อมูลเท็จหรือที่ทำให้เข้าใจผิด",
				"ru": "Распространение ложной или вводящей в заблуждение информации.",
				"pl": "Rozpowszechnianie fałszywych lub wprowadzających w błąd informacji.",
				"fr": "Diffusion d'informations fausses ou trompeuses.",
				"pt": "Divulgação de informações falsas ou enganosas.",
				"id": "Menyebarkan informasi palsu atau menyesatkan.",
				"bn": "মিথ্যা বা বিভ্রান্তিকর তথ্য ছড়ানো।",
			},
		},
		{
			Key:          report.ReportKindProfanity,
			DisplayOrder: 9,
			Name: utils.LocalizedString{
				"en": "Profanity", "tr": "Küfür", "es": "Profanidad", "he": "קללות", "ar": "كلمات بذيئة",
				"zh": "亵渎", "ja": "不適切な言葉", "hi": "गाली-गलौज", "de": "Flüche", "th": "คำหยาบ",
				"ru": "Ненормативная лексика", "pl": "Przekleństwa", "fr": "Grossièretés", "pt": "Palavrões", "id": "Kata-kata kasar", "bn": "অশ্লীল ভাষা",
			},
			Description: utils.LocalizedString{
				"en": "Use of offensive or inappropriate language.",
				"tr": "Saldırgan veya uygunsuz dil kullanımı.",
				"es": "Uso de lenguaje ofensivo o inapropiado.",
				"he": "שימוש בשפה פוגענית או לא הולמת.",
				"ar": "استخدام لغة مسيئة أو غير مناسبة.",
				"zh": "使用冒犯性或不适当的语言。",
				"ja": "攻撃的または不適切な言葉の使用。",
				"hi": "अपमानजनक या अनुचित भाषा का उपयोग।",
				"de": "Verwendung beleidigender oder unangemessener Sprache.",
				"th": "การใช้ภาษาที่ไม่เหมาะสมหรือหยาบคาย",
				"ru": "Использование оскорбительной или неприемлемой лексики.",
				"pl": "Używanie obraźliwego lub nieodpowiedniego języka.",
				"fr": "Utilisation d'un langage offensant ou inapproprié.",
				"pt": "Uso de linguagem ofensiva ou inadequada.",
				"id": "Penggunaan bahasa yang menyinggung atau tidak pantas.",
				"bn": "অপমানজনক বা অপ্রাসঙ্গিক ভাষার ব্যবহার।",
			},
		},
		{
			Key:          report.ReportKindSelfHarm,
			DisplayOrder: 10,
			Name: utils.LocalizedString{
				"en": "Self-Harm", "tr": "Kendine Zarar", "es": "Autolesión", "he": "פגיעה עצמית", "ar": "إيذاء النفس",
				"zh": "自残", "ja": "自傷行為", "hi": "आत्म-हानि", "de": "Selbstverletzung", "th": "ทำร้ายตัวเอง",
				"ru": "Самоповреждение", "pl": "Samouszkodzenie", "fr": "Automutilation", "pt": "Auto-mutilação", "id": "Menyakiti diri sendiri", "bn": "আত্মক্ষতি",
			},
			Description: utils.LocalizedString{
				"en": "Content promoting or depicting self-harm.",
				"tr": "Kendine zarar verme içeren veya teşvik eden içerik.",
				"es": "Contenido que promueve o muestra autolesiones.",
				"he": "תוכן המעודד או מציג פגיעה עצמית.",
				"ar": "محتوى يروج أو يصور إيذاء النفس.",
				"zh": "宣传或描绘自残的内容。",
				"ja": "自傷行為を促進または描写するコンテンツ。",
				"hi": "आत्म-हानि को बढ़ावा देने वाला या दर्शाने वाला सामग्री।",
				"de": "Inhalte, die Selbstverletzung fördern oder darstellen.",
				"th": "เนื้อหาที่ส่งเสริมหรือแสดงการทำร้ายตัวเอง",
				"ru": "Контент, пропагандирующий или изображающий самоповреждение.",
				"pl": "Treści promujące lub przedstawiające samouszkodzenia.",
				"fr": "Contenu promouvant ou décrivant l'automutilation.",
				"pt": "Conteúdo que promove ou descreve auto-mutilação.",
				"id": "Konten yang mempromosikan atau menggambarkan menyakiti diri sendiri.",
				"bn": "আত্ম-ক্ষতির প্রচার বা চিত্রায়ন করা বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindCopyrightInfringement,
			DisplayOrder: 11,
			Name: utils.LocalizedString{
				"en": "Copyright Infringement", "tr": "Telif Hakkı İhlali", "es": "Infracción de derechos de autor", "he": "הפרת זכויות יוצרים", "ar": "انتهاك حقوق النشر",
				"zh": "版权侵犯", "ja": "著作権侵害", "hi": "कॉपीराइट उल्लंघन", "de": "Urheberrechtsverletzung", "th": "ละเมิดลิขสิทธิ์",
				"ru": "Нарушение авторских прав", "pl": "Naruszenie praw autorskich", "fr": "Violation des droits d'auteur", "pt": "Violação de direitos autorais", "id": "Pelanggaran hak cipta", "bn": "কপিরাইট লঙ্ঘন",
			},
			Description: utils.LocalizedString{
				"en": "Unauthorized use of copyrighted material.",
				"tr": "Telif hakkı koruması altındaki materyalin izinsiz kullanımı.",
				"es": "Uso no autorizado de material con derechos de autor.",
				"he": "שימוש בלתי מורשה בחומר המוגן בזכויות יוצרים.",
				"ar": "استخدام غير مصرح به لمواد محمية بحقوق الطبع والنشر.",
				"zh": "未经授权使用受版权保护的材料。",
				"ja": "著作権で保護された素材の無断使用。",
				"hi": "कॉपीराइटेड सामग्री का अनधिकृत उपयोग।",
				"de": "Unbefugte Nutzung von urheberrechtlich geschütztem Material.",
				"th": "การใช้วัสดุที่มีลิขสิทธิ์โดยไม่ได้รับอนุญาต",
				"ru": "Несанкционированное использование материалов, защищённых авторским правом.",
				"pl": "Nieautoryzowane użycie materiałów objętych prawem autorskim.",
				"fr": "Utilisation non autorisée de matériel protégé par des droits d'auteur.",
				"pt": "Uso não autorizado de material protegido por direitos autorais.",
				"id": "Penggunaan materi berhak cipta tanpa izin.",
				"bn": "কপিরাইট সংরক্ষিত সামগ্রীর অননুমোদিত ব্যবহার।",
			},
		},
		{
			Key:          report.ReportKindDrugUse,
			DisplayOrder: 12,
			Name: utils.LocalizedString{
				"en": "Drug Use", "tr": "Uyuşturucu Kullanımı", "es": "Uso de drogas", "he": "שימוש בסמים", "ar": "تعاطي المخدرات",
				"zh": "吸毒", "ja": "薬物使用", "hi": "ड्रग उपयोग", "de": "Drogenkonsum", "th": "การใช้ยาเสพติด",
				"ru": "Употребление наркотиков", "pl": "Używanie narkotyków", "fr": "Usage de drogue", "pt": "Uso de drogas", "id": "Penggunaan narkoba", "bn": "মাদক ব্যবহার",
			},
			Description: utils.LocalizedString{
				"en": "Content showing or promoting drug use.",
				"tr": "Uyuşturucu kullanımı gösteren veya teşvik eden içerik.",
				"es": "Contenido que muestra o promueve el uso de drogas.",
				"he": "תוכן שמציג או מקדם שימוש בסמים.",
				"ar": "محتوى يعرض أو يروج لتعاطي المخدرات.",
				"zh": "展示或宣传吸毒的内容。",
				"ja": "薬物使用を示したり促進したりするコンテンツ。",
				"hi": "ड्रग उपयोग को दिखाने या बढ़ावा देने वाली सामग्री।",
				"de": "Inhalte, die Drogenkonsum zeigen oder fördern.",
				"th": "เนื้อหาที่แสดงหรือส่งเสริมการใช้ยาเสพติด",
				"ru": "Контент, показывающий или пропагандирующий употребление наркотиков.",
				"pl": "Treści pokazujące lub promujące używanie narkotyków.",
				"fr": "Contenu montrant ou promouvant l'usage de drogue.",
				"pt": "Conteúdo mostrando ou promovendo o uso de drogas.",
				"id": "Konten yang menunjukkan atau mempromosikan penggunaan narkoba.",
				"bn": "মাদক ব্যবহার দেখানো বা প্রচার করা বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindTerrorism,
			DisplayOrder: 13,
			Name: utils.LocalizedString{
				"en": "Terrorism", "tr": "Terörizm", "es": "Terrorismo", "he": "טרור", "ar": "إرهاب",
				"zh": "恐怖主义", "ja": "テロリズム", "hi": "आतंकवाद", "de": "Terrorismus", "th": "การก่อการร้าย",
				"ru": "Терроризм", "pl": "Terroryzm", "fr": "Terrorisme", "pt": "Terrorismo", "id": "Terorisme", "bn": "সন্ত্রাসবাদ",
			},
			Description: utils.LocalizedString{
				"en": "Content supporting or promoting terrorism.",
				"tr": "Terörizmi destekleyen veya teşvik eden içerik.",
				"es": "Contenido que apoya o promueve el terrorismo.",
				"he": "תוכן התומך או מקדם טרור.",
				"ar": "محتوى يدعم أو يروج للإرهاب.",
				"zh": "支持或宣传恐怖主义的内容。",
				"ja": "テロリズムを支持または促進するコンテンツ。",
				"hi": "आतंकवाद का समर्थन या प्रचार करने वाली सामग्री।",
				"de": "Inhalte, die Terrorismus unterstützen oder fördern.",
				"th": "เนื้อหาที่สนับสนุนหรือส่งเสริมการก่อการร้าย",
				"ru": "Контент, поддерживающий или пропагандирующий терроризм.",
				"pl": "Treści wspierające lub promujące terroryzm.",
				"fr": "Contenu soutenant ou promouvant le terrorisme.",
				"pt": "Conteúdo que apoia ou promove o terrorismo.",
				"id": "Konten yang mendukung atau mempromosikan terorisme.",
				"bn": "সন্ত্রাসবাদকে সমর্থন বা প্রচার করে এমন বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindPoliticalContent,
			DisplayOrder: 14,
			Name: utils.LocalizedString{
				"en": "Political Content", "tr": "Siyasi İçerik", "es": "Contenido político", "he": "תוכן פוליטי", "ar": "محتوى سياسي",
				"zh": "政治内容", "ja": "政治的内容", "hi": "राजनीतिक सामग्री", "de": "Politische Inhalte", "th": "เนื้อหาการเมือง",
				"ru": "Политический контент", "pl": "Treści polityczne", "fr": "Contenu politique", "pt": "Conteúdo político", "id": "Konten politik", "bn": "রাজনৈতিক বিষয়বস্তু",
			},
			Description: utils.LocalizedString{
				"en": "Content related to politics or political campaigns.",
				"tr": "Siyaset veya siyasi kampanyalarla ilgili içerik.",
				"es": "Contenido relacionado con la política o campañas políticas.",
				"he": "תוכן הקשור לפוליטיקה או קמפיינים פוליטיים.",
				"ar": "محتوى متعلق بالسياسة أو الحملات السياسية.",
				"zh": "与政治或政治活动相关的内容。",
				"ja": "政治や政治キャンペーンに関連するコンテンツ。",
				"hi": "राजनीति या राजनीतिक अभियानों से संबंधित सामग्री।",
				"de": "Inhalte im Zusammenhang mit Politik oder politischen Kampagnen.",
				"th": "เนื้อหาที่เกี่ยวข้องกับการเมืองหรือแคมเปญทางการเมือง",
				"ru": "Контент, связанный с политикой или политическими кампаниями.",
				"pl": "Treści związane z polityką lub kampaniami politycznymi.",
				"fr": "Contenu lié à la politique ou aux campagnes politiques.",
				"pt": "Conteúdo relacionado à política ou campanhas políticas.",
				"id": "Konten terkait politik atau kampanye politik.",
				"bn": "রাজনীতি বা রাজনৈতিক প্রচারণার সাথে সম্পর্কিত বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindMisleadingAdvertising,
			DisplayOrder: 15,
			Name: utils.LocalizedString{
				"en": "Misleading Advertising", "tr": "Yanıltıcı Reklam", "es": "Publicidad engañosa", "he": "פרסום מטעה", "ar": "إعلانات مضللة",
				"zh": "误导性广告", "ja": "誤解を招く広告", "hi": "भ्रामक विज्ञापन", "de": "Irreführende Werbung", "th": "โฆษณาที่หลอกลวง",
				"ru": "Вводящая в заблуждение реклама", "pl": "Wprowadzająca w błąd reklama", "fr": "Publicité mensongère", "pt": "Publicidade enganosa", "id": "Iklan menyesatkan", "bn": "ভ্রান্তিকর বিজ্ঞাপন",
			},
			Description: utils.LocalizedString{
				"en": "Advertising that deceives or misleads consumers.",
				"tr": "Tüketicileri aldatıcı veya yanıltıcı reklamlar.",
				"es": "Publicidad que engaña o induce a error a los consumidores.",
				"he": "פרסום שמטעה או מטעה את הצרכנים.",
				"ar": "إعلانات تخدع أو تضلل المستهلكين.",
				"zh": "欺骗或误导消费者的广告。",
				"ja": "消費者を欺くまたは誤解させる広告。",
				"hi": "विज्ञापन जो उपभोक्ताओं को धोखा देता है या भ्रमित करता है।",
				"de": "Werbung, die Verbraucher täuscht oder in die Irre führt.",
				"th": "โฆษณาที่หลอกลวงหรือลวงผู้บริโภค",
				"ru": "Реклама, вводящая потребителей в заблуждение.",
				"pl": "Reklama wprowadzająca konsumentów w błąd.",
				"fr": "Publicité qui trompe ou induit en erreur les consommateurs.",
				"pt": "Publicidade que engana ou induz consumidores ao erro.",
				"id": "Iklan yang menipu atau menyesatkan konsumen.",
				"bn": "ভোক্তাদের বিভ্রান্তিকর বা মিথ্যা বিজ্ঞাপন।",
			},
		},
		{
			Key:          report.ReportKindSecurityVulnerability,
			DisplayOrder: 16,
			Name: utils.LocalizedString{
				"en": "Security Vulnerability", "tr": "Güvenlik Açığı", "es": "Vulnerabilidad de seguridad", "he": "פגיעות אבטחה", "ar": "ثغرة أمنية",
				"zh": "安全漏洞", "ja": "セキュリティの脆弱性", "hi": "सुरक्षा कमजोरी", "de": "Sicherheitslücke", "th": "ช่องโหว่ความปลอดภัย",
				"ru": "Уязвимость безопасности", "pl": "Luka bezpieczeństwa", "fr": "Vulnérabilité de sécurité", "pt": "Vulnerabilidade de segurança", "id": "Kerentanan keamanan", "bn": "নিরাপত্তা দুর্বলতা",
			},
			Description: utils.LocalizedString{
				"en": "Exposure of security weaknesses or exploits.",
				"tr": "Güvenlik açıklarının veya sömürülerin ifşası.",
				"es": "Exposición de debilidades o explotaciones de seguridad.",
				"he": "חשיפת חולשות אבטחה או ניצוליהן.",
				"ar": "كشف نقاط ضعف أو استغلالات أمنية.",
				"zh": "安全漏洞或利用的曝光。",
				"ja": "セキュリティの弱点やエクスプロイトの公開。",
				"hi": "सुरक्षा कमजोरियों या शोषणों का खुलासा।",
				"de": "Offenlegung von Sicherheitslücken oder Exploits.",
				"th": "การเปิดเผยจุดอ่อนหรือช่องโหว่ด้านความปลอดภัย",
				"ru": "Обнародование уязвимостей или эксплойтов безопасности.",
				"pl": "Ujawnienie słabości lub exploitów bezpieczeństwa.",
				"fr": "Exposition des faiblesses ou des exploits de sécurité.",
				"pt": "Exposição de vulnerabilidades ou explorações de segurança.",
				"id": "Paparan kelemahan atau eksploitasi keamanan.",
				"bn": "নিরাপত্তা দুর্বলতা বা শোষণের প্রকাশ।",
			},
		},
		{
			Key:          report.ReportKindFakeProfile,
			DisplayOrder: 17,
			Name: utils.LocalizedString{
				"en": "Fake Profile", "tr": "Sahte Profil", "es": "Perfil falso", "he": "פרופיל מזויף", "ar": "ملف مزيف",
				"zh": "假冒资料", "ja": "偽のプロフィール", "hi": "नकली प्रोफ़ाइल", "de": "Gefälschtes Profil", "th": "โปรไฟล์ปลอม",
				"ru": "Фейковый профиль", "pl": "Fałszywy profil", "fr": "Profil faux", "pt": "Perfil falso", "id": "Profil palsu", "bn": "নকল প্রোফাইল",
			},
			Description: utils.LocalizedString{
				"en": "Profiles that impersonate others or are fabricated.",
				"tr": "Başkalarını taklit eden veya uydurma profiller.",
				"es": "Perfiles que suplantan a otros o son falsos.",
				"he": "פרופילים שמתחזים לאחרים או מזויפים.",
				"ar": "ملفات شخصية تنتحل شخصية الآخرين أو مزيفة.",
				"zh": "冒充他人或伪造的资料。",
				"ja": "他人になりすましたり作られたプロフィール。",
				"hi": "ऐसे प्रोफाइल जो दूसरों का बहाना करते हैं या बनाए गए हैं।",
				"de": "Profile, die andere imitieren oder gefälscht sind.",
				"th": "โปรไฟล์ที่แอบอ้างผู้อื่นหรือถูกปลอมแปลง",
				"ru": "Профили, выдающие себя за других или поддельные.",
				"pl": "Profile podszywające się pod innych lub fałszywe.",
				"fr": "Profils qui usurpent l'identité d'autres ou sont fabriqués.",
				"pt": "Perfis que se passam por outros ou são fabricados.",
				"id": "Profil yang meniru orang lain atau dibuat-buat.",
				"bn": "যারা অন্যদের নকল করে বা তৈরি প্রোফাইল।",
			},
		},
		{
			Key:          report.ReportKindUnderage,
			DisplayOrder: 18,
			Name: utils.LocalizedString{
				"en": "Underage", "tr": "Reşit Olmayan", "es": "Menor de edad", "he": "קטין", "ar": "قاصر",
				"zh": "未成年", "ja": "未成年", "hi": "अल्पवयस्क", "de": "Minderjährig", "th": "อายุต่ำกว่าเกณฑ์",
				"ru": "Несовершеннолетний", "pl": "Niepełnoletni", "fr": "Mineur", "pt": "Menor de idade", "id": "Di bawah umur", "bn": "অপ্রাপ্তবয়স্ক",
			},
			Description: utils.LocalizedString{
				"en": "Content involving minors or underage individuals.",
				"tr": "Reşit olmayan bireyleri içeren içerik.",
				"es": "Contenido que involucra a menores de edad.",
				"he": "תוכן הכולל קטינים.",
				"ar": "محتوى يتضمن قاصرين.",
				"zh": "涉及未成年人的内容。",
				"ja": "未成年者を含むコンテンツ。",
				"hi": "अल्पवयस्कों से संबंधित सामग्री।",
				"de": "Inhalte, die Minderjährige betreffen.",
				"th": "เนื้อหาที่เกี่ยวข้องกับบุคคลที่ยังไม่บรรลุนิติภาวะ",
				"ru": "Контент с участием несовершеннолетних.",
				"pl": "Treści dotyczące nieletnich osób.",
				"fr": "Contenu impliquant des mineurs.",
				"pt": "Conteúdo envolvendo menores de idade.",
				"id": "Konten yang melibatkan anak di bawah umur.",
				"bn": "অপ্রাপ্তবয়স্কদের অন্তর্ভুক্ত বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindImpersonation,
			DisplayOrder: 19,
			Name: utils.LocalizedString{
				"en": "Impersonation", "tr": "Kişi Taklidi", "es": "Suplantación", "he": "התחזות", "ar": "انتحال شخصية",
				"zh": "冒充", "ja": "なりすまし", "hi": "नक़ल", "de": "Identitätsdiebstahl", "th": "การแอบอ้างตัวตน",
				"ru": "Самозванство", "pl": "Podszywanie się", "fr": "Usurpation d'identité", "pt": "Personificação", "id": "Peniruan", "bn": "নকল করা",
			},
			Description: utils.LocalizedString{
				"en": "Pretending to be someone else or misleading others.",
				"tr": "Başkasını taklit etmek veya başkalarını yanıltmak.",
				"es": "Hacerse pasar por otra persona o engañar a otros.",
				"he": "להעמיד פנים שהוא מישהו אחר או להטעות אחרים.",
				"ar": "التظاهر بأنه شخص آخر أو تضليل الآخرين.",
				"zh": "假装成他人或误导他人。",
				"ja": "他人になりすますことや他者を誤解させること。",
				"hi": "किसी और के होने का दिखावा करना या दूसरों को भ्रमित करना।",
				"de": "Vortäuschen, jemand anderes zu sein, oder andere in die Irre führen.",
				"th": "แกล้งทำเป็นคนอื่นหรือทำให้คนอื่นเข้าใจผิด",
				"ru": "Притворство другим человеком или введение в заблуждение.",
				"pl": "Udawanie kogoś innego lub wprowadzanie innych w błąd.",
				"fr": "Prétendre être quelqu'un d'autre ou induire les autres en erreur.",
				"pt": "Fingir ser outra pessoa ou enganar os outros.",
				"id": "Berlaku seolah-olah orang lain atau menyesatkan orang lain.",
				"bn": "অন্যের ভান করা বা অন্যদের বিভ্রান্ত করা।",
			},
		},
		{
			Key:          report.ReportKindNonConsensualContent,
			DisplayOrder: 20,
			Name: utils.LocalizedString{
				"en": "Non-Consensual Content", "tr": "Rızasız İçerik", "es": "Contenido no consensuado", "he": "תוכן ללא הסכמה", "ar": "محتوى بدون موافقة",
				"zh": "未经同意的内容", "ja": "同意なしのコンテンツ", "hi": "बिना सहमति की सामग्री", "de": "Inhalte ohne Zustimmung", "th": "เนื้อหาที่ไม่ได้รับความยินยอม",
				"ru": "Контент без согласия", "pl": "Treść bez zgody", "fr": "Contenu non consensuel", "pt": "Conteúdo não consensual", "id": "Konten tanpa persetujuan", "bn": "অননুমোদিত বিষয়বস্তু",
			},
			Description: utils.LocalizedString{
				"en": "Content shared without the consent of involved parties.",
				"tr": "İlgili tarafların rızası olmadan paylaşılan içerik.",
				"es": "Contenido compartido sin el consentimiento de las partes involucradas.",
				"he": "תוכן ששיתוף שלו נעשה ללא הסכמת הצדדים המעורבים.",
				"ar": "محتوى تم مشاركته بدون موافقة الأطراف المعنية.",
				"zh": "未经相关方同意分享的内容。",
				"ja": "関係者の同意なしに共有されたコンテンツ。",
				"hi": "संबंधित पक्षों की सहमति के बिना साझा की गई सामग्री।",
				"de": "Inhalte, die ohne Zustimmung der beteiligten Parteien geteilt wurden.",
				"th": "เนื้อหาที่แชร์โดยไม่ได้รับความยินยอมจากฝ่ายที่เกี่ยวข้อง",
				"ru": "Контент, распространённый без согласия участников.",
				"pl": "Treść udostępniona bez zgody zainteresowanych stron.",
				"fr": "Contenu partagé sans le consentement des parties impliquées.",
				"pt": "Conteúdo compartilhado sem o consentimento das partes envolvidas.",
				"id": "Konten yang dibagikan tanpa persetujuan pihak terkait.",
				"bn": "সম্পৃক্ত পক্ষদের সম্মতি ছাড়া শেয়ার করা বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindSexualHarassment,
			DisplayOrder: 21,
			Name: utils.LocalizedString{
				"en": "Sexual Harassment", "tr": "Cinsel Taciz", "es": "Acoso sexual", "he": "הטרדה מינית", "ar": "التحرش الجنسي",
				"zh": "性骚扰", "ja": "性的嫌がらせ", "hi": "यौन उत्पीड़न", "de": "Sexuelle Belästigung", "th": "การล่วงละเมิดทางเพศ",
				"ru": "Сексуальные домогательства", "pl": "Molestowanie seksualne", "fr": "Harcèlement sexuel", "pt": "Assédio sexual", "id": "Pelecehan seksual", "bn": "যৌন হয়রানি",
			},
			Description: utils.LocalizedString{
				"en": "Unwanted sexual advances or harassment.",
				"tr": "İstenmeyen cinsel yaklaşımlar veya taciz.",
				"es": "Avances o acoso sexual no deseados.",
				"he": "התקדמות מינית או הטרדה בלתי רצויה.",
				"ar": "مضايقات أو تقدمات جنسية غير مرغوب فيها.",
				"zh": "不受欢迎的性挑逗或骚扰。",
				"ja": "望まれない性的なアプローチや嫌がらせ。",
				"hi": "अनचाहे यौन संपर्क या उत्पीड़न।",
				"de": "Unerwünschte sexuelle Annäherungen oder Belästigungen.",
				"th": "การล่วงละเมิดหรือเสนอทางเพศที่ไม่ต้องการ",
				"ru": "Нежелательные сексуальные приставания или домогательства.",
				"pl": "Niechciane seksualne propozycje lub molestowanie.",
				"fr": "Avances ou harcèlement sexuels non désirés.",
				"pt": "Avanços ou assédio sexual indesejados.",
				"id": "Pendekatan seksual atau pelecehan yang tidak diinginkan.",
				"bn": "অপছন্দসই যৌন আক্রমণ বা হয়রানি।",
			},
		},
		{
			Key:          report.ReportKindSolicitation,
			DisplayOrder: 22,
			Name: utils.LocalizedString{
				"en": "Solicitation", "tr": "Talep", "es": "Solicitación", "he": "בקשה", "ar": "التحريض",
				"zh": "招揽", "ja": "勧誘", "hi": "प्रार्थना", "de": "Anwerbung", "th": "การขอร้อง",
				"ru": "Вымогательство", "pl": "Natarczywość", "fr": "Sollicitation", "pt": "Solicitação", "id": "Permintaan", "bn": "অনুরোধ",
			},
			Description: utils.LocalizedString{
				"en": "Requesting or encouraging certain actions, often inappropriately.",
				"tr": "Genellikle uygunsuz şekilde belirli eylemlerin talep edilmesi veya teşviki.",
				"es": "Solicitar o fomentar ciertas acciones, a menudo de manera inapropiada.",
				"he": "בקשה או עידוד לפעולות מסוימות, לעיתים בצורה לא הולמת.",
				"ar": "طلب أو تشجيع على أفعال معينة، غالبًا بشكل غير مناسب.",
				"zh": "请求或鼓励某些行为，通常不恰当。",
				"ja": "特定の行動を要求または奨励すること、しばしば不適切に。",
				"hi": "कुछ कार्यों का अनुरोध या प्रोत्साहन, अक्सर अनुचित रूप से।",
				"de": "Anforderung oder Ermutigung zu bestimmten Handlungen, oft unangemessen.",
				"th": "การขอหรือสนับสนุนบางอย่าง โดยมักไม่เหมาะสม",
				"ru": "Запрос или поощрение определенных действий, часто неуместных.",
				"pl": "Prośba lub zachęcanie do określonych działań, często nieodpowiednio.",
				"fr": "Demander ou encourager certaines actions, souvent de manière inappropriée.",
				"pt": "Solicitar ou incentivar certas ações, muitas vezes de forma inadequada.",
				"id": "Meminta atau mendorong tindakan tertentu, seringkali tidak pantas.",
				"bn": "নির্দিষ্ট কাজের অনুরোধ বা উৎসাহ দেওয়া, প্রায়ই অনুপযুক্তভাবে।",
			},
		},
		{
			Key:          report.ReportKindSelfPromotion,
			DisplayOrder: 23,
			Name: utils.LocalizedString{
				"en": "Self Promotion", "tr": "Kendi Kendini Tanıtma", "es": "Auto-promoción", "he": "קידום עצמי", "ar": "الترويج الذاتي",
				"zh": "自我推广", "ja": "自己宣伝", "hi": "स्वयं प्रचार", "de": "Selbstpromotion", "th": "การโปรโมตตัวเอง",
				"ru": "Самореклама", "pl": "Autopromocja", "fr": "Auto-promotion", "pt": "Auto-promoção", "id": "Promosi diri", "bn": "স্বপ্রচার",
			},
			Description: utils.LocalizedString{
				"en": "Content primarily meant to promote oneself or own services.",
				"tr": "Kendini veya kendi hizmetlerini ön planda tutan içerikler.",
				"es": "Contenido destinado principalmente a promocionarse a uno mismo o a sus servicios.",
				"he": "תוכן שמיועד בעיקר לקדם את עצמו או את השירותים שלו.",
				"ar": "محتوى يهدف بشكل أساسي إلى الترويج للنفس أو للخدمات الخاصة.",
				"zh": "主要用于自我或自有服务推广的内容。",
				"ja": "主に自分自身や自分のサービスを宣伝するためのコンテンツ。",
				"hi": "मुख्य रूप से स्वयं या अपनी सेवाओं को बढ़ावा देने वाली सामग्री।",
				"de": "Inhalte, die hauptsächlich der Selbst- oder Dienstleistungsförderung dienen.",
				"th": "เนื้อหาที่เน้นโปรโมตตัวเองหรือบริการของตนเอง",
				"ru": "Контент, направленный в первую очередь на самопродвижение или продвижение собственных услуг.",
				"pl": "Treści mające na celu głównie autopromocję lub promocję własnych usług.",
				"fr": "Contenu principalement destiné à promouvoir soi-même ou ses services.",
				"pt": "Conteúdo principalmente destinado a promover a si mesmo ou seus serviços.",
				"id": "Konten yang terutama ditujukan untuk mempromosikan diri sendiri atau layanan sendiri.",
				"bn": "প্রধানত নিজেকে বা নিজের সেবাগুলোকে প্রচার করার জন্য বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindGraphicViolence,
			DisplayOrder: 24,
			Name: utils.LocalizedString{
				"en": "Graphic Violence", "tr": "Grafik Şiddet", "es": "Violencia gráfica", "he": "אלימות גרפית", "ar": "عنف صريح",
				"zh": "血腥暴力", "ja": "グラフィックな暴力", "hi": "ग्राफिक हिंसा", "de": "Grafische Gewalt", "th": "ความรุนแรงที่ชัดเจน",
				"ru": "Графическое насилие", "pl": "Graficzna przemoc", "fr": "Violence graphique", "pt": "Violência gráfica", "id": "Kekerasan grafis", "bn": "গ্রাফিক সহিংসতা",
			},
			Description: utils.LocalizedString{
				"en": "Explicit and disturbing violent content.",
				"tr": "Açık ve rahatsız edici şiddet içerikleri.",
				"es": "Contenido violento explícito y perturbador.",
				"he": "תוכן אלים מפורש ומטריד.",
				"ar": "محتوى عنيف صريح ومزعج.",
				"zh": "明确且令人不安的暴力内容。",
				"ja": "明示的で不快な暴力的コンテンツ。",
				"hi": "स्पष्ट और परेशान करने वाली हिंसात्मक सामग्री।",
				"de": "Explizite und verstörende gewalttätige Inhalte.",
				"th": "เนื้อหาความรุนแรงที่ชัดเจนและน่ารำคาญ",
				"ru": "Явный и тревожный насильственный контент.",
				"pl": "Wyraźna i niepokojąca przemoc.",
				"fr": "Contenu violent explicite et perturbant.",
				"pt": "Conteúdo violento explícito e perturbador.",
				"id": "Konten kekerasan yang eksplisit dan mengganggu.",
				"bn": "স্পষ্ট এবং উদ্বেগজনক সহিংস সামগ্রী।",
			},
		},
		{
			Key:          report.ReportKindDiscriminatoryLanguage,
			DisplayOrder: 25,
			Name: utils.LocalizedString{
				"en": "Discriminatory Language", "tr": "Ayrımcı Dil", "es": "Lenguaje discriminatorio", "he": "שפה מפלה", "ar": "لغة تمييزية",
				"zh": "歧视性语言", "ja": "差別的な言葉遣い", "hi": "भेदभावपूर्ण भाषा", "de": "Diskriminierende Sprache", "th": "ภาษาแบ่งแยก",
				"ru": "Дискриминационная речь", "pl": "Język dyskryminujący", "fr": "Langage discriminatoire", "pt": "Linguagem discriminatória", "id": "Bahasa diskriminatif", "bn": "বৈষম্যমূলক ভাষা",
			},
			Description: utils.LocalizedString{
				"en": "Language that discriminates against groups or individuals.",
				"tr": "Gruplara veya bireylere karşı ayrımcılık içeren dil.",
				"es": "Lenguaje que discrimina contra grupos o individuos.",
				"he": "שפה שמפליגה נגד קבוצות או יחידים.",
				"ar": "لغة تميز ضد مجموعات أو أفراد.",
				"zh": "歧视群体或个人的语言。",
				"ja": "グループや個人を差別する言葉。",
				"hi": "ऐसी भाषा जो समूहों या व्यक्तियों के साथ भेदभाव करती है।",
				"de": "Sprache, die gegen Gruppen oder Einzelpersonen diskriminiert.",
				"th": "ภาษาแบ่งแยกกลุ่มหรือบุคคล",
				"ru": "Речь, дискриминирующая группы или отдельных лиц.",
				"pl": "Język dyskryminujący grupy lub osoby.",
				"fr": "Langage qui discrimine des groupes ou des individus.",
				"pt": "Linguagem que discrimina grupos ou indivíduos.",
				"id": "Bahasa yang mendiskriminasi kelompok atau individu.",
				"bn": "যে ভাষা গ্রুপ বা ব্যক্তিদের বৈষম্য করে।",
			},
		},
		{
			Key:          report.ReportKindMalwarePhishing,
			DisplayOrder: 26,
			Name: utils.LocalizedString{
				"en": "Malware / Phishing", "tr": "Kötü Amaçlı Yazılım / Phishing", "es": "Malware / Phishing", "he": "תוכנות זדוניות / פישינג", "ar": "برمجيات خبيثة / تصيد",
				"zh": "恶意软件 / 网络钓鱼", "ja": "マルウェア / フィッシング", "hi": "मैलवेयर / फिशिंग", "de": "Malware / Phishing", "th": "มัลแวร์ / ฟิชชิ่ง",
				"ru": "Вредоносное ПО / Фишинг", "pl": "Złośliwe oprogramowanie / Phishing", "fr": "Logiciel malveillant / hameçonnage", "pt": "Malware / Phishing", "id": "Malware / Phishing", "bn": "ম্যালওয়্যার / ফিশিং",
			},
			Description: utils.LocalizedString{
				"en": "Content involving malicious software or phishing attempts.",
				"tr": "Kötü amaçlı yazılım veya kimlik avı girişimleri içeren içerikler.",
				"es": "Contenido que involucra software malicioso o intentos de phishing.",
				"he": "תוכן הכולל תוכנות זדוניות או ניסיונות פישינג.",
				"ar": "محتوى يتضمن برامج ضارة أو محاولات تصيد.",
				"zh": "涉及恶意软件或网络钓鱼尝试的内容。",
				"ja": "悪意のあるソフトウェアやフィッシングの試みを含むコンテンツ。",
				"hi": "हानिकारक सॉफ़्टवेयर या फ़िशिंग प्रयासों वाली सामग्री।",
				"de": "Inhalte mit schädlicher Software oder Phishing-Versuchen.",
				"th": "เนื้อหาที่เกี่ยวข้องกับซอฟต์แวร์ที่เป็นอันตรายหรือการพยายามฟิชชิ่ง",
				"ru": "Контент, связанный с вредоносным ПО или фишинговыми атаками.",
				"pl": "Treści związane ze złośliwym oprogramowaniem lub próbami phishingu.",
				"fr": "Contenu impliquant des logiciels malveillants ou des tentatives de phishing.",
				"pt": "Conteúdo envolvendo software malicioso ou tentativas de phishing.",
				"id": "Konten yang melibatkan perangkat lunak berbahaya atau upaya phishing.",
				"bn": "দুর্নীতিপূর্ণ সফটওয়্যার বা ফিশিং প্রচেষ্টার বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindInappropriateUsername,
			DisplayOrder: 27,
			Name: utils.LocalizedString{
				"en": "Inappropriate Username", "tr": "Uygunsuz Kullanıcı Adı", "es": "Nombre de usuario inapropiado", "he": "שם משתמש לא מתאים", "ar": "اسم مستخدم غير لائق",
				"zh": "不当用户名", "ja": "不適切なユーザー名", "hi": "अनुचित उपयोगकर्ता नाम", "de": "Unangemessener Benutzername", "th": "ชื่อผู้ใช้ที่ไม่เหมาะสม",
				"ru": "Неподходящее имя пользователя", "pl": "Nieodpowiednia nazwa użytkownika", "fr": "Nom d'utilisateur inapproprié", "pt": "Nome de usuário inadequado", "id": "Nama pengguna tidak pantas", "bn": "অশোভন ব্যবহারকারীর নাম",
			},
			Description: utils.LocalizedString{
				"en": "Usernames that are offensive or violate guidelines.",
				"tr": "Hakaret içeren veya kuralları ihlal eden kullanıcı adları.",
				"es": "Nombres de usuario ofensivos o que violan las reglas.",
				"he": "שמות משתמש פוגעניים או המפרים כללים.",
				"ar": "أسماء مستخدمين مسيئة أو تنتهك القواعد.",
				"zh": "冒犯性或违反规则的用户名。",
				"ja": "攻撃的またはガイドラインに違反するユーザー名。",
				"hi": "आक्रामक या नियमों का उल्लंघन करने वाले उपयोगकर्ता नाम।",
				"de": "Benutzernamen, die beleidigend sind oder Richtlinien verletzen.",
				"th": "ชื่อผู้ใช้ที่ไม่เหมาะสมหรือละเมิดกฎ",
				"ru": "Оскорбительные имена пользователей или нарушающие правила.",
				"pl": "Nazwy użytkowników obraźliwe lub naruszające zasady.",
				"fr": "Noms d'utilisateur offensants ou violant les règles.",
				"pt": "Nomes de usuário ofensivos ou que violam as diretrizes.",
				"id": "Nama pengguna yang menyinggung atau melanggar pedoman.",
				"bn": "অপমানজনক বা নির্দেশিকা লঙ্ঘনকারী ব্যবহারকারীর নাম।",
			},
		},
		{
			Key:          report.ReportKindSelfHarmPromotion,
			DisplayOrder: 28,
			Name: utils.LocalizedString{
				"en": "Self Harm Promotion", "tr": "Kendine Zarar Vermeyi Teşvik", "es": "Promoción de autolesiones", "he": "קידום פגיעה עצמית", "ar": "تشجيع إيذاء النفس",
				"zh": "自残宣传", "ja": "自傷行為の促進", "hi": "आत्म-हानि प्रचार", "de": "Förderung von Selbstverletzung", "th": "ส่งเสริมการทำร้ายตัวเอง",
				"ru": "Пропаганда самоубийства", "pl": "Promowanie samookaleczeń", "fr": "Promotion de l'automutilation", "pt": "Promoção de auto-mutilação", "id": "Promosi menyakiti diri sendiri", "bn": "আত্মহানির প্রচার",
			},
			Description: utils.LocalizedString{
				"en": "Content encouraging self-harm or suicide.",
				"tr": "Kendine zarar verme veya intiharı teşvik eden içerik.",
				"es": "Contenido que fomenta la autolesión o el suicidio.",
				"he": "תוכן המעודד פגיעה עצמית או התאבדות.",
				"ar": "محتوى يشجع إيذاء النفس أو الانتحار.",
				"zh": "鼓励自残或自杀的内容。",
				"ja": "自傷行為や自殺を促すコンテンツ。",
				"hi": "आत्म-हानि या आत्महत्या को प्रोत्साहित करने वाली सामग्री।",
				"de": "Inhalte, die Selbstverletzung oder Suizid fördern.",
				"th": "เนื้อหาที่สนับสนุนการทำร้ายตัวเองหรือฆ่าตัวตาย",
				"ru": "Контент, поощряющий самоповреждение или суицид.",
				"pl": "Treści zachęcające do samookaleczeń lub samobójstwa.",
				"fr": "Contenu encourageant l'automutilation ou le suicide.",
				"pt": "Conteúdo que incentiva o auto-mutilação ou suicídio.",
				"id": "Konten yang mendorong menyakiti diri sendiri atau bunuh diri.",
				"bn": "আত্মহানির বা আত্মহত্যার প্রচারকারী বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindThreatsBullying,
			DisplayOrder: 29,
			Name: utils.LocalizedString{
				"en": "Threats / Bullying", "tr": "Tehditler / Zorbalık", "es": "Amenazas / Acoso", "he": "איומים / בריונות", "ar": "تهديدات / تنمر",
				"zh": "威胁 / 欺凌", "ja": "脅迫 / いじめ", "hi": "धमकियां / बदमाशी", "de": "Bedrohungen / Mobbing", "th": "การข่มขู่ / รังแก",
				"ru": "Угрозы / Запугивание", "pl": "Groźby / Znęcanie się", "fr": "Menaces / Harcèlement", "pt": "Ameaças / Bullying", "id": "Ancaman / Perundungan", "bn": "হুমকি / বুলিং",
			},
			Description: utils.LocalizedString{
				"en": "Threatening or bullying behavior towards others.",
				"tr": "Başka kişilere yönelik tehdit veya zorbalık davranışı.",
				"es": "Comportamiento amenazante o acosador hacia otros.",
				"he": "התנהגות מאיימת או בריונית כלפי אחרים.",
				"ar": "سلوك تهديدي أو تنمري تجاه الآخرين.",
				"zh": "对他人的威胁或欺凌行为。",
				"ja": "他者に対する脅迫やいじめの行為。",
				"hi": "दूसरों के प्रति धमकी या बदमाशी व्यवहार।",
				"de": "Bedrohendes oder mobbendes Verhalten gegenüber anderen.",
				"th": "พฤติกรรมข่มขู่หรือรังแกผู้อื่น",
				"ru": "Угрожающие или запугивающие действия в адрес других.",
				"pl": "Zachowanie grożące lub znęcanie się nad innymi.",
				"fr": "Comportement menaçant ou intimidant envers les autres.",
				"pt": "Comportamento ameaçador ou bullying em relação aos outros.",
				"id": "Perilaku mengancam atau membully orang lain.",
				"bn": "অন্যদের প্রতি হুমকি বা বুলিং আচরণ।",
			},
		},
		{
			Key:          report.ReportKindPrivacyViolation,
			DisplayOrder: 30,
			Name: utils.LocalizedString{
				"en": "Privacy Violation", "tr": "Gizlilik İhlali", "es": "Violación de privacidad", "he": "הפרת פרטיות", "ar": "انتهاك الخصوصية",
				"zh": "隐私侵犯", "ja": "プライバシー侵害", "hi": "गोपनीयता उल्लंघन", "de": "Verletzung der Privatsphäre", "th": "การละเมิดความเป็นส่วนตัว",
				"ru": "Нарушение конфиденциальности", "pl": "Naruszenie prywatności", "fr": "Violation de la vie privée", "pt": "Violação de privacidade", "id": "Pelanggaran privasi", "bn": "গোপনীয়তা লঙ্ঘন",
			},
			Description: utils.LocalizedString{
				"en": "Unauthorized sharing or exposure of private information.",
				"tr": "Özel bilgilerin izinsiz paylaşılması veya ifşası.",
				"es": "Compartir o exponer información privada sin autorización.",
				"he": "שיתוף או חשיפה לא מורשית של מידע פרטי.",
				"ar": "مشاركة أو كشف معلومات خاصة دون إذن.",
				"zh": "未经授权共享或暴露私人信息。",
				"ja": "許可なく個人情報を共有または公開すること。",
				"hi": "गैरकानूनी निजी जानकारी साझा करना या उजागर करना।",
				"de": "Unbefugtes Teilen oder Offenlegen privater Informationen.",
				"th": "การแชร์หรือเปิดเผยข้อมูลส่วนตัวโดยไม่ได้รับอนุญาต",
				"ru": "Несанкционированное распространение или раскрытие личной информации.",
				"pl": "Nieautoryzowane udostępnianie lub ujawnianie prywatnych informacji.",
				"fr": "Partage ou exposition non autorisée d'informations privées.",
				"pt": "Compartilhamento ou exposição não autorizada de informações privadas.",
				"id": "Berbagi atau mengekspos informasi pribadi tanpa izin.",
				"bn": "অবৈধভাবে ব্যক্তিগত তথ্য শেয়ার বা প্রকাশ।",
			},
		},
		{
			Key:          report.ReportKindFakeNews,
			DisplayOrder: 31,
			Name: utils.LocalizedString{
				"en": "Fake News", "tr": "Sahte Haber", "es": "Noticias falsas", "he": "חדשות מזויפות", "ar": "أخبار مزيفة",
				"zh": "假新闻", "ja": "偽ニュース", "hi": "झूठी खबरें", "de": "Falsche Nachrichten", "th": "ข่าวปลอม",
				"ru": "Фейковые новости", "pl": "Fałszywe wiadomości", "fr": "Fausses nouvelles", "pt": "Notícias falsas", "id": "Berita palsu", "bn": "মিথ্যা খবর",
			},
			Description: utils.LocalizedString{
				"en": "False or misleading information presented as news.",
				"tr": "Haber olarak sunulan yanlış veya yanıltıcı bilgiler.",
				"es": "Información falsa o engañosa presentada como noticias.",
				"he": "מידע שקרי או מטעה המוצג כחדשות.",
				"ar": "معلومات كاذبة أو مضللة تُعرض كأخبار.",
				"zh": "作为新闻呈现的虚假或误导性信息。",
				"ja": "ニュースとして提示された偽情報または誤解を招く情報。",
				"hi": "समाचार के रूप में प्रस्तुत गलत या भ्रामक जानकारी।",
				"de": "Falsche oder irreführende Informationen, die als Nachrichten präsentiert werden.",
				"th": "ข้อมูลเท็จหรือทำให้เข้าใจผิดที่นำเสนอเป็นข่าว",
				"ru": "Ложная или вводящая в заблуждение информация, представленная как новости.",
				"pl": "Fałszywe lub wprowadzające w błąd informacje przedstawione jako wiadomości.",
				"fr": "Informations fausses ou trompeuses présentées comme des nouvelles.",
				"pt": "Informações falsas ou enganosas apresentadas como notícias.",
				"id": "Informasi palsu atau menyesatkan yang disajikan sebagai berita.",
				"bn": "নিউজ হিসাবে উপস্থাপিত মিথ্যা বা বিভ্রান্তিকর তথ্য।",
			},
		},
		{
			Key:          report.ReportKindReligiousHateSpeech,
			DisplayOrder: 32,
			Name: utils.LocalizedString{
				"en": "Religious Hate Speech", "tr": "Dini Nefret Söylemi", "es": "Discurso de odio religioso", "he": "דיבור שנאה דתי", "ar": "خطاب كراهية ديني",
				"zh": "宗教仇恨言论", "ja": "宗教的憎悪発言", "hi": "धार्मिक घृणा भाषण", "de": "Religiöse Hassrede", "th": "คำพูดเกลียดชังทางศาสนา",
				"ru": "Религиозная речь ненависти", "pl": "Religijna mowa nienawiści", "fr": "Discours de haine religieuse", "pt": "Discurso de ódio religioso", "id": "Ujaran kebencian agama", "bn": "ধর্মীয় ঘৃণা বক্তৃতা",
			},
			Description: utils.LocalizedString{
				"en": "Hate speech targeting individuals or groups based on religion.",
				"tr": "Dine dayalı bireyleri veya grupları hedef alan nefret söylemi.",
				"es": "Discurso de odio dirigido a individuos o grupos por motivos religiosos.",
				"he": "דיבור שנאה המכוון כלפי יחידים או קבוצות על בסיס דת.",
				"ar": "خطاب كراهية يستهدف أفرادًا أو مجموعات على أساس الدين.",
				"zh": "基于宗教针对个人或群体的仇恨言论。",
				"ja": "宗教に基づいて個人やグループを対象とした憎悪発言。",
				"hi": "धर्म के आधार पर व्यक्तियों या समूहों को लक्षित घृणा भाषण।",
				"de": "Hassrede, die sich gegen Einzelpersonen oder Gruppen aufgrund ihrer Religion richtet.",
				"th": "คำพูดเกลียดชังที่มุ่งเป้าหมายบุคคลหรือกลุ่มตามศาสนา",
				"ru": "Речь ненависти, направленная против лиц или групп на религиозной основе.",
				"pl": "Mowa nienawiści skierowana przeciwko osobom lub grupom ze względu na religię.",
				"fr": "Discours de haine ciblant des individus ou groupes sur la base de la religion.",
				"pt": "Discurso de ódio direcionado a indivíduos ou grupos com base na religião.",
				"id": "Ujaran kebencian yang menargetkan individu atau kelompok berdasarkan agama.",
				"bn": "ধর্মের ভিত্তিতে ব্যক্তিদের বা গোষ্ঠীকে লক্ষ্য করে ঘৃণা বক্তৃতা।",
			},
		},
		{
			Key:          report.ReportKindPoliticalExtremism,
			DisplayOrder: 33,
			Name: utils.LocalizedString{
				"en": "Political Extremism", "tr": "Siyasi Aşırılık", "es": "Extremismo político", "he": "קיצוניות פוליטית", "ar": "التطرف السياسي",
				"zh": "政治极端主义", "ja": "政治的過激主義", "hi": "राजनीतिक चरमपंथ", "de": "Politischer Extremismus", "th": "ลัทธิสุดโต่งทางการเมือง",
				"ru": "Политический экстремизм", "pl": "Ekstremizm polityczny", "fr": "Extrémisme politique", "pt": "Extremismo político", "id": "Ekstremisme politik", "bn": "রাজনৈতিক চরমপন্থা",
			},
			Description: utils.LocalizedString{
				"en": "Content promoting extreme political views or violence.",
				"tr": "Aşırı siyasi görüşleri veya şiddeti teşvik eden içerik.",
				"es": "Contenido que promueve puntos de vista políticos extremos o violencia.",
				"he": "תוכן המעודד דעות פוליטיות קיצוניות או אלימות.",
				"ar": "محتوى يروج لوجهات نظر سياسية متطرفة أو عنف.",
				"zh": "宣传极端政治观点或暴力的内容。",
				"ja": "過激な政治的見解や暴力を促進するコンテンツ。",
				"hi": "अत्यधिक राजनीतिक दृष्टिकोण या हिंसा को बढ़ावा देने वाली सामग्री।",
				"de": "Inhalte, die extreme politische Ansichten oder Gewalt fördern.",
				"th": "เนื้อหาที่ส่งเสริมมุมมองทางการเมืองสุดโต่งหรือความรุนแรง",
				"ru": "Контент, пропагандирующий экстремистские политические взгляды или насилие.",
				"pl": "Treści promujące ekstremalne poglądy polityczne lub przemoc.",
				"fr": "Contenu promouvant des vues politiques extrêmes ou la violence.",
				"pt": "Conteúdo que promove visões políticas extremas ou violência.",
				"id": "Konten yang mempromosikan pandangan politik ekstrem atau kekerasan.",
				"bn": "চরম রাজনৈতিক মতবাদ বা সহিংসতা প্রচারকারী বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindCulturalInsensitivity,
			DisplayOrder: 34,
			Name: utils.LocalizedString{
				"en": "Cultural Insensitivity", "tr": "Kültürel Duyarsızlık", "es": "Insensibilidad cultural", "he": "חוסר רגישות תרבותית", "ar": "عدم الحساسية الثقافية",
				"zh": "文化不敏感", "ja": "文化的な無神経", "hi": "सांस्कृतिक असंवेदनशीलता", "de": "Kulturelle Unsensibilität", "th": "ความไม่ไวต่อวัฒนธรรม",
				"ru": "Культурная нечувствительность", "pl": "Nietolerancja kulturowa", "fr": "Insensibilité culturelle", "pt": "Insensibilidade cultural", "id": "Ketidaksensitifan budaya", "bn": "সাংস্কৃতিক অসংবেদনশীলতা",
			},
			Description: utils.LocalizedString{
				"en": "Content disrespecting or offending cultural values or practices.",
				"tr": "Kültürel değerleri veya uygulamaları küçümseyen veya rahatsız eden içerik.",
				"es": "Contenido que falta al respeto o ofende valores o prácticas culturales.",
				"he": "תוכן שמכבד או פוגע בערכים או בפרקטיקות תרבותיות.",
				"ar": "محتوى يسيء الاحترام أو يسيء إلى القيم أو الممارسات الثقافية.",
				"zh": "不尊重或冒犯文化价值观或习俗的内容。",
				"ja": "文化的な価値観や慣習を軽視または侮辱するコンテンツ。",
				"hi": "सांस्कृतिक मूल्यों या प्रथाओं का अपमान या अपमान करने वाली सामग्री।",
				"de": "Inhalte, die kulturelle Werte oder Praktiken missachten oder beleidigen.",
				"th": "เนื้อหาที่ไม่เคารพหรือทำให้ค่านิยมทางวัฒนธรรมเสียหาย",
				"ru": "Контент, неуважительно относящийся к культурным ценностям или практикам.",
				"pl": "Treści lekceważące lub obrażające wartości lub praktyki kulturowe.",
				"fr": "Contenu manquant de respect ou offensant envers des valeurs ou pratiques culturelles.",
				"pt": "Conteúdo que desrespeita ou ofende valores ou práticas culturais.",
				"id": "Konten yang tidak menghormati atau menyinggung nilai atau praktik budaya.",
				"bn": "সংস্কৃতিক মূল্যবোধ বা অনুশীলনকে অবমাননা বা অপমান করার বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindIllegalActivities,
			DisplayOrder: 35,
			Name: utils.LocalizedString{
				"en": "Illegal Activities", "tr": "Yasadışı Faaliyetler", "es": "Actividades ilegales", "he": "פעילויות בלתי חוקיות", "ar": "أنشطة غير قانونية",
				"zh": "非法活动", "ja": "違法行為", "hi": "अवैध गतिविधियाँ", "de": "Illegale Aktivitäten", "th": "กิจกรรมที่ผิดกฎหมาย",
				"ru": "Незаконная деятельность", "pl": "Nielegalne działania", "fr": "Activités illégales", "pt": "Atividades ilegais", "id": "Kegiatan ilegal", "bn": "অবৈধ কার্যকলাপ",
			},
			Description: utils.LocalizedString{
				"en": "Content promoting or involving illegal actions.",
				"tr": "Yasadışı eylemleri teşvik eden veya içeren içerik.",
				"es": "Contenido que promueve o implica acciones ilegales.",
				"he": "תוכן המעודד או כולל פעולות בלתי חוקיות.",
				"ar": "محتوى يروج أو يشمل أفعالًا غير قانونية.",
				"zh": "宣传或涉及非法行为的内容。",
				"ja": "違法行為を促進または含むコンテンツ。",
				"hi": "अवैध कार्यों को बढ़ावा देने या शामिल करने वाली सामग्री।",
				"de": "Inhalte, die illegale Handlungen fördern oder beinhalten.",
				"th": "เนื้อหาที่ส่งเสริมหรือเกี่ยวข้องกับการกระทำที่ผิดกฎหมาย",
				"ru": "Контент, пропагандирующий или связанный с незаконными действиями.",
				"pl": "Treści promujące lub zawierające nielegalne działania.",
				"fr": "Contenu promouvant ou impliquant des actions illégales.",
				"pt": "Conteúdo que promove ou envolve ações ilegais.",
				"id": "Konten yang mempromosikan atau melibatkan tindakan ilegal.",
				"bn": "অবৈধ কার্যকলাপ প্রচার বা জড়িত বিষয়বস্তু।",
			},
		},
		{
			Key:          report.ReportKindCopyrightViolation,
			DisplayOrder: 36,
			Name: utils.LocalizedString{
				"en": "Copyright Violation", "tr": "Telif Hakkı İhlali", "es": "Violación de derechos de autor", "he": "הפרת זכויות יוצרים", "ar": "انتهاك حقوق النشر",
				"zh": "版权侵权", "ja": "著作権侵害", "hi": "कॉपीराइट उल्लंघन", "de": "Urheberrechtsverletzung", "th": "การละเมิดลิขสิทธิ์",
				"ru": "Нарушение авторских прав", "pl": "Naruszenie praw autorskich", "fr": "Violation du droit d'auteur", "pt": "Violação de direitos autorais", "id": "Pelanggaran hak cipta", "bn": "কপিরাইট লঙ্ঘন",
			},
			Description: utils.LocalizedString{
				"en": "Unauthorized use of copyrighted material.",
				"tr": "Telif hakkı koruması altındaki materyalin yetkisiz kullanımı.",
				"es": "Uso no autorizado de material con derechos de autor.",
				"he": "שימוש בלתי מורשה בחומר עם זכויות יוצרים.",
				"ar": "استخدام غير مصرح به للمواد المحمية بحقوق النشر.",
				"zh": "未经授权使用受版权保护的材料。",
				"ja": "著作権で保護された資料の無断使用。",
				"hi": "कॉपीराइट सामग्री का अनधिकृत उपयोग।",
				"de": "Unbefugte Nutzung von urheberrechtlich geschütztem Material.",
				"th": "การใช้วัสดุที่มีลิขสิทธิ์โดยไม่ได้รับอนุญาต",
				"ru": "Несанкционированное использование материалов с авторским правом.",
				"pl": "Nieautoryzowane użycie materiałów chronionych prawem autorskim.",
				"fr": "Utilisation non autorisée de matériel protégé par le droit d'auteur.",
				"pt": "Uso não autorizado de material protegido por direitos autorais.",
				"id": "Penggunaan materi berhak cipta tanpa izin.",
				"bn": "কপিরাইটকৃত সামগ্রীয়ের অননুমোদিত ব্যবহার।",
			},
		},
		{
			Key:          report.ReportKindOther,
			DisplayOrder: 37,
			Name: utils.LocalizedString{
				"en": "Other", "tr": "Diğer", "es": "Otro", "he": "אחר", "ar": "آخر",
				"zh": "其他", "ja": "その他", "hi": "अन्य", "de": "Andere", "th": "อื่น ๆ",
				"ru": "Другое", "pl": "Inne", "fr": "Autre", "pt": "Outro", "id": "Lainnya", "bn": "অন্যান্য",
			},
			Description: utils.LocalizedString{
				"en": "Other types of inappropriate content.",
				"tr": "Diğer uygunsuz içerik türleri.",
				"es": "Otros tipos de contenido inapropiado.",
				"he": "סוגים אחרים של תוכן בלתי מתאים.",
				"ar": "أنواع أخرى من المحتوى غير المناسب.",
				"zh": "其他类型的不当内容。",
				"ja": "その他の不適切なコンテンツの種類。",
				"hi": "अन्य प्रकार की अनुचित सामग्री।",
				"de": "Andere Arten unangemessener Inhalte.",
				"th": "ประเภทอื่น ๆ ของเนื้อหาไม่เหมาะสม",
				"ru": "Другие виды неподходящего контента.",
				"pl": "Inne rodzaje nieodpowiednich treści.",
				"fr": "Autres types de contenu inapproprié.",
				"pt": "Outros tipos de conteúdo inadequado.",
				"id": "Jenis konten tidak pantas lainnya.",
				"bn": "অন্যান্য ধরণের অনুপযুক্ত বিষয়বস্তু।",
			},
		},
	}
	for _, k := range kinds {
		db.Where(report.ReportKind{Key: k.Key}).Assign(k).FirstOrCreate(&k)
	}

	return nil
}
