package EventKinds

import (
	payloads "coolvibes/models/post/payloads"
	"coolvibes/models/utils"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedEventKinds(db *gorm.DB) error {
	eventKinds := []payloads.EventKind{
		{
			Kind:         payloads.EventKindPrideParade,
			DisplayOrder: 0,
			Name:         utils.LocalizedString{"en": "Pride Parade", "tr": "Onur Yürüyüşü", "es": "Desfile del Orgullo", "he": "מצעד הגאווה", "ar": "مسيرة الفخر", "zh": "骄傲游行", "ja": "プライドパレード", "hi": "प्राइड परेड", "de": "Pride-Parade", "th": "ขบวนพาเหรดไพรด์", "ru": "Парад гордости", "pl": "Parada Równości", "fr": "Marche des Fiertés", "pt": "Parada do Orgulho", "id": "Parade Kebanggaan", "bn": "প্রাইড প্যারেড"},
			Description:  utils.LocalizedString{"en": "A parade celebrating LGBTQ+ pride and community.", "tr": "LGBTQ+ onurunu ve topluluğunu kutlayan bir geçit töreni.", "es": "Un desfile que celebra el orgullo y la comunidad LGBTQ+.", "he": "מצעד החוגג את הגאווה והקהילה הגאה.", "ar": "مسيرة تحتفل بكرامة ومجتمع المثليين.", "zh": "庆祝 LGBTQ+ 骄傲和社区的游行。", "ja": "LGBTQ+ のプライドとコミュニティを祝うパレード。", "hi": "LGBTQ+ गौरव और समुदाय का जश्न मनाने वाली परेड।", "de": "Eine Parade zur Feier von LGBTQ+-Stolz und Gemeinschaft.", "th": "ขบวนพาเหรดเฉลิมฉลองความภาคภูมิใจและชุมชน LGBTQ+", "ru": "Парад, празднующий гордость и сообщество ЛГБТК+.", "pl": "Parada świętująca dumę i społeczność LGBTQ+.", "fr": "Un défilé célébrant la fierté et la communauté LGBTQ+.", "pt": "Um desfile celebrando o orgulho e a comunidade LGBTQ+.", "id": "Parade yang merayakan kebanggaan dan komunitas LGBTQ+.", "bn": "LGBTQ+ গর্ব এবং সম্প্রদায় উদযাপনকারী একটি প্যারেড।"},
		},
		{
			Kind:         payloads.EventKindLGBTQMeetup,
			DisplayOrder: 1,
			Name:         utils.LocalizedString{"en": "LGBTQ+ Meetup", "tr": "LGBTQ+ Buluşması", "es": "Reunión LGBTQ+", "he": "מפגש להט\"ב", "ar": "لقاء مجتمع الميم", "zh": "LGBTQ+ 聚会", "ja": "LGBTQ+ ミートアップ", "hi": "LGBTQ+ मिलन", "de": "LGBTQ+ Treffen", "th": "มีตติ้ง LGBTQ+", "ru": "Встреча ЛГБТК+", "pl": "Spotkanie LGBTQ+", "fr": "Rencontre LGBTQ+", "pt": "Encontro LGBTQ+", "id": "Pertemuan LGBTQ+", "bn": "LGBTQ+ সাক্ষাৎ"},
			Description:  utils.LocalizedString{"en": "A casual meetup for LGBTQ+ individuals and allies.", "tr": "LGBTQ+ bireyler ve müttefikler için gündelik bir buluşma.", "es": "Una reunión informal para personas LGBTQ+ y aliados.", "he": "מפגש קליל ללהט\"בים ובני ברית.", "ar": "لقاء غير رسمي للأفراد من مجتمع الميم والحلفاء.", "zh": "LGBTQ+ 个人和盟友的非正式聚会。", "ja": "LGBTQ+ の個人と同盟者のためのカジュアルな集まり。", "hi": "LGBTQ+ व्यक्तियों और सहयोगियों के लिए एक अनौपचारिक बैठक।", "de": "Ein lockeres Treffen für LGBTQ+-Personen und Verbündete.", "th": "การพบปะแบบสบายๆ สำหรับชาว LGBTQ+ และพันธมิตร", "ru": "Неформальная встреча для ЛГБТК+ людей и союзников.", "pl": "Luźne spotkanie dla osób LGBTQ+ i sojuszników.", "fr": "Une rencontre décontractée pour les personnes LGBTQ+ et leurs alliés.", "pt": "Um encontro casual para indivíduos LGBTQ+ e aliados.", "id": "Pertemuan santai untuk individu LGBTQ+ dan sekutu.", "bn": "LGBTQ+ ব্যক্তি এবং মিত্রদের জন্য একটি অনানুষ্ঠানিক সাক্ষাৎ।"},
		},
		{
			Kind:         payloads.EventKindSupportGroup,
			DisplayOrder: 2,
			Name:         utils.LocalizedString{"en": "Support Group", "tr": "Destek Grubu", "es": "Grupo de Apoyo", "he": "קבוצת תמיכה", "ar": "مجموعة دعم", "zh": "支持小组", "ja": "サポートグループ", "hi": "समर्थन समूह", "de": "Selbsthilfegruppe", "th": "กลุ่มสนับสนุน", "ru": "Группа поддержки", "pl": "Grupa Wsparcia", "fr": "Groupe de soutien", "pt": "Grupo de Apoio", "id": "Kelompok Pendukung", "bn": "সহায়তা গোষ্ঠী"},
			Description:  utils.LocalizedString{"en": "A gathering to provide emotional support and share experiences.", "tr": "Duygusal destek sağlamak ve deneyimleri paylaşmak için bir toplanma.", "es": "Una reunión para brindar apoyo emocional y compartir experiencias.", "he": "מפגש למתן תמיכה רגשית ושיתוף חוויות.", "ar": "تجمع لتقديم الدعم العاطفي وتبادل الخبرات.", "zh": "提供情感支持和分享经验的聚会。", "ja": "感情的なサポートを提供し、経験を共有するための集まり。", "hi": "भावनात्मक समर्थन प्रदान करने और अनुभव साझा करने के लिए एक सभा।", "de": "Ein Treffen, um emotionale Unterstützung zu bieten und Erfahrungen auszutauschen.", "th": "การรวมตัวเพื่อให้การสนับสนุนทางอารมณ์และแบ่งปันประสบการณ์", "ru": "Встреча для оказания эмоциональной поддержки и обмена опытом.", "pl": "Spotkanie w celu zapewnienia wsparcia emocjonalnego i wymiany doświadczeń.", "fr": "Un rassemblement pour apporter un soutien émotionnel et partager des expériences.", "pt": "Uma reunião para fornecer apoio emocional e compartilhar experiências.", "id": "Pertemuan untuk memberikan dukungan emosional dan berbagi pengalaman.", "bn": "মানসিক সমর্থন প্রদান এবং অভিজ্ঞতা ভাগ করার জন্য একটি সমাবেশ।"},
		},
		{
			Kind:         payloads.EventKindWorkshop,
			DisplayOrder: 3,
			Name:         utils.LocalizedString{"en": "Workshop", "tr": "Atölye", "es": "Taller", "he": "סדנה", "ar": "ورشة عمل", "zh": "研讨会", "ja": "ワークショップ", "hi": "कार्यशाला", "de": "Workshop", "th": "เวิร์กช็อป", "ru": "Мастер-класс", "pl": "Warsztaty", "fr": "Atelier", "pt": "Workshop", "id": "Lokakarya", "bn": "কর্মশালা"},
			Description:  utils.LocalizedString{"en": "Interactive sessions focusing on various LGBTQ+ topics.", "tr": "Çeşitli LGBTQ+ konularına odaklanan interaktif oturumlar.", "es": "Sesiones interactivas centradas en varios temas LGBTQ+.", "he": "מפגשים אינטראקטיביים המתמקדים בנושאים להט\"ביים שונים.", "ar": "جلسات تفاعلية تركز على مواضيع مختلفة لمجتمع الميم.", "zh": "专注于各种 LGBTQ+ 主题的互动会议。", "ja": "さまざまな LGBTQ+ トピックに焦点を当てたインタラクティブなセッション。", "hi": "विभिन्न LGBTQ+ विषयों पर केंद्रित इंटरैक्टिव सत्र।", "de": "Interaktive Sitzungen zu verschiedenen LGBTQ+-Themen.", "th": "เซสชันแบบโต้ตอบที่เน้นหัวข้อ LGBTQ+ ต่างๆ", "ru": "Интерактивные сессии, посвященные различным темам ЛГБТК+.", "pl": "Interaktywne sesje skupiające się na różnych tematach LGBTQ+.", "fr": "Séances interactives axées sur divers sujets LGBTQ+.", "pt": "Sessões interativas focadas em vários tópicos LGBTQ+.", "id": "Sesi interaktif yang berfokus pada berbagai topik LGBTQ+.", "bn": "বিভিন্ন LGBTQ+ বিষয়ের উপর দৃষ্টি নিবদ্ধ করে ইন্টারেক্টিভ সেশন।"},
		},
		{
			Kind:         payloads.EventKindPanelDiscussion,
			DisplayOrder: 4,
			Name:         utils.LocalizedString{"en": "Panel Discussion", "tr": "Panel Tartışması", "es": "Panel de Discusión", "he": "דיון פאנל", "ar": "حلقة نقاش", "zh": "小组讨论", "ja": "パネルディスカッション", "hi": "पैनल चर्चा", "de": "Podiumsdiskussion", "th": "การอภิปรายแบบคณะ", "ru": "Панельная дискуссия", "pl": "Dyskusja Panelowa", "fr": "Table ronde", "pt": "Painel de Discussão", "id": "Diskusi Panel", "bn": "প্যানেল আলোচনা"},
			Description:  utils.LocalizedString{"en": "A moderated discussion featuring experts on LGBTQ+ issues.", "tr": "LGBTQ+ konularında uzmanların yer aldığı moderatörlü bir tartışma.", "es": "Una discusión moderada con expertos en temas LGBTQ+.", "he": "דיון מונחה בהשתתפות מומחים לנושאי להט\"ב.", "ar": "مناقشة خاضعة للإشراف تضم خبراء في قضايا مجتمع الميم.", "zh": "由 LGBTQ+ 问题专家主持的讨论。", "ja": "LGBTQ+ 問題の専門家による司会付きの討論。", "hi": "LGBTQ+ मुद्दों पर विशेषज्ञों की विशेषता वाली एक संचालित चर्चा।", "de": "Eine moderierte Diskussion mit Experten zu LGBTQ+-Themen.", "th": "การอภิปรายที่มีผู้ดำเนินรายการโดยมีผู้เชี่ยวชาญในประเด็น LGBTQ+", "ru": "Модерируемая дискуссия с участием экспертов по вопросам ЛГБТК+.", "pl": "Moderowana dyskusja z udziałem ekspertów ds. problematyki LGBTQ+.", "fr": "Une discussion modérée avec des experts sur les questions LGBTQ+.", "pt": "Uma discussão moderada com especialistas em questões LGBTQ+.", "id": "Diskusi yang dimoderatori menampilkan para ahli tentang masalah LGBTQ+.", "bn": "LGBTQ+ বিষয়ে বিশেষজ্ঞদের সমন্বয়ে একটি পরিমিত আলোচনা।"},
		},
		{
			Kind:         payloads.EventKindWebinar,
			DisplayOrder: 5,
			Name:         utils.LocalizedString{"en": "Webinar", "tr": "Webinar", "es": "Seminario Web", "he": "וובינר", "ar": "ندوة عبر الإنترنت", "zh": "网络研讨会", "ja": "ウェビナー", "hi": "वेबिनार", "de": "Webinar", "th": "การสัมมนาผ่านเว็บ", "ru": "Вебинар", "pl": "Webinarium", "fr": "Webinaire", "pt": "Webinar", "id": "Webinar", "bn": "ওয়েবিনার"},
			Description:  utils.LocalizedString{"en": "An online seminar on relevant LGBTQ+ themes.", "tr": "İlgili LGBTQ+ temaları üzerine çevrimiçi bir seminer.", "es": "Un seminario en línea sobre temas LGBTQ+ relevantes.", "he": "סמינר מקוון בנושאים להט\"ביים רלוונטיים.", "ar": "ندوة عبر الإنترنت حول موضوعات ذات صلة بمجتمع الميم.", "zh": "关于相关 LGBTQ+ 主题的在线研讨会。", "ja": "関連する LGBTQ+ テーマに関するオンラインセミナー。", "hi": "प्रासंगिक LGBTQ+ विषयों पर एक ऑनलाइन सेमिनार।", "de": "Ein Online-Seminar zu relevanten LGBTQ+-Themen.", "th": "การสัมมนาออนไลน์ในหัวข้อ LGBTQ+ ที่เกี่ยวข้อง", "ru": "Онлайн-семинар на актуальные темы ЛГБТК+.", "pl": "Seminarium internetowe na temat odpowiednich tematów LGBTQ+.", "fr": "Un séminaire en ligne sur des thèmes LGBTQ+ pertinents.", "pt": "Um seminário online sobre temas LGBTQ+ relevantes.", "id": "Seminar online tentang tema LGBTQ+ yang relevan.", "bn": "প্রাসঙ্গিক LGBTQ+ থিমগুলির উপর একটি অনলাইন সেমিনার।"},
		},
		{
			Kind:         payloads.EventKindFilmScreening,
			DisplayOrder: 6,
			Name:         utils.LocalizedString{"en": "Film Screening", "tr": "Film Gösterimi", "es": "Proyección de Película", "he": "הקרנת סרט", "ar": "عرض فيلم", "zh": "电影放映", "ja": "映画上映", "hi": "फिल्म स्क्रीनिंग", "de": "Filmvorführung", "th": "การฉายภาพยนตร์", "ru": "Кинопоказ", "pl": "Pokaz Filmowy", "fr": "Projection de film", "pt": "Exibição de Filme", "id": "Pemutaran Film", "bn": "চলচ্চিত্র প্রদর্শনী"},
			Description:  utils.LocalizedString{"en": "Showing films with LGBTQ+ themes or creators.", "tr": "LGBTQ+ temalı veya yaratıcılı filmlerin gösterimi.", "es": "Proyección de películas con temas o creadores LGBTQ+.", "he": "הקרנת סרטים עם נושאים או יוצרים להט\"בים.", "ar": "عرض أفلام ذات مواضيع أو مبدعين من مجتمع الميم.", "zh": "放映具有 LGBTQ+ 主题或创作者的电影。", "ja": "LGBTQ+ のテーマやクリエイターによる映画の上映。", "hi": "LGBTQ+ थीम या रचनाकारों के साथ फिल्में दिखाना।", "de": "Zeigen von Filmen mit LGBTQ+-Themen oder -Machern.", "th": "การฉายภาพยนตร์ที่มีธีมหรือผู้สร้างเป็น LGBTQ+", "ru": "Показ фильмов с ЛГБТК+ тематикой или создателями.", "pl": "Pokazywanie filmów o tematyce LGBTQ+ lub twórców.", "fr": "Projection de films avec des thèmes ou des créateurs LGBTQ+.", "pt": "Exibição de filmes com temas ou criadores LGBTQ+.", "id": "Menayangkan film dengan tema atau pembuat LGBTQ+.", "bn": "LGBTQ+ থিম বা নির্মাতাদের সাথে চলচ্চিত্র প্রদর্শন।"},
		},
		{
			Kind:         payloads.EventKindArtExhibition,
			DisplayOrder: 7,
			Name:         utils.LocalizedString{"en": "Art Exhibition", "tr": "Sanat Sergisi", "es": "Exposición de Arte", "he": "תערוכת אמנות", "ar": "معرض فني", "zh": "艺术展览", "ja": "美術展", "hi": "कला प्रदर्शनी", "de": "Kunstausstellung", "th": "นิทรรศการศิลปะ", "ru": "Художественная выставка", "pl": "Wystawa Sztuki", "fr": "Exposition d'art", "pt": "Exposição de Arte", "id": "Pameran Seni", "bn": "শিল্প প্রদর্শনী"},
			Description:  utils.LocalizedString{"en": "An exhibit showcasing LGBTQ+ artists and their works.", "tr": "LGBTQ+ sanatçılarını ve eserlerini sergileyen bir sergi.", "es": "Una exhibición que muestra a artistas LGBTQ+ y sus obras.", "he": "תערוכה המציגה אמנים להט\"בים ואת יצירותיהם.", "ar": "معرض يعرض فنانين من مجتمع الميم وأعمالهم.", "zh": "展示 LGBTQ+ 艺术家及其作品的展览。", "ja": "LGBTQ+ アーティストとその作品を紹介する展示。", "hi": "LGBTQ+ कलाकारों और उनके कार्यों को प्रदर्शित करने वाली एक प्रदर्शनी।", "de": "Eine Ausstellung, die LGBTQ+-Künstler und ihre Werke präsentiert.", "th": "นิทรรศการแสดงผลงานศิลปิน LGBTQ+ และผลงานของพวกเขา", "ru": "Выставка, демонстрирующая ЛГБТК+ художников и их работы.", "pl": "Wystawa prezentująca artystów LGBTQ+ i ich prace.", "fr": "Une exposition présentant des artistes LGBTQ+ et leurs œuvres.", "pt": "Uma exposição mostrando artistas LGBTQ+ e suas obras.", "id": "Pameran yang menampilkan seniman LGBTQ+ dan karya mereka.", "bn": "LGBTQ+ শিল্পী এবং তাদের কাজ প্রদর্শনকারী একটি প্রদর্শনী।"},
		},
		{
			Kind:         payloads.EventKindFundraiser,
			DisplayOrder: 8,
			Name:         utils.LocalizedString{"en": "Fundraiser", "tr": "Bağış Toplama", "es": "Recaudación de Fondos", "he": "אירוע גיוס כספים", "ar": "جمع التبرعات", "zh": "筹款活动", "ja": "募金活動", "hi": "धन उगाहने का कार्यक्रम", "de": "Spendenaktion", "th": "การระดมทุน", "ru": "Сбор средств", "pl": "Zbiórka Pieniędzy", "fr": "Collecte de fonds", "pt": "Arrecadação de Fundos", "id": "Penggalangan Dana", "bn": "তহবিল সংগ্রহ"},
			Description:  utils.LocalizedString{"en": "An event to raise funds for LGBTQ+ causes.", "tr": "LGBTQ+ amaçları için fon toplamak amacıyla düzenlenen bir etkinlik.", "es": "Un evento para recaudar fondos para causas LGBTQ+.", "he": "אירוע לגיוס כספים למטרות להט\"ב.", "ar": "حدث لجمع الأموال لقضايا مجتمع الميم.", "zh": "为 LGBTQ+ 事业筹集资金的活动。", "ja": "LGBTQ+ のための資金を集めるイベント。", "hi": "LGBTQ+ कारणों के लिए धन जुटाने का एक कार्यक्रम।", "de": "Eine Veranstaltung, um Spenden für LGBTQ+-Zwecke zu sammeln.", "th": "กิจกรรมระดมทุนเพื่อสนับสนุนกิจกรรม LGBTQ+", "ru": "Мероприятие по сбору средств на нужды ЛГБТК+.", "pl": "Wydarzenie mające na celu zbiórkę funduszy na cele LGBTQ+.", "fr": "Un événement pour collecter des fonds pour des causes LGBTQ+.", "pt": "Um evento para arrecadar fundos para causas LGBTQ+.", "id": "Acara untuk menggalang dana bagi tujuan LGBTQ+.", "bn": "LGBTQ+ কারণগুলির জন্য তহবিল সংগ্রহের একটি ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindConference,
			DisplayOrder: 9,
			Name:         utils.LocalizedString{"en": "Conference", "tr": "Konferans", "es": "Conferencia", "he": "כנס", "ar": "مؤتمر", "zh": "会议", "ja": "会議", "hi": "सम्मेलन", "de": "Konferenz", "th": "การประชุม", "ru": "Конференция", "pl": "Konferencja", "fr": "Conférence", "pt": "Conferência", "id": "Konferensi", "bn": "সম্মেলন"},
			Description:  utils.LocalizedString{"en": "A large gathering for discussions, networking, and presentations.", "tr": "Tartışmalar, ağ oluşturma ve sunumlar için büyük bir toplanma.", "es": "Una gran reunión para discusiones, networking y presentaciones.", "he": "מפגש גדול לדיונים, נטוורקינג ומצגות.", "ar": "تجمع كبير للمناقشات والتواصل والعروض التقديمية.", "zh": "用于讨论、交流和演讲的大型聚会。", "ja": "議論、ネットワーキング、プレゼンテーションのための大規模な集まり。", "hi": "चर्चा, नेटवर्किंग और प्रस्तुतियों के लिए एक बड़ा जमावड़ा।", "de": "Ein großes Treffen für Diskussionen, Networking und Präsentationen.", "th": "การรวมตัวขนาดใหญ่เพื่อการหารือ การสร้างเครือข่าย และการนำเสนอ", "ru": "Крупное собрание для дискуссий, нетворкинга и презентаций.", "pl": "Duże zgromadzenie w celu dyskusji, networkingu i prezentacji.", "fr": "Un grand rassemblement pour des discussions, du réseautage et des présentations.", "pt": "Uma grande reunião para discussões, networking e apresentações.", "id": "Pertemuan besar untuk diskusi, jejaring, dan presentasi.", "bn": "আলোচনা, নেটওয়ার্কিং এবং উপস্থাপনার জন্য একটি বড় সমাবেশ।"},
		},
		{
			Kind:         payloads.EventKindParty,
			DisplayOrder: 10,
			Name:         utils.LocalizedString{"en": "Party", "tr": "Parti", "es": "Fiesta", "he": "מסיבה", "ar": "حفلة", "zh": "派对", "ja": "パーティー", "hi": "पार्टी", "de": "Party", "th": "ปาร์ตี้", "ru": "Вечеринка", "pl": "Impreza", "fr": "Fête", "pt": "Festa", "id": "Pesta", "bn": "পার্টি"},
			Description:  utils.LocalizedString{"en": "A social event for celebration and community bonding.", "tr": "Kutlama ve topluluk bağları için sosyal bir etkinlik.", "es": "Un evento social para celebración y unión comunitaria.", "he": "אירוע חברתי לחגיגה וגיבוש הקהילה.", "ar": "حدث اجتماعي للاحتفال وترابط المجتمع.", "zh": "用于庆祝和社区联系的社交活动。", "ja": "お祝いとコミュニティの絆のためのソーシャルイベント。", "hi": "उत्सव और सामुदायिक बंधन के लिए एक सामाजिक कार्यक्रम।", "de": "Ein gesellschaftliches Ereignis zum Feiern und zur Stärkung der Gemeinschaft.", "th": "กิจกรรมทางสังคมเพื่อการเฉลิมฉลองและความผูกพันในชุมชน", "ru": "Социальное мероприятие для празднования и сплочения сообщества.", "pl": "Wydarzenie towarzyskie służące świętowaniu i integracji społeczności.", "fr": "Un événement social pour la célébration et le lien communautaire.", "pt": "Um evento social para celebração e união da comunidade.", "id": "Acara sosial untuk perayaan dan ikatan komunitas.", "bn": "উদযাপন এবং সম্প্রদায়ের বন্ধনের জন্য একটি সামাজিক ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindAwarenessCampaign,
			DisplayOrder: 11,
			Name:         utils.LocalizedString{"en": "Awareness Campaign", "tr": "Farkındalık Kampanyası", "es": "Campaña de Concientización", "he": "קמפיין מודעות", "ar": "حملة توعية", "zh": "意识活动", "ja": "啓発キャンペーン", "hi": "जागरूकता अभियान", "de": "Aufklärungskampagne", "th": "รณรงค์สร้างความตระหนัก", "ru": "Информационная кампания", "pl": "Kampania świadomości", "fr": "Campagne de sensibilisation", "pt": "Campanha de Conscientização", "id": "Kampanye Kesadaran", "bn": "সচেতনতা অভিযান"},
			Description:  utils.LocalizedString{"en": "Activities aimed at raising awareness on LGBTQ+ issues.", "tr": "LGBTQ+ sorunları hakkında farkındalık yaratmayı amaçlayan etkinlikler.", "es": "Actividades destinadas a crear conciencia sobre temas LGBTQ+.", "he": "פעילויות שמטרתן להעלות את המודעות לנושאי להט\"ב.", "ar": "أنشطة تهدف إلى رفع الوعي حول قضايا مجتمع الميم.", "zh": "旨在提高对 LGBTQ+ 问题的认识的活动。", "ja": "LGBTQ+ 問題への意識を高めることを目的とした活動。", "hi": "LGBTQ+ मुद्दों पर जागरूकता बढ़ाने के उद्देश्य से गतिविधियाँ।", "de": "Aktivitäten zur Sensibilisierung für LGBTQ+-Themen.", "th": "กิจกรรมที่มุ่งสร้างความตระหนักในประเด็น LGBTQ+", "ru": "Деятельность, направленная на повышение осведомленности о проблемах ЛГБТК+.", "pl": "Działania mające na celu podniesienie świadomości na temat problemów LGBTQ+.", "fr": "Activités visant à sensibiliser aux questions LGBTQ+.", "pt": "Atividades destinadas a aumentar a conscientização sobre questões LGBTQ+.", "id": "Kegiatan yang bertujuan untuk meningkatkan kesadaran tentang masalah LGBTQ+.", "bn": "LGBTQ+ বিষয়ে সচেতনতা বাড়ানোর লক্ষ্যে কার্যক্রম।"},
		},
		{
			Kind:         payloads.EventKindVolunteering,
			DisplayOrder: 12,
			Name:         utils.LocalizedString{"en": "Volunteering", "tr": "Gönüllülük", "es": "Voluntariado", "he": "התנדבות", "ar": "العمل التطوعي", "zh": "志愿服务", "ja": "ボランティア", "hi": "स्वयंसेवा", "de": "Freiwilligenarbeit", "th": "อาสาสมัคร", "ru": "Волонтерство", "pl": "Wolontariat", "fr": "Bénévolat", "pt": "Voluntariado", "id": "Sukarelawan", "bn": "স্বেচ্ছাসেবী"},
			Description:  utils.LocalizedString{"en": "Opportunities to volunteer for LGBTQ+ organizations.", "tr": "LGBTQ+ kuruluşları için gönüllü olma fırsatları.", "es": "Oportunidades para ser voluntario en organizaciones LGBTQ+.", "he": "הזדמנויות להתנדב בארגוני להט\"ב.", "ar": "فرص للتطوع لمنظمات مجتمع الميم.", "zh": "为 LGBTQ+ 组织做志愿者的机会。", "ja": "LGBTQ+ 団体でボランティアをする機会。", "hi": "LGBTQ+ संगठनों के लिए स्वयंसेवा करने के अवसर।", "de": "Möglichkeiten zur Freiwilligenarbeit für LGBTQ+-Organisationen.", "th": "โอกาสในการเป็นอาสาสมัครให้กับองค์กร LGBTQ+", "ru": "Возможности волонтерства в ЛГБТК+ организациях.", "pl": "Możliwości wolontariatu w organizacjach LGBTQ+.", "fr": "Possibilités de faire du bénévolat pour des organisations LGBTQ+.", "pt": "Oportunidades de voluntariado para organizações LGBTQ+.", "id": "Peluang menjadi sukarelawan untuk organisasi LGBTQ+.", "bn": "LGBTQ+ সংস্থাগুলির জন্য স্বেচ্ছাসেবক হওয়ার সুযোগ।"},
		},
		{
			Kind:         payloads.EventKindMarch,
			DisplayOrder: 13,
			Name:         utils.LocalizedString{"en": "March", "tr": "Yürüyüş", "es": "Marcha", "he": "צעדה", "ar": "مسيرة", "zh": "游行", "ja": "行進", "hi": "जुलूस", "de": "Marsch", "th": "การเดินขบวน", "ru": "Марш", "pl": "Marsz", "fr": "Marche", "pt": "Marcha", "id": "Pawai", "bn": "মার্চ"},
			Description:  utils.LocalizedString{"en": "A public march or demonstration for LGBTQ+ rights.", "tr": "LGBTQ+ hakları için halka açık bir yürüyüş veya gösteri.", "es": "Una marcha o manifestación pública por los derechos LGBTQ+.", "he": "צעדה או הפגנה פומבית למען זכויות להט\"ב.", "ar": "مسيرة عامة أو مظاهرة من أجل حقوق مجتمع الميم.", "zh": "争取 LGBTQ+ 权利的公开游行或示威。", "ja": "LGBTQ+ の権利のための公的な行進またはデモ。", "hi": "LGBTQ+ अधिकारों के लिए एक सार्वजनिक मार्च या प्रदर्शन।", "de": "Ein öffentlicher Marsch oder eine Demonstration für LGBTQ+-Rechte.", "th": "การเดินขบวนสาธารณะหรือการสาธิตเพื่อสิทธิ LGBTQ+", "ru": "Публичный марш или демонстрация за права ЛГБТК+.", "pl": "Publiczny marsz lub demonstracja na rzecz praw LGBTQ+.", "fr": "Une marche ou manifestation publique pour les droits LGBTQ+.", "pt": "Uma marcha pública ou manifestação pelos direitos LGBTQ+.", "id": "Pawai umum atau demonstrasi untuk hak-hak LGBTQ+.", "bn": "LGBTQ+ অধিকারের জন্য একটি পাবলিক মার্চ বা বিক্ষোভ।"},
		},
		{
			Kind:         payloads.EventKindNetworkingEvent,
			DisplayOrder: 14,
			Name:         utils.LocalizedString{"en": "Networking Event", "tr": "Ağ Oluşturma Etkinliği", "es": "Evento de Networking", "he": "אירוע נטוורקינג", "ar": "حدث تواصل", "zh": "社交活动", "ja": "ネットワーキングイベント", "hi": "नेटवर्किंग कार्यक्रम", "de": "Networking-Event", "th": "กิจกรรมสร้างเครือข่าย", "ru": "Нетворкинг", "pl": "Wydarzenie networkingowe", "fr": "Événement de réseautage", "pt": "Evento de Networking", "id": "Acara Jejaring", "bn": "নেটওয়ার্কিং ইভেন্ট"},
			Description:  utils.LocalizedString{"en": "An event to meet and connect with others in the LGBTQ+ community.", "tr": "LGBTQ+ topluluğundaki diğer kişilerle tanışmak ve bağlantı kurmak için bir etkinlik.", "es": "Un evento para conocer y conectar con otros en la comunidad LGBTQ+.", "he": "אירוע למפגש וחיבור עם אחרים בקהילה הגאה.", "ar": "حدث للالتقاء والتواصل مع الآخرين في مجتمع الميم.", "zh": "与 LGBTQ+ 社区中其他人见面和联系的活动。", "ja": "LGBTQ+ コミュニティの他の人々と出会い、つながるためのイベント。", "hi": "LGBTQ+ समुदाय में दूसरों से मिलने और जुड़ने का एक कार्यक्रम।", "de": "Eine Veranstaltung, um andere in der LGBTQ+-Community zu treffen und sich zu vernetzen.", "th": "กิจกรรมเพื่อพบปะและเชื่อมต่อกับผู้อื่นในชุมชน LGBTQ+", "ru": "Мероприятие для знакомства и общения с другими людьми в ЛГБТК+ сообществе.", "pl": "Wydarzenie mające na celu spotkanie i nawiązanie kontaktu z innymi osobami ze społeczności LGBTQ+.", "fr": "Un événement pour rencontrer et se connecter avec d'autres membres de la communauté LGBTQ+.", "pt": "Um evento para conhecer e se conectar com outras pessoas na comunidade LGBTQ+.", "id": "Acara untuk bertemu dan terhubung dengan orang lain di komunitas LGBTQ+.", "bn": "LGBTQ+ সম্প্রদায়ের অন্যদের সাথে দেখা করার এবং সংযোগ করার একটি ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindBookClub,
			DisplayOrder: 15,
			Name:         utils.LocalizedString{"en": "Book Club", "tr": "Kitap Kulübü", "es": "Club de Lectura", "he": "מועדון קריאה", "ar": "نادي الكتاب", "zh": "读书俱乐部", "ja": "ブッククラブ", "hi": "बुक क्लब", "de": "Buchclub", "th": "ชมรมหนังสือ", "ru": "Книжный клуб", "pl": "Klub książki", "fr": "Club de lecture", "pt": "Clube do Livro", "id": "Klub Buku", "bn": "বুক ক্লাব"},
			Description:  utils.LocalizedString{"en": "A group reading and discussing LGBTQ+ related literature.", "tr": "LGBTQ+ ile ilgili literatürü okuyan ve tartışan bir grup.", "es": "Un grupo que lee y discute literatura relacionada con LGBTQ+.", "he": "קבוצה הקוראת ודנה בספרות הקשורה ללהט\"ב.", "ar": "مجموعة تقرأ وتناقش الأدب المتعلق بمجتمع الميم.", "zh": "阅读和讨论 LGBTQ+ 相关文学的小组。", "ja": "LGBTQ+ 関連の文学を読み、議論するグループ。", "hi": "LGBTQ+ संबंधित साहित्य पढ़ने और चर्चा करने वाला एक समूह।", "de": "Eine Gruppe, die LGBTQ+-bezogene Literatur liest und diskutiert.", "th": "กลุ่มที่อ่านและอภิปรายวรรณกรรมที่เกี่ยวข้องกับ LGBTQ+", "ru": "Группа, читающая и обсуждающая литературу, связанную с ЛГБТК+.", "pl": "Grupa czytająca i dyskutująca o literaturze związanej z LGBTQ+.", "fr": "Un groupe lisant et discutant de littérature liée aux LGBTQ+.", "pt": "Um grupo lendo e discutindo literatura relacionada a LGBTQ+.", "id": "Kelompok yang membaca dan mendiskusikan literatur terkait LGBTQ+.", "bn": "LGBTQ+ সম্পর্কিত সাহিত্য পড়া এবং আলোচনা করা একটি দল।"},
		},
		{
			Kind:         payloads.EventKindYogaSession,
			DisplayOrder: 16,
			Name:         utils.LocalizedString{"en": "Yoga Session", "tr": "Yoga Seansı", "es": "Sesión de Yoga", "he": "מפגש יוגה", "ar": "جلسة يوغا", "zh": "瑜伽课程", "ja": "ヨガセッション", "hi": "योग सत्र", "de": "Yoga-Sitzung", "th": "เซสชั่นโยคะ", "ru": "Занятие йогой", "pl": "Sesja jogi", "fr": "Séance de yoga", "pt": "Sessão de Ioga", "id": "Sesi Yoga", "bn": "যোগব্যায়াম সেশন"},
			Description:  utils.LocalizedString{"en": "A relaxing yoga class inclusive for LGBTQ+ participants.", "tr": "LGBTQ+ katılımcıları için kapsayıcı, rahatlatıcı bir yoga dersi.", "es": "Una clase de yoga relajante e inclusiva para participantes LGBTQ+.", "he": "שיעור יוגה מרגיע המיועד למשתתפים להט\"בים.", "ar": "درس يوغا مريح وشامل للمشاركين من مجتمع الميم.", "zh": "面向 LGBTQ+ 参与者的包容性放松瑜伽课。", "ja": "LGBTQ+ 参加者を受け入れるリラックスできるヨガクラス。", "hi": "LGBTQ+ प्रतिभागियों के लिए समावेशी एक आरामदायक योग कक्षा।", "de": "Eine entspannende Yoga-Stunde, die für LGBTQ+-Teilnehmer inklusiv ist.", "th": "ชั้นเรียนโยคะที่ผ่อนคลายซึ่งครอบคลุมสำหรับผู้เข้าร่วม LGBTQ+", "ru": "Расслабляющее занятие йогой, инклюзивное для ЛГБТК+ участников.", "pl": "Relaksujące zajęcia jogi integracyjne dla uczestników LGBTQ+.", "fr": "Un cours de yoga relaxant et inclusif pour les participants LGBTQ+.", "pt": "Uma aula de ioga relaxante e inclusiva para participantes LGBTQ+.", "id": "Kelas yoga santai yang inklusif bagi peserta LGBTQ+.", "bn": "LGBTQ+ অংশগ্রহণকারীদের জন্য অন্তর্ভুক্ত একটি আরামদায়ক যোগ ক্লাস।"},
		},
		{
			Kind:         payloads.EventKindHealthCheckup,
			DisplayOrder: 17,
			Name:         utils.LocalizedString{"en": "Health Checkup", "tr": "Sağlık Kontrolü", "es": "Chequeo Médico", "he": "בדיקה רפואית", "ar": "فحص صحي", "zh": "健康检查", "ja": "健康診断", "hi": "स्वास्थ्य जांच", "de": "Gesundheitscheck", "th": "ตรวจสุขภาพ", "ru": "Медосмотр", "pl": "Badanie lekarskie", "fr": "Bilan de santé", "pt": "Check-up de Saúde", "id": "Pemeriksaan Kesehatan", "bn": "স্বাস্থ্য পরীক্ষা"},
			Description:  utils.LocalizedString{"en": "Medical checkups focusing on LGBTQ+ health needs.", "tr": "LGBTQ+ sağlık ihtiyaçlarına odaklanan tıbbi kontroller.", "es": "Chequeos médicos centrados en las necesidades de salud LGBTQ+.", "he": "בדיקות רפואיות המתמקדות בצרכי הבריאות של הקהילה הגאה.", "ar": "فحوصات طبية تركز على الاحتياجات الصحية لمجتمع الميم.", "zh": "专注于 LGBTQ+ 健康需求的体检。", "ja": "LGBTQ+ の健康ニーズに焦点を当てた健康診断。", "hi": "LGBTQ+ स्वास्थ्य आवश्यकताओं पर केंद्रित चिकित्सा जांच।", "de": "Medizinische Untersuchungen mit Schwerpunkt auf LGBTQ+-Gesundheitsbedürfnissen.", "th": "การตรวจสุขภาพที่เน้นความต้องการด้านสุขภาพของ LGBTQ+", "ru": "Медицинские осмотры, ориентированные на потребности здоровья ЛГБТК+.", "pl": "Badania lekarskie koncentrujące się na potrzebach zdrowotnych LGBTQ+.", "fr": "Des bilans de santé axés sur les besoins de santé des LGBTQ+.", "pt": "Exames médicos focados nas necessidades de saúde LGBTQ+.", "id": "Pemeriksaan medis yang berfokus pada kebutuhan kesehatan LGBTQ+.", "bn": "LGBTQ+ স্বাস্থ্যের প্রয়োজনের উপর দৃষ্টি নিবদ্ধ করে মেডিকেল চেকআপ।"},
		},
		{
			Kind:         payloads.EventKindDragShow,
			DisplayOrder: 18,
			Name:         utils.LocalizedString{"en": "Drag Show", "tr": "Drag Şovu", "es": "Espectáculo de Drag", "he": "מופע דראג", "ar": "عرض دراغ", "zh": "变装秀", "ja": "ドラァグショー", "hi": "ड्रैग शो", "de": "Drag-Show", "th": "แดร็กโชว์", "ru": "Дрэг-шоу", "pl": "Drag Show", "fr": "Spectacle de drag", "pt": "Show de Drag", "id": "Pertunjukan Drag", "bn": "ড্র্যাগ শো"},
			Description:  utils.LocalizedString{"en": "A performance event featuring drag artists.", "tr": "Drag sanatçılarının yer aldığı bir performans etkinliği.", "es": "Un evento de actuación con artistas drag.", "he": "אירוע הופעות בהשתתפות אמני דראג.", "ar": "حدث أدائي يضم فناني الدراغ.", "zh": "以变装艺术家为特色的表演活动。", "ja": "ドラァグアーティストをフィーチャーしたパフォーマンスイベント。", "hi": "ड्रैग कलाकारों की विशेषता वाला एक प्रदर्शन कार्यक्रम।", "de": "Eine Performance-Veranstaltung mit Drag-Künstlern.", "th": "กิจกรรมการแสดงที่มีศิลปินแดร็ก", "ru": "Представление с участием дрэг-артистов.", "pl": "Wydarzenie artystyczne z udziałem artystów drag.", "fr": "Un événement de performance mettant en vedette des artistes drag.", "pt": "Um evento de performance com artistas drag.", "id": "Acara pertunjukan yang menampilkan seniman drag.", "bn": "ড্র্যাগ শিল্পীদের সমন্বিত একটি পারফরম্যান্স ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindMusicConcert,
			DisplayOrder: 19,
			Name:         utils.LocalizedString{"en": "Music Concert", "tr": "Müzik Konseri", "es": "Concierto de Música", "he": "קונצרט מוזיקה", "ar": "حفل موسيقي", "zh": "音乐会", "ja": "音楽コンサート", "hi": "संगीत कार्यक्रम", "de": "Musikkonzert", "th": "คอนเสิร์ตดนตรี", "ru": "Музыкальный концерт", "pl": "Koncert muzyczny", "fr": "Concert de musique", "pt": "Concerto de Música", "id": "Konser Musik", "bn": "সঙ্গীত কনসার্ট"},
			Description:  utils.LocalizedString{"en": "Live music performances by LGBTQ+ artists or allies.", "tr": "LGBTQ+ sanatçıları veya müttefikleri tarafından canlı müzik performansları.", "es": "Actuaciones de música en vivo por artistas LGBTQ+ o aliados.", "he": "הופעות מוזיקה חיה של אמנים להט\"בים או בני ברית.", "ar": "عروض موسيقية حية لفنانين من مجتمع الميم أو حلفاء.", "zh": "LGBTQ+ 艺术家或盟友的现场音乐表演。", "ja": "LGBTQ+ アーティストまたは同盟者によるライブ音楽パフォーマンス。", "hi": "LGBTQ+ कलाकारों या सहयोगियों द्वारा लाइव संगीत प्रदर्शन।", "de": "Live-Musikauftritte von LGBTQ+-Künstlern oder Verbündeten.", "th": "การแสดงดนตรีสดโดยศิลปิน LGBTQ+ หรือพันธมิตร", "ru": "Живые музыкальные выступления ЛГБТК+ артистов или союзников.", "pl": "Występy muzyczne na żywo artystów LGBTQ+ lub sojuszników.", "fr": "Performances musicales en direct par des artistes LGBTQ+ ou des alliés.", "pt": "Apresentações de música ao vivo por artistas LGBTQ+ ou aliados.", "id": "Pertunjukan musik langsung oleh seniman atau sekutu LGBTQ+.", "bn": "LGBTQ+ শিল্পী বা সহযোগীদের দ্বারা লাইভ সঙ্গীত পরিবেশন।"},
		},
		{
			Kind:         payloads.EventKindDanceParty,
			DisplayOrder: 20,
			Name:         utils.LocalizedString{"en": "Dance Party", "tr": "Dans Partisi", "es": "Fiesta de Baile", "he": "מסיבת ריקודים", "ar": "حفلة رقص", "zh": "舞会", "ja": "ダンスパーティー", "hi": "नृत्य पार्टी", "de": "Tanzparty", "th": "ปาร์ตี้เต้นรำ", "ru": "Танцевальная вечеринка", "pl": "Impreza taneczna", "fr": "Soirée dansante", "pt": "Festa de Dança", "id": "Pesta Dansa", "bn": "নাচ পার্টি"},
			Description:  utils.LocalizedString{"en": "A party centered around dancing and socializing.", "tr": "Dans ve sosyalleşme odaklı bir parti.", "es": "Una fiesta centrada en bailar y socializar.", "he": "מסיבה המתמקדת בריקודים וחיברות.", "ar": "حفلة تتمحور حول الرقص والتواصل الاجتماعي.", "zh": "以跳舞和社交为中心的聚会。", "ja": "ダンスと交流を中心としたパーティー。", "hi": "नाचने और मेलजोल पर केंद्रित एक पार्टी।", "de": "Eine Party, bei der Tanzen und geselliges Beisammensein im Mittelpunkt stehen.", "th": "ปาร์ตี้ที่มีศูนย์กลางอยู่ที่การเต้นรำและการเข้าสังคม", "ru": "Вечеринка, посвященная танцам и общению.", "pl": "Impreza skupiona na tańcu i towarzystwie.", "fr": "Une fête centrée sur la danse et la socialisation.", "pt": "Uma festa centrada na dança e na socialização.", "id": "Pesta yang berpusat pada menari dan bersosialisasi.", "bn": "নাচ এবং সামাজিকীকরণের চারপাশে কেন্দ্র করে একটি পার্টি।"},
		},
		{
			Kind:         payloads.EventKindFundingPitch,
			DisplayOrder: 21,
			Name:         utils.LocalizedString{"en": "Funding Pitch", "tr": "Yatırım Sunumu", "es": "Presentación de Financiación", "he": "פיץ' גיוס כספים", "ar": "عرض تمويل", "zh": "融资推介", "ja": "資金調達ピッチ", "hi": "फंडिंग पिच", "de": "Finanzierungs-Pitch", "th": "การนำเสนอเพื่อขอทุน", "ru": "Питч финансирования", "pl": "Prezentacja finansowania", "fr": "Présentation de financement", "pt": "Pitch de Financiamento", "id": "Presentasi Pendanaan", "bn": "তহবিল পিচ"},
			Description:  utils.LocalizedString{"en": "Presentations aimed at securing funding for LGBTQ+ projects.", "tr": "LGBTQ+ projeleri için finansman sağlamayı amaçlayan sunumlar.", "es": "Presentaciones destinadas a asegurar financiación para proyectos LGBTQ+.", "he": "מצגות שמטרתן להבטיח מימון לפרויקטים של הקהילה הגאה.", "ar": "عروض تهدف إلى تأمين التمويل لمشاريع مجتمع الميم.", "zh": "旨在为 LGBTQ+ 项目争取资金的演示。", "ja": "LGBTQ+ プロジェクトの資金確保を目的としたプレゼンテーション。", "hi": "LGBTQ+ परियोजनाओं के लिए धन सुरक्षित करने के उद्देश्य से प्रस्तुतियाँ।", "de": "Präsentationen zur Sicherung der Finanzierung von LGBTQ+-Projekten.", "th": "การนำเสนอที่มีเป้าหมายเพื่อระดมทุนสำหรับโครงการ LGBTQ+", "ru": "Презентации, направленные на получение финансирования для ЛГБТК+ проектов.", "pl": "Prezentacje mające na celu pozyskanie finansowania na projekty LGBTQ+.", "fr": "Présentations visant à obtenir des financements pour des projets LGBTQ+.", "pt": "Apresentações destinadas a garantir financiamento para projetos LGBTQ+.", "id": "Presentasi yang ditujukan untuk mendapatkan pendanaan bagi proyek LGBTQ+.", "bn": "LGBTQ+ প্রকল্পগুলির জন্য তহবিল সুরক্ষিত করার লক্ষ্যে উপস্থাপনা।"},
		},
		{
			Kind:         payloads.EventKindCommunityFestival,
			DisplayOrder: 22,
			Name:         utils.LocalizedString{"en": "Community Festival", "tr": "Topluluk Festivali", "es": "Festival Comunitario", "he": "פסטיבל קהילתי", "ar": "مهرجان مجتمعي", "zh": "社区节日", "ja": "コミュニティフェスティバル", "hi": "सामुदायिक महोत्सव", "de": "Gemeindefest", "th": "เทศกาลชุมชน", "ru": "Фестиваль сообщества", "pl": "Festiwal społeczności", "fr": "Festival communautaire", "pt": "Festival Comunitário", "id": "Festival Komunitas", "bn": "কমিউনিটি ফেস্টিভ্যাল"},
			Description:  utils.LocalizedString{"en": "A festival celebrating LGBTQ+ culture and community.", "tr": "LGBTQ+ kültürünü ve topluluğunu kutlayan bir festival.", "es": "Un festival que celebra la cultura y la comunidad LGBTQ+.", "he": "פסטיבל החוגג את התרבות והקהילה הגאה.", "ar": "مهرجان يحتفل بثقافة ومجتمع الميم.", "zh": "庆祝 LGBTQ+ 文化和社区的节日。", "ja": "LGBTQ+ 文化とコミュニティを祝うフェスティバル。", "hi": "LGBTQ+ संस्कृति और समुदाय का जश्न मनाने वाला त्योहार।", "de": "Ein Festival zur Feier der LGBTQ+-Kultur und -Gemeinschaft.", "th": "เทศกาลเฉลิมฉลองวัฒนธรรมและชุมชน LGBTQ+", "ru": "Фестиваль, прославляющий культуру и сообщество ЛГБТК+.", "pl": "Festiwal celebrujący kulturę i społeczność LGBTQ+.", "fr": "Un festival célébrant la culture et la communauté LGBTQ+.", "pt": "Um festival celebrando a cultura e a comunidade LGBTQ+.", "id": "Festival yang merayakan budaya dan komunitas LGBTQ+.", "bn": "LGBTQ+ সংস্কৃতি এবং সম্প্রদায় উদযাপনকারী একটি উৎসব।"},
		},
		{
			Kind:         payloads.EventKindTraining,
			DisplayOrder: 23,
			Name:         utils.LocalizedString{"en": "Training", "tr": "Eğitim", "es": "Capacitación", "he": "הכשרה", "ar": "تدريب", "zh": "培训", "ja": "トレーニング", "hi": "प्रशिक्षण", "de": "Schulung", "th": "การฝึกอบรม", "ru": "Тренинг", "pl": "Szkolenie", "fr": "Formation", "pt": "Treinamento", "id": "Pelatihan", "bn": "প্রশিক্ষণ"},
			Description:  utils.LocalizedString{"en": "Educational sessions aimed at building skills or awareness.", "tr": "Beceri veya farkındalık oluşturmayı amaçlayan eğitim oturumları.", "es": "Sesiones educativas destinadas a desarrollar habilidades o conciencia.", "he": "מפגשים חינוכיים שמטרתם לבנות מיומנויות או מודעות.", "ar": "جلسات تعليمية تهدف إلى بناء المهارات أو الوعي.", "zh": "旨在建立技能或意识的教育会议。", "ja": "スキルや意識の向上を目的とした教育セッション。", "hi": "कौशल या जागरूकता के निर्माण के उद्देश्य से शैक्षिक सत्र।", "de": "Bildungsveranstaltungen zum Aufbau von Fähigkeiten oder Bewusstsein.", "th": "เซสชันการศึกษาที่มุ่งเป้าไปที่การสร้างทักษะหรือความตระหนัก", "ru": "Образовательные сессии, направленные на развитие навыков или осведомленности.", "pl": "Sesje edukacyjne mające na celu budowanie umiejętności lub świadomości.", "fr": "Sessions éducatives visant à renforcer les compétences ou la sensibilisation.", "pt": "Sessões educacionais destinadas a desenvolver habilidades ou conscientização.", "id": "Sesi pendidikan yang ditujukan untuk membangun keterampilan atau kesadaran.", "bn": "দক্ষতা বা সচেতনতা তৈরির লক্ষ্যে শিক্ষামূলক সেশন।"},
		},
		{
			Kind:         payloads.EventKindDebate,
			DisplayOrder: 24,
			Name:         utils.LocalizedString{"en": "Debate", "tr": "Münazara", "es": "Debate", "he": "עימות", "ar": "مناظرة", "zh": "辩论", "ja": "討論", "hi": "बहस", "de": "Debatte", "th": "การโต้วาที", "ru": "Дебаты", "pl": "Debata", "fr": "Débat", "pt": "Debate", "id": "Debat", "bn": "বিতর্ক"},
			Description:  utils.LocalizedString{"en": "A formal discussion on LGBTQ+ related topics.", "tr": "LGBTQ+ ile ilgili konularda resmi bir tartışma.", "es": "Una discusión formal sobre temas relacionados con LGBTQ+.", "he": "דיון רשמי בנושאים הקשורים ללהט\"ב.", "ar": "مناقشة رسمية حول المواضيع المتعلقة بمجتمع الميم.", "zh": "关于 LGBTQ+ 相关话题的正式讨论。", "ja": "LGBTQ+ 関連トピックに関する正式な議論。", "hi": "LGBTQ+ संबंधित विषयों पर एक औपचारिक चर्चा।", "de": "Eine formelle Diskussion zu LGBTQ+-bezogenen Themen.", "th": "การอภิปรายอย่างเป็นทางการในหัวข้อที่เกี่ยวข้องกับ LGBTQ+", "ru": "Формальная дискуссия на темы, связанные с ЛГБТК+.", "pl": "Formalna dyskusja na tematy związane z LGBTQ+.", "fr": "Une discussion formelle sur des sujets liés aux LGBTQ+.", "pt": "Uma discussão formal sobre tópicos relacionados a LGBTQ+.", "id": "Diskusi formal tentang topik terkait LGBTQ+.", "bn": "LGBTQ+ সম্পর্কিত বিষয়ে একটি আনুষ্ঠানিক আলোচনা।"},
		},
		{
			Kind:         payloads.EventKindMovieNight,
			DisplayOrder: 25,
			Name:         utils.LocalizedString{"en": "Movie Night", "tr": "Film Gecesi", "es": "Noche de Cine", "he": "ערב סרט", "ar": "ليلة سينمائية", "zh": "电影之夜", "ja": "ムービーナイト", "hi": "मूवी नाइट", "de": "Filmabend", "th": "คืนดูหนัง", "ru": "Киновечер", "pl": "Noc filmowa", "fr": "Soirée cinéma", "pt": "Noite de Cinema", "id": "Malam Film", "bn": "মুভি নাইট"},
			Description:  utils.LocalizedString{"en": "Screening of LGBTQ+ themed movies for a community audience.", "tr": "Topluluk izleyicileri için LGBTQ+ temalı filmlerin gösterimi.", "es": "Proyección de películas con temática LGBTQ+ para una audiencia comunitaria.", "he": "הקרנת סרטים בנושא להט\"ב לקהל הקהילה.", "ar": "عرض أفلام ذات طابع مجتمع الميم لجمهور المجتمع.", "zh": "为社区观众放映 LGBTQ+ 主题电影。", "ja": "コミュニティの観客向けの LGBTQ+ テーマの映画の上映。", "hi": "सामुदायिक दर्शकों के लिए LGBTQ+ थीम्ड फिल्मों की स्क्रीनिंग।", "de": "Vorführung von Filmen mit LGBTQ+-Thematik für ein Gemeinschaftspublikum.", "th": "การฉายภาพยนตร์ธีม LGBTQ+ สำหรับผู้ชมในชุมชน", "ru": "Показ фильмов на тему ЛГБТК+ для сообщества.", "pl": "Pokaz filmów o tematyce LGBTQ+ dla publiczności społecznościowej.", "fr": "Projection de films sur le thème LGBTQ+ pour un public communautaire.", "pt": "Exibição de filmes com temática LGBTQ+ para um público comunitário.", "id": "Pemutaran film bertema LGBTQ+ untuk audiens komunitas.", "bn": "সম্প্রদায়ের দর্শকদের জন্য LGBTQ+ থিমযুক্ত সিনেমার প্রদর্শনী।"},
		},
		{
			Kind:         payloads.EventKindSupportCounseling,
			DisplayOrder: 26,
			Name:         utils.LocalizedString{"en": "Support Counseling", "tr": "Destek Danışmanlığı", "es": "Consejería de Apoyo", "he": "ייעוץ תמיכה", "ar": "استشارات الدعم", "zh": "支持咨询", "ja": "サポートカウンセリング", "hi": "समर्थन परामर्श", "de": "Unterstützende Beratung", "th": "การให้คำปรึกษาสนับสนุน", "ru": "Консультация поддержки", "pl": "Poradnictwo wspierające", "fr": "Conseil de soutien", "pt": "Aconselhamento de Apoio", "id": "Konseling Dukungan", "bn": "সমর্থন কাউন্সেলিং"},
			Description:  utils.LocalizedString{"en": "Counseling sessions to support LGBTQ+ individuals.", "tr": "LGBTQ+ bireyleri desteklemek için danışmanlık seansları.", "es": "Sesiones de consejería para apoyar a personas LGBTQ+.", "he": "מפגשי ייעוץ לתמיכה ביחידים להט\"בים.", "ar": "جلسات استشارية لدعم الأفراد من مجتمع الميم.", "zh": "支持 LGBTQ+ 个人的咨询会议。", "ja": "LGBTQ+ の個人をサポートするためのカウンセリングセッション。", "hi": "LGBTQ+ व्यक्तियों का समर्थन करने के लिए परामर्श सत्र।", "de": "Beratungssitzungen zur Unterstützung von LGBTQ+-Personen.", "th": "เซสชันการให้คำปรึกษาเพื่อสนับสนุนบุคคล LGBTQ+", "ru": "Консультации для поддержки ЛГБТК+ людей.", "pl": "Sesje doradcze wspierające osoby LGBTQ+.", "fr": "Séances de conseil pour soutenir les personnes LGBTQ+.", "pt": "Sessões de aconselhamento para apoiar indivíduos LGBTQ+.", "id": "Sesi konseling untuk mendukung individu LGBTQ+.", "bn": "LGBTQ+ ব্যক্তিদের সমর্থন করার জন্য কাউন্সেলিং সেশন।"},
		},
		{
			Kind:         payloads.EventKindYouthOutreach,
			DisplayOrder: 27,
			Name:         utils.LocalizedString{"en": "Youth Outreach", "tr": "Gençlik Sosyal Yardımı", "es": "Alcance Juvenil", "he": "הסברה לנוער", "ar": "التوعية الشبابية", "zh": "青年外展", "ja": "若者支援", "hi": "युवा आउटरीच", "de": "Jugendarbeit", "th": "การเข้าถึงเยาวชน", "ru": "Работа с молодежью", "pl": "Wsparcie młodzieży", "fr": "Sensibilisation des jeunes", "pt": "Alcance Juvenil", "id": "Jangkauan Pemuda", "bn": "যুব আউটরিচ"},
			Description:  utils.LocalizedString{"en": "Programs targeting support and engagement of LGBTQ+ youth.", "tr": "LGBTQ+ gençlerinin desteğini ve katılımını hedefleyen programlar.", "es": "Programas dirigidos al apoyo y la participación de jóvenes LGBTQ+.", "he": "תוכניות המיועדות לתמיכה ומעורבות של נוער להט\"ב.", "ar": "برامج تستهدف دعم وإشراك شباب مجتمع الميم.", "zh": "旨在支持和让 LGBTQ+ 青年参与的计划。", "ja": "LGBTQ+ の若者の支援と関与を目的としたプログラム。", "hi": "LGBTQ+ युवाओं के समर्थन और जुड़ाव को लक्षित करने वाले कार्यक्रम।", "de": "Programme, die auf die Unterstützung und Einbindung von LGBTQ+-Jugendlichen abzielen.", "th": "โปรแกรมที่มุ่งเป้าไปที่การสนับสนุนและการมีส่วนร่วมของเยาวชน LGBTQ+", "ru": "Программы, направленные на поддержку и вовлечение ЛГБТК+ молодежи.", "pl": "Programy ukierunkowane na wsparcie i zaangażowanie młodzieży LGBTQ+.", "fr": "Programmes ciblant le soutien et l'engagement des jeunes LGBTQ+.", "pt": "Programas visando o apoio e engajamento de jovens LGBTQ+.", "id": "Program yang menargetkan dukungan dan keterlibatan pemuda LGBTQ+.", "bn": "LGBTQ+ যুবকদের সমর্থন এবং ব্যস্ততাকে লক্ষ্য করে প্রোগ্রামগুলি।"},
		},
		{
			Kind:         payloads.EventKindMentalHealthForum,
			DisplayOrder: 28,
			Name:         utils.LocalizedString{"en": "Mental Health Forum", "tr": "Ruh Sağlığı Forumu", "es": "Foro de Salud Mental", "he": "פורום בריאות הנפש", "ar": "منتدى الصحة العقلية", "zh": "心理健康论坛", "ja": "メンタルヘルスフォーラム", "hi": "मानसिक स्वास्थ्य मंच", "de": "Forum für psychische Gesundheit", "th": "ฟอรัมสุขภาพจิต", "ru": "Форум психического здоровья", "pl": "Forum zdrowia psychicznego", "fr": "Forum sur la santé mentale", "pt": "Fórum de Saúde Mental", "id": "Forum Kesehatan Mental", "bn": "মানসিক স্বাস্থ্য ফোরাম"},
			Description:  utils.LocalizedString{"en": "Discussions and resources about mental health in LGBTQ+ communities.", "tr": "LGBTQ+ topluluklarında ruh sağlığı hakkında tartışmalar ve kaynaklar.", "es": "Discusiones y recursos sobre salud mental en comunidades LGBTQ+.", "he": "דיונים ומשאבים בנושא בריאות הנפש בקהילות להט\"ב.", "ar": "مناقشات وموارد حول الصحة العقلية في مجتمعات الميم.", "zh": "关于 LGBTQ+ 社区心理健康的讨论和资源。", "ja": "LGBTQ+ コミュニティにおけるメンタルヘルスに関する議論とリソース。", "hi": "LGBTQ+ समुदायों में मानसिक स्वास्थ्य के बारे में चर्चा और संसाधन।", "de": "Diskussionen und Ressourcen zur psychischen Gesundheit in LGBTQ+-Gemeinschaften.", "th": "การอภิปรายและทรัพยากรเกี่ยวกับสุขภาพจิตในชุมชน LGBTQ+", "ru": "Дискуссии и ресурсы о психическом здоровье в ЛГБТК+ сообществах.", "pl": "Dyskusje i zasoby dotyczące zdrowia psychicznego w społecznościach LGBTQ+.", "fr": "Discussions et ressources sur la santé mentale dans les communautés LGBTQ+.", "pt": "Discussões e recursos sobre saúde mental em comunidades LGBTQ+.", "id": "Diskusi dan sumber daya tentang kesehatan mental di komunitas LGBTQ+.", "bn": "LGBTQ+ সম্প্রদায়ের মানসিক স্বাস্থ্য সম্পর্কে আলোচনা এবং সম্পদ।"},
		},
		{
			Kind:         payloads.EventKindTransgenderRights,
			DisplayOrder: 29,
			Name:         utils.LocalizedString{"en": "Transgender Rights", "tr": "Trans Hakları", "es": "Derechos Transgénero", "he": "זכויות טרנסג'נדרים", "ar": "حقوق المتحولين جنسياً", "zh": "跨性别权利", "ja": "トランスジェンダーの権利", "hi": "ट्रांसजेंडर अधिकार", "de": "Transgender-Rechte", "th": "สิทธิคนข้ามเพศ", "ru": "Права трансгендеров", "pl": "Prawa osób transpłciowych", "fr": "Droits des transgenres", "pt": "Direitos Transgêneros", "id": "Hak Transgender", "bn": "ট্রান্সজেন্ডার অধিকার"},
			Description:  utils.LocalizedString{"en": "Events focused on rights and issues affecting transgender people.", "tr": "Trans bireyleri etkileyen haklara ve sorunlara odaklanan etkinlikler.", "es": "Eventos centrados en los derechos y problemas que afectan a las personas transgénero.", "he": "אירועים המתמקדים בזכויות וסוגיות המשפיעות על אנשים טרנסג'נדרים.", "ar": "أحداث تركز على الحقوق والقضايا التي تؤثر على المتحولين جنسياً.", "zh": "关注影响跨性别者的权利和问题的活动。", "ja": "トランスジェンダーの人々に影響を与える権利と問題に焦点を当てたイベント。", "hi": "ट्रांसजेंडर लोगों को प्रभावित करने वाले अधिकारों और मुद्दों पर केंद्रित कार्यक्रम।", "de": "Veranstaltungen, die sich auf Rechte und Probleme konzentrieren, die Transgender-Personen betreffen.", "th": "กิจกรรมที่เน้นเรื่องสิทธิและปัญหาที่ส่งผลกระทบต่อคนข้ามเพศ", "ru": "Мероприятия, посвященные правам и проблемам, затрагивающим трансгендеров.", "pl": "Wydarzenia koncentrujące się na prawach i problemach dotyczących osób transpłciowych.", "fr": "Événements axés sur les droits et les problèmes affectant les personnes transgenres.", "pt": "Eventos focados em direitos e questões que afetam pessoas transgênero.", "id": "Acara yang berfokus pada hak dan masalah yang memengaruhi orang transgender.", "bn": "ট্রান্সজেন্ডার ব্যক্তিদের প্রভাবিত করে এমন অধিকার এবং সমস্যাগুলির উপর দৃষ্টি নিবদ্ধ করা ইভেন্টগুলি।"},
		},
		{
			Kind:         payloads.EventKindQueerHistoryTalk,
			DisplayOrder: 30,
			Name:         utils.LocalizedString{"en": "Queer History Talk", "tr": "Queer Tarihi Konuşması", "es": "Charla de Historia Queer", "he": "הרצאה על היסטוריה קווירית", "ar": "حديث عن التاريخ الكويري", "zh": "酷儿历史讲座", "ja": "クィアヒストリートーク", "hi": "क्वीर इतिहास वार्ता", "de": "Vortrag über queere Geschichte", "th": "การพูดคุยประวัติศาสตร์เควียร์", "ru": "Лекция по квир-истории", "pl": "Rozmowa o historii queer", "fr": "Conférence sur l'histoire queer", "pt": "Palestra sobre História Queer", "id": "Bicara Sejarah Queer", "bn": "কুইর হিস্ট্রি টক"},
			Description:  utils.LocalizedString{"en": "Lectures or discussions about LGBTQ+ history.", "tr": "LGBTQ+ tarihi hakkında dersler veya tartışmalar.", "es": "Conferencias o discusiones sobre la historia LGBTQ+.", "he": "הרצאות או דיונים על היסטוריה להט\"בית.", "ar": "محاضرات أو مناقشات حول تاريخ مجتمع الميم.", "zh": "关于 LGBTQ+ 历史的讲座或讨论。", "ja": "LGBTQ+ の歴史に関する講義や議論。", "hi": "LGBTQ+ इतिहास के बारे में व्याख्यान या चर्चा।", "de": "Vorträge oder Diskussionen über LGBTQ+-Geschichte.", "th": "การบรรยายหรือการอภิปรายเกี่ยวกับประวัติศาสตร์ LGBTQ+", "ru": "Лекции или дискуссии об истории ЛГБТК+.", "pl": "Wykłady lub dyskusje na temat historii LGBTQ+.", "fr": "Conférences ou discussions sur l'histoire LGBTQ+.", "pt": "Palestras ou discussões sobre a história LGBTQ+.", "id": "Kuliah atau diskusi tentang sejarah LGBTQ+.", "bn": "LGBTQ+ ইতিহাস সম্পর্কে বক্তৃতা বা আলোচনা।"},
		},
		{
			Kind:         payloads.EventKindAllyTraining,
			DisplayOrder: 31,
			Name:         utils.LocalizedString{"en": "Ally Training", "tr": "Müttefik Eğitimi", "es": "Entrenamiento para Aliados", "he": "הכשרת בני ברית", "ar": "تدريب الحلفاء", "zh": "盟友培训", "ja": "アライトレーニング", "hi": "सहयोगी प्रशिक्षण", "de": "Ally-Training", "th": "การฝึกอบรมพันธมิตร", "ru": "Тренинг для союзников", "pl": "Szkolenie sojuszników", "fr": "Formation des alliés", "pt": "Treinamento de Aliados", "id": "Pelatihan Sekutu", "bn": "মিত্র প্রশিক্ষণ"},
			Description:  utils.LocalizedString{"en": "Training sessions for allies supporting LGBTQ+ people.", "tr": "LGBTQ+ bireyleri destekleyen müttefikler için eğitim oturumları.", "es": "Sesiones de capacitación para aliados que apoyan a personas LGBTQ+.", "he": "מפגשי הכשרה לבני ברית התומכים באנשים להט\"בים.", "ar": "جلسات تدريبية للحلفاء الداعمين للأشخاص من مجتمع الميم.", "zh": "为支持 LGBTQ+ 人群的盟友提供的培训课程。", "ja": "LGBTQ+ の人々を支援する同盟者のためのトレーニングセッション。", "hi": "LGBTQ+ लोगों का समर्थन करने वाले सहयोगियों के लिए प्रशिक्षण सत्र।", "de": "Schulungen für Verbündete, die LGBTQ+-Personen unterstützen.", "th": "การฝึกอบรมสำหรับพันธมิตรที่สนับสนุนผู้คน LGBTQ+", "ru": "Тренинги для союзников, поддерживающих ЛГБТК+ людей.", "pl": "Sesje szkoleniowe dla sojuszników wspierających osoby LGBTQ+.", "fr": "Sessions de formation pour les alliés soutenant les personnes LGBTQ+.", "pt": "Sessões de treinamento para aliados que apoiam pessoas LGBTQ+.", "id": "Sesi pelatihan untuk sekutu yang mendukung orang LGBTQ+.", "bn": "LGBTQ+ লোকেদের সমর্থনকারী মিত্রদের জন্য প্রশিক্ষণ সেশন।"},
		},
		{
			Kind:         payloads.EventKindFamilySupport,
			DisplayOrder: 32,
			Name:         utils.LocalizedString{"en": "Family Support", "tr": "Aile Desteği", "es": "Apoyo Familiar", "he": "תמיכה משפחתית", "ar": "دعم الأسرة", "zh": "家庭支持", "ja": "家族支援", "hi": "पारिवारिक समर्थन", "de": "Familienunterstützung", "th": "การสนับสนุนครอบครัว", "ru": "Семейная поддержка", "pl": "Wsparcie rodziny", "fr": "Soutien familial", "pt": "Apoio Familiar", "id": "Dukungan Keluarga", "bn": "পারিবারিক সহায়তা"},
			Description:  utils.LocalizedString{"en": "Programs aimed at supporting families of LGBTQ+ individuals.", "tr": "LGBTQ+ bireylerin ailelerini desteklemeyi amaçlayan programlar.", "es": "Programas dirigidos a apoyar a las familias de personas LGBTQ+.", "he": "תוכניות שמטרתן לתמוך במשפחות של יחידים להט\"בים.", "ar": "برامج تهدف إلى دعم عائلات الأفراد من مجتمع الميم.", "zh": "旨在支持 LGBTQ+ 个人家庭的计划。", "ja": "LGBTQ+ の個人の家族を支援することを目的としたプログラム。", "hi": "LGBTQ+ व्यक्तियों के परिवारों का समर्थन करने के उद्देश्य से कार्यक्रम।", "de": "Programme zur Unterstützung von Familien von LGBTQ+-Personen.", "th": "โปรแกรมที่มุ่งเป้าไปที่การสนับสนุนครอบครัวของบุคคล LGBTQ+", "ru": "Программы, направленные на поддержку семей ЛГБТК+ людей.", "pl": "Programy mające na celu wsparcie rodzin osób LGBTQ+.", "fr": "Programmes visant à soutenir les familles des personnes LGBTQ+.", "pt": "Programas destinados a apoiar famílias de indivíduos LGBTQ+.", "id": "Program yang bertujuan mendukung keluarga individu LGBTQ+.", "bn": "LGBTQ+ ব্যক্তিদের পরিবারকে সমর্থন করার লক্ষ্যে প্রোগ্রামগুলি।"},
		},
		{
			Kind:         payloads.EventKindCulturalCelebration,
			DisplayOrder: 33,
			Name:         utils.LocalizedString{"en": "Cultural Celebration", "tr": "Kültürel Kutlama", "es": "Celebración Cultural", "he": "חגיגה תרבותית", "ar": "احتفال ثقافي", "zh": "文化庆典", "ja": "文化的なお祝い", "hi": "सांस्कृतिक उत्सव", "de": "Kulturelle Feier", "th": "การเฉลิมฉลองทางวัฒนธรรม", "ru": "Культурный праздник", "pl": "Święto kultury", "fr": "Célébration culturelle", "pt": "Celebração Cultural", "id": "Perayaan Budaya", "bn": "সাংস্কৃতিক উদযাপন"},
			Description:  utils.LocalizedString{"en": "Events celebrating diverse LGBTQ+ cultures.", "tr": "Çeşitli LGBTQ+ kültürlerini kutlayan etkinlikler.", "es": "Eventos que celebran diversas culturas LGBTQ+.", "he": "אירועים החוגגים תרבויות להט\"ב מגוונות.", "ar": "أحداث تحتفل بثقافات مجتمع الميم المتنوعة.", "zh": "庆祝多元 LGBTQ+ 文化的活动。", "ja": "多様な LGBTQ+ 文化を祝うイベント。", "hi": "विभिन्न LGBTQ+ संस्कृतियों का जश्न मनाने वाले कार्यक्रम।", "de": "Veranstaltungen zur Feier verschiedener LGBTQ+-Kulturen.", "th": "กิจกรรมเฉลิมฉลองวัฒนธรรม LGBTQ+ ที่หลากหลาย", "ru": "Мероприятия, прославляющие разнообразные культуры ЛГБТК+.", "pl": "Wydarzenia celebrujące różnorodne kultury LGBTQ+.", "fr": "Événements célébrant diverses cultures LGBTQ+.", "pt": "Eventos celebrando diversas culturas LGBTQ+.", "id": "Acara yang merayakan beragam budaya LGBTQ+.", "bn": "বিচিত্র LGBTQ+ সংস্কৃতি উদযাপন করা ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindHIVAwareness,
			DisplayOrder: 34,
			Name:         utils.LocalizedString{"en": "HIV Awareness", "tr": "HIV Farkındalığı", "es": "Concientización sobre el VIH", "he": "מודעות ל-HIV", "ar": "التوعية بفيروس نقص المناعة البشرية", "zh": "艾滋病毒意识", "ja": "HIV啓発", "hi": "एचआईवी जागरूकता", "de": "HIV-Aufklärung", "th": "ความตระหนักรู้เรื่องเอชไอวี", "ru": "Осведомленность о ВИЧ", "pl": "Świadomość HIV", "fr": "Sensibilisation au VIH", "pt": "Conscientização sobre o HIV", "id": "Kesadaran HIV", "bn": "এইচআইভি সচেতনতা"},
			Description:  utils.LocalizedString{"en": "Events raising awareness about HIV and related issues.", "tr": "HIV ve ilgili konular hakkında farkındalık yaratan etkinlikler.", "es": "Eventos para crear conciencia sobre el VIH y temas relacionados.", "he": "אירועים להעלאת המודעות ל-HIV ונושאים קשורים.", "ar": "أحداث ترفع الوعي حول فيروس نقص المناعة البشرية والقضايا ذات الصلة.", "zh": "提高对艾滋病毒及相关问题认识的活动。", "ja": "HIV と関連する問題についての意識を高めるイベント。", "hi": "एचआईवी और संबंधित मुद्दों के बारे में जागरूकता बढ़ाने वाले कार्यक्रम।", "de": "Veranstaltungen zur Sensibilisierung für HIV und damit verbundene Themen.", "th": "กิจกรรมสร้างความตระหนักรู้เกี่ยวกับเอชไอวีและประเด็นที่เกี่ยวข้อง", "ru": "Мероприятия по повышению осведомленности о ВИЧ и связанных с ним проблемах.", "pl": "Wydarzenia podnoszące świadomość na temat HIV i powiązanych problemów.", "fr": "Événements de sensibilisation au VIH et aux problèmes connexes.", "pt": "Eventos aumentando a conscientização sobre o HIV e questões relacionadas.", "id": "Acara meningkatkan kesadaran tentang HIV dan masalah terkait.", "bn": "এইচআইভি এবং সম্পর্কিত বিষয় সম্পর্কে সচেতনতা বৃদ্ধি ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindHIVTesting,
			DisplayOrder: 35,
			Name:         utils.LocalizedString{"en": "HIV Testing", "tr": "HIV Testi", "es": "Prueba de VIH", "he": "בדיקת HIV", "ar": "فحص فيروس نقص المناعة البشرية", "zh": "艾滋病毒检测", "ja": "HIV検査", "hi": "एचआईवी परीक्षण", "de": "HIV-Test", "th": "การตรวจเอชไอวี", "ru": "Тестирование на ВИЧ", "pl": "Testowanie na HIV", "fr": "Dépistage du VIH", "pt": "Teste de HIV", "id": "Tes HIV", "bn": "এইচআইভি পরীক্ষা"},
			Description:  utils.LocalizedString{"en": "Events providing HIV testing services.", "tr": "HIV testi hizmetleri sunan etkinlikler.", "es": "Eventos que brindan servicios de prueba de VIH.", "he": "אירועים המספקים שירותי בדיקת HIV.", "ar": "أحداث تقدم خدمات فحص فيروس نقص المناعة البشرية.", "zh": "提供艾滋病毒检测服务的活动。", "ja": "HIV 検査サービスを提供するイベント。", "hi": "एचआईवी परीक्षण सेवाएं प्रदान करने वाले कार्यक्रम।", "de": "Veranstaltungen, die HIV-Testdienste anbieten.", "th": "กิจกรรมให้บริการตรวจเอชไอวี", "ru": "Мероприятия, предоставляющие услуги тестирования на ВИЧ.", "pl": "Wydarzenia oferujące usługi testowania na HIV.", "fr": "Événements proposant des services de dépistage du VIH.", "pt": "Eventos fornecendo serviços de teste de HIV.", "id": "Acara yang menyediakan layanan tes HIV.", "bn": "এইচআইভি পরীক্ষা পরিষেবা প্রদানকারী ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindHIVSupportGroup,
			DisplayOrder: 36,
			Name:         utils.LocalizedString{"en": "HIV Support Group", "tr": "HIV Destek Grubu", "es": "Grupo de Apoyo VIH", "he": "קבוצת תמיכה ל-HIV", "ar": "مجموعة دعم فيروس نقص المناعة البشرية", "zh": "艾滋病毒支持小组", "ja": "HIVサポートグループ", "hi": "एचआईवी सहायता समूह", "de": "HIV-Selbsthilfegruppe", "th": "กลุ่มสนับสนุนเอชไอวี", "ru": "Группа поддержки ВИЧ", "pl": "Grupa wsparcia HIV", "fr": "Groupe de soutien VIH", "pt": "Grupo de Apoio HIV", "id": "Kelompok Dukungan HIV", "bn": "এইচআইভি সহায়তা গ্রুপ"},
			Description:  utils.LocalizedString{"en": "Support groups for people living with HIV.", "tr": "HIV ile yaşayan insanlar için destek grupları.", "es": "Grupos de apoyo para personas que viven con el VIH.", "he": "קבוצות תמיכה לאנשים החיים עם HIV.", "ar": "مجموعات دعم للأشخاص المتعايشين مع فيروس نقص المناعة البشرية.", "zh": "为艾滋病毒感染者提供的支持小组。", "ja": "HIV と共に生きる人々のためのサポートグループ。", "hi": "एचआईवी के साथ रहने वाले लोगों के लिए सहायता समूह।", "de": "Selbsthilfegruppen für Menschen, die mit HIV leben.", "th": "กลุ่มสนับสนุนสำหรับผู้ติดเชื้อเอชไอวี", "ru": "Группы поддержки для людей, живущих с ВИЧ.", "pl": "Grupy wsparcia dla osób żyjących z HIV.", "fr": "Groupes de soutien pour les personnes vivant avec le VIH.", "pt": "Grupos de apoio para pessoas vivendo com HIV.", "id": "Kelompok dukungan bagi orang yang hidup dengan HIV.", "bn": "এইচআইভি নিয়ে বসবাসকারী মানুষের জন্য সহায়তা গোষ্ঠী।"},
		},
		{
			Kind:         payloads.EventKindHIVPrevention,
			DisplayOrder: 37,
			Name:         utils.LocalizedString{"en": "HIV Prevention", "tr": "HIV Önleme", "es": "Prevención del VIH", "he": "מניעת HIV", "ar": "الوقاية من فيروس نقص المناعة البشرية", "zh": "艾滋病毒预防", "ja": "HIV予防", "hi": "एचआईवी रोकथाम", "de": "HIV-Prävention", "th": "การป้องกันเอชไอวี", "ru": "Профилактика ВИЧ", "pl": "Profilaktyka HIV", "fr": "Prévention du VIH", "pt": "Prevenção do HIV", "id": "Pencegahan HIV", "bn": "এইচআইভি প্রতিরোধ"},
			Description:  utils.LocalizedString{"en": "Programs focused on preventing HIV transmission.", "tr": "HIV bulaşmasını önlemeye odaklanan programlar.", "es": "Programas enfocados en prevenir la transmisión del VIH.", "he": "תוכניות המתמקדות במניעת העברת HIV.", "ar": "برامج تركز على منع انتقال فيروس نقص المناعة البشرية.", "zh": "专注于预防艾滋病毒传播的计划。", "ja": "HIV 感染の予防に焦点を当てたプログラム。", "hi": "एचआईवी संचरण को रोकने पर केंद्रित कार्यक्रम।", "de": "Programme zur Verhinderung der HIV-Übertragung.", "th": "โปรแกรมที่เน้นการป้องกันการแพร่เชื้อเอชไอวี", "ru": "Программы, направленные на предотвращение передачи ВИЧ.", "pl": "Programy koncentrujące się na zapobieganiu transmisji HIV.", "fr": "Programmes axés sur la prévention de la transmission du VIH.", "pt": "Programas focados na prevenção da transmissão do HIV.", "id": "Program yang berfokus pada pencegahan penularan HIV.", "bn": "এইচআইভি সংক্রমণ প্রতিরোধের উপর দৃষ্টি নিবদ্ধ করা প্রোগ্রাম।"},
		},
		{
			Kind:         payloads.EventKindHIVTreatmentInfo,
			DisplayOrder: 38,
			Name:         utils.LocalizedString{"en": "HIV Treatment Info", "tr": "HIV Tedavi Bilgisi", "es": "Info Tratamiento VIH", "he": "מידע על טיפול ב-HIV", "ar": "معلومات علاج فيروس نقص المناعة البشرية", "zh": "艾滋病毒治疗信息", "ja": "HIV治療情報", "hi": "एचआईवी उपचार जानकारी", "de": "HIV-Behandlungsinformationen", "th": "ข้อมูลการรักษาเอชไอวี", "ru": "Информация о лечении ВИЧ", "pl": "Informacje o leczeniu HIV", "fr": "Infos traitement VIH", "pt": "Informações sobre Tratamento HIV", "id": "Info Pengobatan HIV", "bn": "এইচআইভি চিকিত্সা তথ্য"},
			Description:  utils.LocalizedString{"en": "Information sessions on HIV treatments.", "tr": "HIV tedavileri üzerine bilgilendirme oturumları.", "es": "Sesiones informativas sobre tratamientos del VIH.", "he": "מפגשי מידע על טיפולי HIV.", "ar": "جلسات معلومات حول علاجات فيروس نقص المناعة البشرية.", "zh": "关于艾滋病毒治疗的信息会议。", "ja": "HIV 治療に関する情報セッション。", "hi": "एचआईवी उपचार पर सूचना सत्र।", "de": "Informationsveranstaltungen zu HIV-Behandlungen.", "th": "เซสชันข้อมูลเกี่ยวกับการรักษาเอชไอวี", "ru": "Информационные сессии по лечению ВИЧ.", "pl": "Sesje informacyjne na temat leczenia HIV.", "fr": "Sessions d'information sur les traitements du VIH.", "pt": "Sessões de informação sobre tratamentos de HIV.", "id": "Sesi informasi tentang pengobatan HIV.", "bn": "এইচআইভি চিকিত্সা সম্পর্কে তথ্য সেশন।"},
		},
		{
			Kind:         payloads.EventKindSexualHealthClinic,
			DisplayOrder: 39,
			Name:         utils.LocalizedString{"en": "Sexual Health Clinic", "tr": "Cinsel Sağlık Kliniği", "es": "Clínica de Salud Sexual", "he": "מרפאת בריאות מינית", "ar": "عيادة الصحة الجنسية", "zh": "性健康诊所", "ja": "性保健クリニック", "hi": "यौन स्वास्थ्य क्लिनिक", "de": "Klinik für sexuelle Gesundheit", "th": "คลินิกสุขภาพทางเพศ", "ru": "Клиника сексуального здоровья", "pl": "Klinika zdrowia seksualnego", "fr": "Clinique de santé sexuelle", "pt": "Clínica de Saúde Sexual", "id": "Klinik Kesehatan Seksual", "bn": "যৌন স্বাস্থ্য ক্লিনিক"},
			Description:  utils.LocalizedString{"en": "Clinics providing sexual health services.", "tr": "Cinsel sağlık hizmetleri sunan klinikler.", "es": "Clínicas que brindan servicios de salud sexual.", "he": "מרפאות המספקות שירותי בריאות מינית.", "ar": "عيادات تقدم خدمات الصحة الجنسية.", "zh": "提供性健康服务的诊所。", "ja": "性的健康サービスを提供するクリニック。", "hi": "यौन स्वास्थ्य सेवाएं प्रदान करने वाले क्लीनिक।", "de": "Kliniken, die sexuelle Gesundheitsdienste anbieten.", "th": "คลินิกให้บริการด้านสุขภาพทางเพศ", "ru": "Клиники, предоставляющие услуги сексуального здоровья.", "pl": "Kliniki oferujące usługi w zakresie zdrowia seksualnego.", "fr": "Cliniques proposant des services de santé sexuelle.", "pt": "Clínicas fornecendo serviços de saúde sexual.", "id": "Klinik yang menyediakan layanan kesehatan seksual.", "bn": "যৌন স্বাস্থ্য পরিষেবা প্রদানকারী ক্লিনিক।"},
		},
		{
			Kind:         payloads.EventKindSafeSexWorkshop,
			DisplayOrder: 40,
			Name:         utils.LocalizedString{"en": "Safe Sex Workshop", "tr": "Güvenli Seks Atölyesi", "es": "Taller de Sexo Seguro", "he": "סדנת מין בטוח", "ar": "ورشة عمل الجنس الآمن", "zh": "安全性行为工作坊", "ja": "セーフセックスワークショップ", "hi": "सुरक्षित यौन कार्यशाला", "de": "Workshop für sicheren Sex", "th": "เวิร์กช็อปเรื่องเพศสัมพันธ์ที่ปลอดภัย", "ru": "Семинар по безопасному сексу", "pl": "Warsztaty bezpiecznego seksu", "fr": "Atelier sur le sexe sans risque", "pt": "Workshop de Sexo Seguro", "id": "Lokakarya Seks Aman", "bn": "নিরাপদ যৌন কর্মশালা"},
			Description:  utils.LocalizedString{"en": "Workshops promoting safe sex practices.", "tr": "Güvenli seks uygulamalarını teşvik eden atölyeler.", "es": "Talleres que promueven prácticas de sexo seguro.", "he": "סדנאות המקדמות פרקטיקות של מין בטוח.", "ar": "ورش عمل تروج لممارسات الجنس الآمن.", "zh": "推广安全性行为实践的工作坊。", "ja": "セーフセックスの実践を促進するワークショップ。", "hi": "सुरक्षित यौन प्रथाओं को बढ़ावा देने वाली कार्यशालाएं।", "de": "Workshops zur Förderung sicherer Sexpraktiken.", "th": "เวิร์กช็อปส่งเสริมการมีเพศสัมพันธ์ที่ปลอดภัย", "ru": "Семинары, пропагандирующие практику безопасного секса.", "pl": "Warsztaty promujące bezpieczne praktyki seksualne.", "fr": "Ateliers promouvant des pratiques sexuelles sûres.", "pt": "Workshops promovendo práticas de sexo seguro.", "id": "Lokakarya mempromosikan praktik seks yang aman.", "bn": "নিরাপদ যৌন অভ্যাস প্রচার কর্মশালা।"},
		},
		{
			Kind:         payloads.EventKindSTDAwareness,
			DisplayOrder: 41,
			Name:         utils.LocalizedString{"en": "STD Awareness", "tr": "CYBH Farkındalığı", "es": "Concientización ETS", "he": "מודעות למחלות מין", "ar": "التوعية بالأمراض المنقولة جنسياً", "zh": "性病意识", "ja": "STD啓発", "hi": "एसटीडी जागरूकता", "de": "STD-Aufklärung", "th": "ความตระหนักเรื่องโรคติดต่อทางเพศสัมพันธ์", "ru": "Осведомленность о ЗППП", "pl": "Świadomość chorób przenoszonych drogą płciową", "fr": "Sensibilisation aux MST", "pt": "Conscientização sobre DST", "id": "Kesadaran PMS", "bn": "এসটিডি সচেতনতা"},
			Description:  utils.LocalizedString{"en": "Raising awareness about sexually transmitted diseases.", "tr": "Cinsel yolla bulaşan hastalıklar hakkında farkındalık yaratma.", "es": "Crear conciencia sobre las enfermedades de transmisión sexual.", "he": "העלאת המודעות למחלות המועברות במגע מיני.", "ar": "رفع الوعي حول الأمراض المنقولة جنسياً.", "zh": "提高对性传播疾病的认识。", "ja": "性感染症に関する意識向上。", "hi": "यौन संचारित रोगों के बारे में जागरूकता बढ़ाना।", "de": "Sensibilisierung für sexuell übertragbare Krankheiten.", "th": "การสร้างความตระหนักรู้เกี่ยวกับโรคติดต่อทางเพศสัมพันธ์", "ru": "Повышение осведомленности о заболеваниях, передающихся половым путем.", "pl": "Podnoszenie świadomości na temat chorób przenoszonych drogą płciową.", "fr": "Sensibilisation aux maladies sexuellement transmissibles.", "pt": "Aumentar a conscientização sobre doenças sexualmente transmissíveis.", "id": "Meningkatkan kesadaran tentang penyakit menular seksual.", "bn": "যৌন সংক্রামিত রোগ সম্পর্কে সচেতনতা বৃদ্ধি।"},
		},
		{
			Kind:         payloads.EventKindPrEPInfoSession,
			DisplayOrder: 42,
			Name:         utils.LocalizedString{"en": "PrEP Info Session", "tr": "PrEP Bilgi Oturumu", "es": "Sesión Info PrEP", "he": "מפגש מידע על PrEP", "ar": "جلسة معلومات PrEP", "zh": "PrEP 信息会", "ja": "PrEP 情報セッション", "hi": "PrEP सूचना सत्र", "de": "PrEP-Info-Sitzung", "th": "เซสชั่นข้อมูล PrEP", "ru": "Инфосессия по PrEP", "pl": "Sesja informacyjna PrEP", "fr": "Session d'info PrEP", "pt": "Sessão de Informação PrEP", "id": "Sesi Info PrEP", "bn": "PrEP তথ্য সেশন"},
			Description:  utils.LocalizedString{"en": "Information about Pre-Exposure Prophylaxis (PrEP).", "tr": "Temas Öncesi Profilaksi (PrEP) hakkında bilgi.", "es": "Información sobre Profilaxis Pre-Exposición (PrEP).", "he": "מידע על טיפול מונע טרום-חשיפה (PrEP).", "ar": "معلومات حول العلاج الوقائي قبل التعرض (PrEP).", "zh": "关于暴露前预防 (PrEP) 的信息。", "ja": "曝露前予防 (PrEP) に関する情報。", "hi": "प्री-एक्सपोज़र प्रोफिलैक्सिस (PrEP) के बारे में जानकारी।", "de": "Informationen zur Präexpositionsprophylaxe (PrEP).", "th": "ข้อมูลเกี่ยวกับการป้องกันก่อนการสัมผัสเชื้อ (PrEP)", "ru": "Информация о доконтактной профилактике (PrEP).", "pl": "Informacje o profilaktyce przedekspozycyjnej (PrEP).", "fr": "Informations sur la prophylaxie pré-exposition (PrEP).", "pt": "Informações sobre Profilaxia Pré-Exposição (PrEP).", "id": "Informasi tentang Profilaksis Pra-Pajanan (PrEP).", "bn": "প্রাক-এক্সপোজার প্রফিল্যাক্সিস (PrEP) সম্পর্কে তথ্য।"},
		},
		{
			Kind:         payloads.EventKindPEPWorkshop,
			DisplayOrder: 43,
			Name:         utils.LocalizedString{"en": "PEP Workshop", "tr": "PEP Atölyesi", "es": "Taller PEP", "he": "סדנת PEP", "ar": "ورشة عمل PEP", "zh": "PEP 工作坊", "ja": "PEP ワークショップ", "hi": "PEP कार्यशाला", "de": "PEP-Workshop", "th": "เวิร์กช็อป PEP", "ru": "Семинар по PEP", "pl": "Warsztaty PEP", "fr": "Atelier PEP", "pt": "Workshop PEP", "id": "Lokakarya PEP", "bn": "PEP কর্মশালা"},
			Description:  utils.LocalizedString{"en": "Workshops about Post-Exposure Prophylaxis (PEP).", "tr": "Temas Sonrası Profilaksi (PEP) hakkında atölyeler.", "es": "Talleres sobre Profilaxis Post-Exposición (PEP).", "he": "סדנאות על טיפול מונע לאחר חשיפה (PEP).", "ar": "ورش عمل حول العلاج الوقائي بعد التعرض (PEP).", "zh": "关于暴露后预防 (PEP) 的工作坊。", "ja": "曝露後予防 (PEP) に関するワークショップ。", "hi": "पोस्ट-एक्सपोज़र प्रोफिलैक्सिस (PEP) के बारे में कार्यशालाएं।", "de": "Workshops zur Postexpositionsprophylaxe (PEP).", "th": "เวิร์กช็อปเกี่ยวกับการป้องกันหลังการสัมผัสเชื้อ (PEP)", "ru": "Семинары по постконтактной профилактике (PEP).", "pl": "Warsztaty na temat profilaktyki poekspozycyjnej (PEP).", "fr": "Ateliers sur la prophylaxie post-exposition (PEP).", "pt": "Workshops sobre Profilaxia Pós-Exposição (PEP).", "id": "Lokakarya tentang Profilaksis Pasca Pajanan (PEP).", "bn": "পোস্ট-এক্সপোজার প্রফিল্যাক্সিস (PEP) সম্পর্কে কর্মশালা।"},
		},
		{
			Kind:         payloads.EventKindNeedleExchange,
			DisplayOrder: 44,
			Name:         utils.LocalizedString{"en": "Needle Exchange", "tr": "İğne Değişimi", "es": "Intercambio de Agujas", "he": "החלפת מחטים", "ar": "تبادل الإبر", "zh": "针具交换", "ja": "針交換", "hi": "सुई विनिमय", "de": "Nadelaustausch", "th": "การแลกเปลี่ยนเข็ม", "ru": "Обмен шприцев", "pl": "Wymiana igieł", "fr": "Échange de seringues", "pt": "Troca de Seringas", "id": "Pertukaran Jarum", "bn": "নিডেল এক্সচেঞ্জ"},
			Description:  utils.LocalizedString{"en": "Programs for safe needle exchange.", "tr": "Güvenli iğne değişimi için programlar.", "es": "Programas para el intercambio seguro de agujas.", "he": "תוכניות להחלפה בטוחה של מחטים.", "ar": "برامج لتبادل الإبر بشكل آمن.", "zh": "安全针具交换计划。", "ja": "安全な針交換のためのプログラム。", "hi": "सुरक्षित सुई विनिमय के लिए कार्यक्रम।", "de": "Programme für den sicheren Nadelaustausch.", "th": "โครงการแลกเปลี่ยนเข็มอย่างปลอดภัย", "ru": "Программы безопасного обмена шприцев.", "pl": "Programy bezpiecznej wymiany igieł.", "fr": "Programmes pour l'échange sécurisé de seringues.", "pt": "Programas para troca segura de seringas.", "id": "Program pertukaran jarum yang aman.", "bn": "নিরাপদ সুচ বিনিময়ের জন্য প্রোগ্রাম।"},
		},
		{
			Kind:         payloads.EventKindCounselingSession,
			DisplayOrder: 45,
			Name:         utils.LocalizedString{"en": "Counseling Session", "tr": "Danışmanlık Seansı", "es": "Sesión de Consejería", "he": "מפגש ייעוץ", "ar": "جلسة استشارية", "zh": "咨询会议", "ja": "カウンセリングセッション", "hi": "परामर्श सत्र", "de": "Beratungssitzung", "th": "เซสชั่นการให้คำปรึกษา", "ru": "Сессия консультирования", "pl": "Sesja doradcza", "fr": "Séance de conseil", "pt": "Sessão de Aconselhamento", "id": "Sesi Konseling", "bn": "কাউন্সেলিং সেশন"},
			Description:  utils.LocalizedString{"en": "One-on-one or group counseling sessions.", "tr": "Birebir veya grup danışmanlık seansları.", "es": "Sesiones de consejería individuales o grupales.", "he": "מפגשי ייעוץ אישיים או קבוצתיים.", "ar": "جلسات استشارية فردية أو جماعية.", "zh": "一对一或小组咨询会议。", "ja": "マンツーマンまたはグループカウンセリングセッション。", "hi": "एक-एक करके या समूह परामर्श सत्र।", "de": "Einzel- oder Gruppenberatungssitzungen.", "th": "การให้คำปรึกษาแบบตัวต่อตัวหรือแบบกลุ่ม", "ru": "Индивидуальные или групповые консультации.", "pl": "Indywidualne lub grupowe sesje doradcze.", "fr": "Séances de conseil individuelles ou de groupe.", "pt": "Sessões de aconselhamento individuais ou em grupo.", "id": "Sesi konseling satu lawan satu atau kelompok.", "bn": "এক-এক বা গ্রুপ কাউন্সেলিং সেশন।"},
		},
		{
			Kind:         payloads.EventKindHarmReduction,
			DisplayOrder: 46,
			Name:         utils.LocalizedString{"en": "Harm Reduction", "tr": "Zarar Azaltma", "es": "Reducción de Daños", "he": "מזעור נזקים", "ar": "الحد من الضرر", "zh": "减少危害", "ja": "ハームリダクション", "hi": "नुकसान में कमी", "de": "Schadensminimierung", "th": "การลดอันตราย", "ru": "Снижение вреда", "pl": "Redukcja szkód", "fr": "Réduction des risques", "pt": "Redução de Danos", "id": "Pengurangan Dampak Buruk", "bn": "ক্ষতি হ্রাস"},
			Description:  utils.LocalizedString{"en": "Events focusing on reducing risks associated with substance use.", "tr": "Madde kullanımıyla ilişkili riskleri azaltmaya odaklanan etkinlikler.", "es": "Eventos centrados en reducir los riesgos asociados con el uso de sustancias.", "he": "אירועים המתמקדים בהפחתת סיכונים הקשורים לשימוש בחומרים.", "ar": "أحداث تركز على الحد من المخاطر المرتبطة بتعاطي المخدرات.", "zh": "专注于减少与药物使用相关风险的活动。", "ja": "薬物使用に伴うリスクの軽減に焦点を当てたイベント。", "hi": "पदार्थ के उपयोग से जुड़े जोखिमों को कम करने पर केंद्रित कार्यक्रम।", "de": "Veranstaltungen zur Reduzierung von Risiken im Zusammenhang mit Substanzkonsum.", "th": "กิจกรรมที่เน้นการลดความเสี่ยงที่เกี่ยวข้องกับการใช้สารเสพติด", "ru": "Мероприятия, направленные на снижение рисков, связанных с употреблением психоактивных веществ.", "pl": "Wydarzenia koncentrujące się na redukcji ryzyka związanego z używaniem substancji.", "fr": "Événements axés sur la réduction des risques liés à la consommation de substances.", "pt": "Eventos focados na redução de riscos associados ao uso de substâncias.", "id": "Acara yang berfokus pada pengurangan risiko terkait penggunaan zat.", "bn": "পদার্থ ব্যবহারের সাথে সম্পর্কিত ঝুঁকি কমানোর উপর দৃষ্টি নিবদ্ধ করা ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindSexualViolenceSupport,
			DisplayOrder: 47,
			Name:         utils.LocalizedString{"en": "Sexual Violence Support", "tr": "Cinsel Şiddet Desteği", "es": "Apoyo Violencia Sexual", "he": "תמיכה בנפגעות תקיפה מינית", "ar": "دعم العنف الجنسي", "zh": "性暴力支持", "ja": "性暴力サポート", "hi": "यौन हिंसा समर्थन", "de": "Unterstützung bei sexueller Gewalt", "th": "การสนับสนุนความรุนแรงทางเพศ", "ru": "Поддержка при сексуальном насилии", "pl": "Wsparcie w przypadku przemocy seksualnej", "fr": "Soutien contre la violence sexuelle", "pt": "Apoio à Violência Sexual", "id": "Dukungan Kekerasan Seksual", "bn": "যৌন সহিংসতা সমর্থন"},
			Description:  utils.LocalizedString{"en": "Support services for survivors of sexual violence.", "tr": "Cinsel şiddet mağdurları için destek hizmetleri.", "es": "Servicios de apoyo para sobrevivientes de violencia sexual.", "he": "שירותי תמיכה לניצולי אלימות מינית.", "ar": "خدمات الدعم للناجين من العنف الجنسي.", "zh": "为性暴力幸存者提供的支持服务。", "ja": "性暴力サバイバーのためのサポートサービス。", "hi": "यौन हिंसा के बचे लोगों के लिए सहायता सेवाएं।", "de": "Unterstützungsdienste für Überlebende sexueller Gewalt.", "th": "บริการสนับสนุนสำหรับผู้รอดชีวิตจากความรุนแรงทางเพศ", "ru": "Службы поддержки для переживших сексуальное насилие.", "pl": "Usługi wsparcia dla ofiar przemocy seksualnej.", "fr": "Services de soutien pour les survivants de violences sexuelles.", "pt": "Serviços de apoio para sobreviventes de violência sexual.", "id": "Layanan dukungan bagi penyintas kekerasan seksual.", "bn": "যৌন সহিংসতার বেঁচে থাকা ব্যক্তিদের জন্য সহায়তা পরিষেবা।"},
		},
		{
			Kind:         payloads.EventKindCommunityMeetup,
			DisplayOrder: 48,
			Name:         utils.LocalizedString{"en": "Community Meetup", "tr": "Topluluk Buluşması", "es": "Reunión Comunitaria", "he": "מפגש קהילתי", "ar": "لقاء مجتمعي", "zh": "社区聚会", "ja": "コミュニティミートアップ", "hi": "सामुदायिक मिलन", "de": "Community-Treffen", "th": "มีตติ้งชุมชน", "ru": "Встреча сообщества", "pl": "Spotkanie społeczności", "fr": "Rencontre communautaire", "pt": "Encontro Comunitário", "id": "Pertemuan Komunitas", "bn": "কমিউনিটি মিটআপ"},
			Description:  utils.LocalizedString{"en": "Informal community gatherings.", "tr": "Resmi olmayan topluluk toplanmaları.", "es": "Reuniones comunitarias informales.", "he": "מפגשים קהילתיים לא רשמיים.", "ar": "تجمعات مجتمعية غير رسمية.", "zh": "非正式社区聚会。", "ja": "非公式なコミュニティの集まり。", "hi": "अनौपचारिक सामुदायिक सभाएँ।", "de": "Informelle Gemeinschaftstreffen.", "th": "การรวมตัวของชุมชนอย่างไม่เป็นทางการ", "ru": "Неформальные собрания сообщества.", "pl": "Nieformalne spotkania społeczności.", "fr": "Rassemblements communautaires informels.", "pt": "Reuniões comunitárias informais.", "id": "Pertemuan komunitas informal.", "bn": "অনানুষ্ঠানিক সম্প্রদায় সমাবেশ।"},
		},
		{
			Kind:         payloads.EventKindOpenMicNight,
			DisplayOrder: 49,
			Name:         utils.LocalizedString{"en": "Open Mic Night", "tr": "Açık Mikrofon Gecesi", "es": "Noche de Micrófono Abierto", "he": "ערב במה פתוחה", "ar": "ليلة الميكروفون المفتوح", "zh": "开放麦克风之夜", "ja": "オープンマイクナイト", "hi": "ओपन माइक नाइट", "de": "Open Mic Night", "th": "คืนโอเพ่นไมค์", "ru": "Вечер открытого микрофона", "pl": "Noc otwartego mikrofonu", "fr": "Soirée micro ouvert", "pt": "Noite de Microfone Aberto", "id": "Malam Mic Terbuka", "bn": "ওপেন মাইক নাইট"},
			Description:  utils.LocalizedString{"en": "An event where anyone can perform music, poetry, or comedy.", "tr": "Herkesin müzik, şiir veya komedi performansı sergileyebileceği bir etkinlik.", "es": "Un evento donde cualquiera puede interpretar música, poesía o comedia.", "he": "אירוע שבו כל אחד יכול להופיע עם מוזיקה, שירה או קומדיה.", "ar": "حدث حيث يمكن لأي شخص أداء الموسيقى أو الشعر أو الكوميديا.", "zh": "任何人都可以表演音乐、诗歌或喜剧的活动。", "ja": "誰でも音楽、詩、コメディを披露できるイベント。", "hi": "एक ऐसा कार्यक्रम जहां कोई भी संगीत, कविता या कॉमेडी का प्रदर्शन कर सकता है।", "de": "Eine Veranstaltung, bei der jeder Musik, Poesie oder Comedy aufführen kann.", "th": "กิจกรรมที่ใครๆ ก็สามารถแสดงดนตรี บทกวี หรือตลกได้", "ru": "Мероприятие, где любой желающий может выступить с музыкой, стихами или комедией.", "pl": "Wydarzenie, na którym każdy może wykonywać muzykę, poezję lub komedię.", "fr": "Un événement où n'importe qui peut jouer de la musique, de la poésie ou de la comédie.", "pt": "Um evento onde qualquer pessoa pode apresentar música, poesia ou comédia.", "id": "Acara di mana siapa saja dapat menampilkan musik, puisi, atau komedi.", "bn": "এমন একটি ইভেন্ট যেখানে যে কেউ গান, কবিতা বা কমেডি পরিবেশন করতে পারে।"},
		},
		{
			Kind:         payloads.EventKindDragBrunch,
			DisplayOrder: 50,
			Name:         utils.LocalizedString{"en": "Drag Brunch", "tr": "Drag Kahvaltısı", "es": "Brunch Drag", "he": "בראנץ' דראג", "ar": "برانش دراغ", "zh": "变装早午餐", "ja": "ドラァグブランチ", "hi": "ड्रैग ब्रंच", "de": "Drag-Brunch", "th": "แดร็กบรันช์", "ru": "Дрэг-бранч", "pl": "Drag Brunch", "fr": "Brunch drag", "pt": "Brunch Drag", "id": "Brunch Drag", "bn": "ড্র্যাগ ব্রাঞ্চ"},
			Description:  utils.LocalizedString{"en": "A brunch event featuring drag performances.", "tr": "Drag performanslarının yer aldığı bir kahvaltı etkinliği.", "es": "Un evento de brunch con actuaciones de drag.", "he": "אירוע בראנץ' הכולל הופעות דראג.", "ar": "حدث برانش يضم عروض الدراغ.", "zh": "以变装表演为特色的早午餐活动。", "ja": "ドラァグパフォーマンスをフィーチャーしたブランチイベント。", "hi": "ड्रैग प्रदर्शन की विशेषता वाला एक ब्रंच कार्यक्रम।", "de": "Ein Brunch-Event mit Drag-Performances.", "th": "กิจกรรมบรันช์ที่มีการแสดงแดร็ก", "ru": "Бранч с участием дрэг-артистов.", "pl": "Wydarzenie brunchowe z występami drag.", "fr": "Un événement brunch avec des performances de drag.", "pt": "Um evento de brunch com performances de drag.", "id": "Acara brunch yang menampilkan pertunjukan drag.", "bn": "ড্র্যাগ পারফরমেন্স সমন্বিত একটি ব্রাঞ্চ ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindKaraokeNight,
			DisplayOrder: 51,
			Name:         utils.LocalizedString{"en": "Karaoke Night", "tr": "Karaoke Gecesi", "es": "Noche de Karaoke", "he": "ערב קריוקי", "ar": "ليلة كاريوكي", "zh": "卡拉OK之夜", "ja": "カラオケナイト", "hi": "कराओके रात", "de": "Karaoke-Abend", "th": "คืนคาราโอเกะ", "ru": "Караоке-вечер", "pl": "Wieczór karaoke", "fr": "Soirée karaoké", "pt": "Noite de Karaokê", "id": "Malam Karaoke", "bn": "কারাওকে নাইট"},
			Description:  utils.LocalizedString{"en": "A night of karaoke singing and fun.", "tr": "Karaoke şarkı söyleme ve eğlence gecesi.", "es": "Una noche de canto de karaoke y diversión.", "he": "לילה של שירת קריוקי וכיף.", "ar": "ليلة من غناء الكاريوكي والمرح.", "zh": "卡拉OK唱歌和娱乐之夜。", "ja": "カラオケと楽しみの夜。", "hi": "कराओके गायन और मस्ती की एक रात।", "de": "Eine Nacht voller Karaoke-Singen und Spaß.", "th": "ค่ำคืนแห่งการร้องเพลงคาราโอเกะและความสนุกสนาน", "ru": "Вечер караоке и веселья.", "pl": "Noc śpiewania karaoke i zabawy.", "fr": "Une soirée de chant karaoké et de plaisir.", "pt": "Uma noite de canto de karaokê e diversão.", "id": "Malam bernyanyi karaoke dan bersenang-senang.", "bn": "কারাওকে গান এবং মজার একটি রাত।"},
		},
		{
			Kind:         payloads.EventKindFundraisingGala,
			DisplayOrder: 52,
			Name:         utils.LocalizedString{"en": "Fundraising Gala", "tr": "Bağış Galası", "es": "Gala de Recaudación", "he": "ערב גיוס כספים", "ar": "حفل لجمع التبرعات", "zh": "筹款晚会", "ja": "募金ガラ", "hi": "धन उगाहने वाला गाला", "de": "Spendengala", "th": "กาล่าระดมทุน", "ru": "Благотворительный гала-вечер", "pl": "Gala zbiórki funduszy", "fr": "Gala de collecte de fonds", "pt": "Gala de Arrecadação", "id": "Gala Penggalangan Dana", "bn": "তহবিল সংগ্রহের গালা"},
			Description:  utils.LocalizedString{"en": "A formal event to raise money for causes.", "tr": "Amaçlar için para toplamak amacıyla düzenlenen resmi bir etkinlik.", "es": "Un evento formal para recaudar dinero para causas.", "he": "אירוע רשמי לגיוס כספים למטרות.", "ar": "حدث رسمي لجمع الأموال لأسباب معينة.", "zh": "为事业筹集资金的正式活动。", "ja": "大義のために資金を集めるための公式イベント。", "hi": "कारणों के लिए पैसा जुटाने के लिए एक औपचारिक कार्यक्रम।", "de": "Eine formelle Veranstaltung, um Geld für Zwecke zu sammeln.", "th": "กิจกรรมทางการเพื่อระดมเงินสำหรับสาเหตุต่างๆ", "ru": "Формальное мероприятие по сбору денег на благотворительность.", "pl": "Formalne wydarzenie mające na celu zbiórkę pieniędzy na cele charytatywne.", "fr": "Un événement formel pour collecter des fonds pour des causes.", "pt": "Um evento formal para arrecadar dinheiro para causas.", "id": "Acara formal untuk menggalang dana bagi tujuan tertentu.", "bn": "কারণ জন্য অর্থ সংগ্রহের জন্য একটি আনুষ্ঠানিক ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindArtWorkshop,
			DisplayOrder: 53,
			Name:         utils.LocalizedString{"en": "Art Workshop", "tr": "Sanat Atölyesi", "es": "Taller de Arte", "he": "סדנת אמנות", "ar": "ورشة عمل فنية", "zh": "艺术工作坊", "ja": "アートワークショップ", "hi": "कला कार्यशाला", "de": "Kunstworkshop", "th": "เวิร์กช็อปศิลปะ", "ru": "Арт-мастерская", "pl": "Warsztaty artystyczne", "fr": "Atelier d'art", "pt": "Workshop de Arte", "id": "Lokakarya Seni", "bn": "আর্ট ওয়ার্কশপ"},
			Description:  utils.LocalizedString{"en": "Hands-on art creation sessions.", "tr": "Uygulamalı sanat yaratma oturumları.", "es": "Sesiones prácticas de creación de arte.", "he": "מפגשי יצירה אמנותית מעשית.", "ar": "جلسات إبداع فني عملية.", "zh": "亲身实践的艺术创作课程。", "ja": "実践的なアート制作セッション。", "hi": "हाथों-हाथ कला निर्माण सत्र।", "de": "Praktische Kunstschaffenssitzungen.", "th": "เซสชันการสร้างสรรค์ศิลปะแบบลงมือปฏิบัติ", "ru": "Практические занятия по созданию искусства.", "pl": "Praktyczne sesje tworzenia sztuki.", "fr": "Séances pratiques de création artistique.", "pt": "Sessões práticas de criação de arte.", "id": "Sesi pembuatan seni langsung.", "bn": "হাতে-কলমে শিল্প তৈরির সেশন।"},
		},
		{
			Kind:         payloads.EventKindPoetryReading,
			DisplayOrder: 54,
			Name:         utils.LocalizedString{"en": "Poetry Reading", "tr": "Şiir Dinletisi", "es": "Lectura de Poesía", "he": "קריאת שירה", "ar": "قراءة الشعر", "zh": "诗歌朗诵", "ja": "詩の朗読", "hi": "कविता पाठ", "de": "Dichterlesung", "th": "การอ่านบทกวี", "ru": "Поэтические чтения", "pl": "Czytanie poezji", "fr": "Lecture de poésie", "pt": "Leitura de Poesia", "id": "Pembacaan Puisi", "bn": "কবিতা পাঠ"},
			Description:  utils.LocalizedString{"en": "An event to listen to and share poetry.", "tr": "Şiir dinlemek ve paylaşmak için bir etkinlik.", "es": "Un evento para escuchar y compartir poesía.", "he": "אירוע להאזנה ושיתוף שירה.", "ar": "حدث للاستماع ومشاركة الشعر.", "zh": "聆听和分享诗歌的活动。", "ja": "詩を聞いたり共有したりするイベント。", "hi": "कविता सुनने और साझा करने का एक कार्यक्रम।", "de": "Eine Veranstaltung zum Hören und Teilen von Gedichten.", "th": "กิจกรรมเพื่อฟังและแบ่งปันบทกวี", "ru": "Мероприятие, чтобы послушать и поделиться стихами.", "pl": "Wydarzenie mające na celu słuchanie i dzielenie się poezją.", "fr": "Un événement pour écouter et partager de la poésie.", "pt": "Um evento para ouvir e compartilhar poesia.", "id": "Acara untuk mendengarkan dan berbagi puisi.", "bn": "কবিতা শোনার এবং শেয়ার করার একটি অনুষ্ঠান।"},
		},
		{
			Kind:         payloads.EventKindLGBTQFilmFestival,
			DisplayOrder: 55,
			Name:         utils.LocalizedString{"en": "LGBTQ Film Festival", "tr": "LGBTQ Film Festivali", "es": "Festival de Cine LGBTQ", "he": "פסטיבל סרטי להט\"ב", "ar": "مهرجان أفلام مجتمع الميم", "zh": "LGBTQ 电影节", "ja": "LGBTQ 映画祭", "hi": "LGBTQ फिल्म महोत्सव", "de": "LGBTQ-Filmfestival", "th": "เทศกาลภาพยนตร์ LGBTQ", "ru": "ЛГБТК+ кинофестиваль", "pl": "Festiwal filmowy LGBTQ", "fr": "Festival du film LGBTQ", "pt": "Festival de Cinema LGBTQ", "id": "Festival Film LGBTQ", "bn": "LGBTQ চলচ্চিত্র উৎসব"},
			Description:  utils.LocalizedString{"en": "A festival showcasing LGBTQ+ films.", "tr": "LGBTQ+ filmlerini sergileyen bir festival.", "es": "Un festival que exhibe películas LGBTQ+.", "he": "פסטיבל המציג סרטי להט\"ב.", "ar": "مهرجان يعرض أفلام مجتمع الميم.", "zh": "展示 LGBTQ+ 电影的节日。", "ja": "LGBTQ+ 映画を紹介する映画祭。", "hi": "LGBTQ+ फिल्मों को प्रदर्शित करने वाला एक त्योहार।", "de": "Ein Festival, das LGBTQ+-Filme zeigt.", "th": "เทศกาลฉายภาพยนตร์ LGBTQ+", "ru": "Фестиваль, демонстрирующий ЛГБТК+ фильмы.", "pl": "Festiwal prezentujący filmy LGBTQ+.", "fr": "Un festival présentant des films LGBTQ+.", "pt": "Um festival exibindo filmes LGBTQ+.", "id": "Festival yang menampilkan film LGBTQ+.", "bn": "LGBTQ+ চলচ্চিত্র প্রদর্শনকারী একটি উৎসব।"},
		},
		{
			Kind:         payloads.EventKindQueerDanceClass,
			DisplayOrder: 56,
			Name:         utils.LocalizedString{"en": "Queer Dance Class", "tr": "Queer Dans Dersi", "es": "Clase de Baile Queer", "he": "שיעור ריקוד קווירי", "ar": "درس رقص كويري", "zh": "酷儿舞蹈课", "ja": "クィアダンスクラス", "hi": "क्वीर डांस क्लास", "de": "Queer-Tanzkurs", "th": "คลาสเต้นรำเควียร์", "ru": "Квир-танцевальный класс", "pl": "Lekcja tańca queer", "fr": "Cours de danse queer", "pt": "Aula de Dança Queer", "id": "Kelas Tari Queer", "bn": "কুইর ডান্স ক্লাস"},
			Description:  utils.LocalizedString{"en": "Dance classes inclusive to queer identities.", "tr": "Queer kimliklerini kapsayan dans dersleri.", "es": "Clases de baile inclusivas para identidades queer.", "he": "שיעורי ריקוד המכילים זהויות קוויריות.", "ar": "دروس رقص شاملة للهويات الكويرية.", "zh": "包容酷儿身份的舞蹈课程。", "ja": "クィアアイデンティティを受け入れるダンスクラス。", "hi": "क्वीर पहचान के लिए समावेशी नृत्य कक्षाएं।", "de": "Tanzkurse, die queer-Identitäten einbeziehen.", "th": "คลาสเรียนเต้นที่ครอบคลุมอัตลักษณ์เควียร์", "ru": "Танцевальные классы, инклюзивные для квир-идентичностей.", "pl": "Zajęcia taneczne włączające tożsamości queer.", "fr": "Cours de danse inclusifs pour les identités queer.", "pt": "Aulas de dança inclusivas para identidades queer.", "id": "Kelas tari yang inklusif bagi identitas queer.", "bn": "কুইর পরিচয়ের অন্তর্ভুক্ত নৃত্য ক্লাস।"},
		},
		{
			Kind:         payloads.EventKindMeditationSession,
			DisplayOrder: 57,
			Name:         utils.LocalizedString{"en": "Meditation Session", "tr": "Meditasyon Seansı", "es": "Sesión de Meditación", "he": "מפגש מדיטציה", "ar": "جلسة تأمل", "zh": "冥想课程", "ja": "瞑想セッション", "hi": "ध्यान सत्र", "de": "Meditationssitzung", "th": "เซสชันการทำสมาธิ", "ru": "Сеанс медитации", "pl": "Sesja medytacyjna", "fr": "Séance de méditation", "pt": "Sessão de Meditação", "id": "Sesi Meditasi", "bn": "ধ্যান অধিবেশন"},
			Description:  utils.LocalizedString{"en": "Guided meditation for relaxation and mindfulness.", "tr": "Rahatlama ve farkındalık için rehberli meditasyon.", "es": "Meditación guiada para relajación y atención plena.", "he": "מדיטציה מודרכת להרפיה ומיינדפולנס.", "ar": "تأمل موجه للاسترخاء واليقظة.", "zh": "用于放松和正念的引导冥想。", "ja": "リラクゼーションとマインドフルネスのためのガイド付き瞑想。", "hi": "विश्राम और दिमागीपन के लिए निर्देशित ध्यान।", "de": "Geführte Meditation zur Entspannung und Achtsamkeit.", "th": "การทำสมาธิแบบมีผู้แนะนำเพื่อความผ่อนคลายและสติ", "ru": "Управляемая медитация для расслабления и осознанности.", "pl": "Medytacja prowadzona w celu relaksu i uważności.", "fr": "Méditation guidée pour la relaxation et la pleine conscience.", "pt": "Meditação guiada para relaxamento e atenção plena.", "id": "Meditasi terpandu untuk relaksasi dan perhatian penuh.", "bn": "শিথিলকরণ এবং মননশীলতার জন্য নির্দেশিত ধ্যান।"},
		},
		{
			Kind:         payloads.EventKindSexEdClass,
			DisplayOrder: 58,
			Name:         utils.LocalizedString{"en": "Sex Education Class", "tr": "Cinsel Eğitim Dersi", "es": "Clase de Educación Sexual", "he": "שיעור חינוך מיני", "ar": "درس التربية الجنسية", "zh": "性教育课程", "ja": "性教育クラス", "hi": "यौन शिक्षा कक्षा", "de": "Sexualkundeunterricht", "th": "ชั้นเรียนเพศศึกษา", "ru": "Урок полового воспитания", "pl": "Lekcja edukacji seksualnej", "fr": "Cours d'éducation sexuelle", "pt": "Aula de Educação Sexual", "id": "Kelas Pendidikan Seks", "bn": "যৌন শিক্ষা ক্লাস"},
			Description:  utils.LocalizedString{"en": "Educational classes on sexual health and safety.", "tr": "Cinsel sağlık ve güvenlik üzerine eğitim dersleri.", "es": "Clases educativas sobre salud y seguridad sexual.", "he": "שיעורים חינוכיים בנושא בריאות ובטיחות מינית.", "ar": "دروس تعليمية حول الصحة والسلامة الجنسية.", "zh": "关于性健康和安全的教育课程。", "ja": "性的健康と安全に関する教育クラス。", "hi": "यौन स्वास्थ्य और सुरक्षा पर शैक्षिक कक्षाएं।", "de": "Bildungskurse zu sexueller Gesundheit und Sicherheit.", "th": "ชั้นเรียนการศึกษาเกี่ยวกับสุขภาพและความปลอดภัยทางเพศ", "ru": "Образовательные занятия по сексуальному здоровью и безопасности.", "pl": "Zajęcia edukacyjne na temat zdrowia i bezpieczeństwa seksualnego.", "fr": "Cours éducatifs sur la santé et la sécurité sexuelle.", "pt": "Aulas educativas sobre saúde e segurança sexual.", "id": "Kelas pendidikan tentang kesehatan dan keselamatan seksual.", "bn": "যৌন স্বাস্থ্য এবং নিরাপত্তা সংক্রান্ত শিক্ষামূলক ক্লাস।"},
		},
		{
			Kind:         payloads.EventKindHealthFair,
			DisplayOrder: 59,
			Name:         utils.LocalizedString{"en": "Health Fair", "tr": "Sağlık Fuarı", "es": "Feria de Salud", "he": "יריד בריאות", "ar": "معرض صحي", "zh": "健康博览会", "ja": "ヘルスフェア", "hi": "स्वास्थ्य मेला", "de": "Gesundheitsmesse", "th": "งานแฟร์สุขภาพ", "ru": "Ярмарка здоровья", "pl": "Targi zdrowia", "fr": "Foire de la santé", "pt": "Feira de Saúde", "id": "Pameran Kesehatan", "bn": "স্বাস্থ্য মেলা"},
			Description:  utils.LocalizedString{"en": "Community event offering various health services.", "tr": "Çeşitli sağlık hizmetleri sunan topluluk etkinliği.", "es": "Evento comunitario que ofrece varios servicios de salud.", "he": "אירוע קהילתי המציע שירותי בריאות שונים.", "ar": "حدث مجتمعي يقدم خدمات صحية متنوعة.", "zh": "提供各种健康服务的社区活动。", "ja": "さまざまな健康サービスを提供するコミュニティイベント。", "hi": "विभिन्न स्वास्थ्य सेवाएं प्रदान करने वाला सामुदायिक कार्यक्रम।", "de": "Gemeindeveranstaltung mit verschiedenen Gesundheitsdiensten.", "th": "กิจกรรมชุมชนที่ให้บริการด้านสุขภาพต่างๆ", "ru": "Общественное мероприятие, предлагающее различные медицинские услуги.", "pl": "Wydarzenie społecznościowe oferujące różne usługi zdrowotne.", "fr": "Événement communautaire offrant divers services de santé.", "pt": "Evento comunitário oferecendo vários serviços de saúde.", "id": "Acara komunitas yang menawarkan berbagai layanan kesehatan.", "bn": "বিভিন্ন স্বাস্থ্য পরিষেবা প্রদানকারী কমিউনিটি ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindStorytellingNight,
			DisplayOrder: 60,
			Name:         utils.LocalizedString{"en": "Storytelling Night", "tr": "Hikaye Anlatma Gecesi", "es": "Noche de Cuentacuentos", "he": "ערב סיפורים", "ar": "ليلة رواية القصص", "zh": "讲故事之夜", "ja": "ストーリーテリングナイト", "hi": "कहानी कहने की रात", "de": "Geschichtenerzähl-Nacht", "th": "คืนเล่าเรื่อง", "ru": "Вечер историй", "pl": "Noc opowiadania historii", "fr": "Soirée contes", "pt": "Noite de Contação de Histórias", "id": "Malam Bercerita", "bn": "গল্প বলার রাত"},
			Description:  utils.LocalizedString{"en": "An event to share personal stories and experiences.", "tr": "Kişisel hikayeleri ve deneyimleri paylaşmak için bir etkinlik.", "es": "Un evento para compartir historias y experiencias personales.", "he": "אירוע לשיתוף סיפורים אישיים וחוויות.", "ar": "حدث لمشاركة القصص والتجارب الشخصية.", "zh": "分享个人故事和经历的活动。", "ja": "個人的な物語や経験を共有するイベント。", "hi": "व्यक्तिगत कहानियों और अनुभवों को साझा करने का एक कार्यक्रम।", "de": "Eine Veranstaltung zum Austausch persönlicher Geschichten und Erfahrungen.", "th": "กิจกรรมเพื่อแบ่งปันเรื่องราวและประสบการณ์ส่วนตัว", "ru": "Мероприятие для обмена личными историями и опытом.", "pl": "Wydarzenie służące dzieleniu się osobistymi historiami i doświadczeniami.", "fr": "Un événement pour partager des histoires et des expériences personnelles.", "pt": "Um evento para compartilhar histórias e experiências pessoais.", "id": "Acara untuk berbagi cerita dan pengalaman pribadi.", "bn": "ব্যক্তিগত গল্প এবং অভিজ্ঞতা শেয়ার করার একটি ইভেন্ট।"},
		},
		{
			Kind:         payloads.EventKindQueerYouthCamp,
			DisplayOrder: 61,
			Name:         utils.LocalizedString{"en": "Queer Youth Camp", "tr": "Queer Gençlik Kampı", "es": "Campamento Juvenil Queer", "he": "מחנה נוער גאה", "ar": "مخيم الشباب الكويري", "zh": "酷儿青年营", "ja": "クィアユースキャンプ", "hi": "क्वीर युवा शिविर", "de": "Queer-Jugendcamp", "th": "ค่ายเยาวชนเควียร์", "ru": "Лагерь для квир-молодежи", "pl": "Obóz młodzieży queer", "fr": "Camp pour jeunes queer", "pt": "Acampamento Juvenil Queer", "id": "Perkemahan Pemuda Queer", "bn": "কুইর ইয়ুথ ক্যাম্প"},
			Description:  utils.LocalizedString{"en": "A camp designed for LGBTQ+ youth to connect and grow.", "tr": "LGBTQ+ gençlerinin bağlantı kurması ve büyümesi için tasarlanmış bir kamp.", "es": "Un campamento diseñado para que los jóvenes LGBTQ+ se conecten y crezcan.", "he": "מחנה המיועד לנוער להט\"ב להתחבר ולצמוח.", "ar": "مخيم مصمم لشباب مجتمع الميم للتواصل والنمو.", "zh": "专为 LGBTQ+ 青年设计的联系和成长营地。", "ja": "LGBTQ+ の若者がつながり、成長するために設計されたキャンプ。", "hi": "LGBTQ+ युवाओं को जोड़ने और बढ़ने के लिए डिज़ाइन किया गया एक शिविर।", "de": "Ein Camp, das für LGBTQ+-Jugendliche entwickelt wurde, um Kontakte zu knüpfen und zu wachsen.", "th": "ค่ายที่ออกแบบมาสำหรับเยาวชน LGBTQ+ เพื่อเชื่อมต่อและเติบโต", "ru": "Лагерь, созданный для того, чтобы ЛГБТК+ молодежь могла общаться и развиваться.", "pl": "Obóz zaprojektowany dla młodzieży LGBTQ+ w celu nawiązania kontaktów i rozwoju.", "fr": "Un camp conçu pour que les jeunes LGBTQ+ se connectent et grandissent.", "pt": "Um acampamento projetado para jovens LGBTQ+ se conectarem e crescerem.", "id": "Perkemahan yang dirancang untuk pemuda LGBTQ+ untuk terhubung dan tumbuh.", "bn": "LGBTQ+ যুবকদের সংযোগ এবং বৃদ্ধির জন্য ডিজাইন করা একটি ক্যাম্প।"},
		},
		{
			Kind:         payloads.EventKindVolunteerMeetup,
			DisplayOrder: 62,
			Name:         utils.LocalizedString{"en": "Volunteer Meetup", "tr": "Gönüllü Buluşması", "es": "Reunión de Voluntarios", "he": "מפגש מתנדבים", "ar": "لقاء المتطوعين", "zh": "志愿者聚会", "ja": "ボランティアミートアップ", "hi": "स्वयंसेवक मिलन", "de": "Freiwilligentreffen", "th": "มีตติ้งอาสาสมัคร", "ru": "Встреча волонтеров", "pl": "Spotkanie wolontariuszy", "fr": "Rencontre de bénévoles", "pt": "Encontro de Voluntários", "id": "Pertemuan Sukarelawan", "bn": "স্বেচ্ছাসেবক মিটআপ"},
			Description:  utils.LocalizedString{"en": "Meetings for organizing volunteer efforts.", "tr": "Gönüllü çalışmalarını organize etmek için toplantılar.", "es": "Reuniones para organizar esfuerzos de voluntariado.", "he": "פגישות לארגון מאמצי התנדבות.", "ar": "اجتماعات لتنظيم الجهود التطوعية.", "zh": "组织志愿者工作的会议。", "ja": "ボランティア活動を組織するための会議。", "hi": "स्वयंसेवक प्रयासों को व्यवस्थित करने के लिए बैठकें।", "de": "Treffen zur Organisation von Freiwilligenarbeit.", "th": "การประชุมเพื่อจัดระเบียบความพยายามของอาสาสมัคร", "ru": "Встречи для организации волонтерской деятельности.", "pl": "Spotkania w celu organizowania działań wolontariackich.", "fr": "Réunions pour organiser les efforts bénévoles.", "pt": "Reuniões para organizar esforços voluntários.", "id": "Pertemuan untuk mengorganisir upaya sukarelawan.", "bn": "স্বেচ্ছাসেবী প্রচেষ্টার আয়োজনের জন্য মিটিং।"},
		},
		{
			Kind:         payloads.EventKindSocialJusticeForum,
			DisplayOrder: 63,
			Name:         utils.LocalizedString{"en": "Social Justice Forum", "tr": "Sosyal Adalet Forumu", "es": "Foro de Justicia Social", "he": "פורום צדק חברתי", "ar": "منتدى العدالة الاجتماعية", "zh": "社会正义论坛", "ja": "社会正義フォーラム", "hi": "सामाजिक न्याय मंच", "de": "Forum für soziale Gerechtigkeit", "th": "ฟอรัมความยุติธรรมทางสังคม", "ru": "Форум социальной справедливости", "pl": "Forum sprawiedliwości społecznej", "fr": "Forum sur la justice sociale", "pt": "Fórum de Justiça Social", "id": "Forum Keadilan Sosial", "bn": "সামাজিক ন্যায়বিচার ফোরাম"},
			Description:  utils.LocalizedString{"en": "Discussions focused on social justice issues.", "tr": "Sosyal adalet sorunlarına odaklanan tartışmalar.", "es": "Discusiones centradas en temas de justicia social.", "he": "דיונים המתמקדים בנושאי צדק חברתי.", "ar": "مناقشات تركز على قضايا العدالة الاجتماعية.", "zh": "专注于社会正义问题的讨论。", "ja": "社会正義の問題に焦点を当てた議論。", "hi": "सामाजिक न्याय के मुद्दों पर केंद्रित चर्चाएँ।", "de": "Diskussionen mit Schwerpunkt auf Fragen der sozialen Gerechtigkeit.", "th": "การอภิปรายที่เน้นประเด็นความยุติธรรมทางสังคม", "ru": "Дискуссии, посвященные вопросам социальной справедливости.", "pl": "Dyskusje koncentrujące się na kwestiach sprawiedliwości społecznej.", "fr": "Discussions axées sur les questions de justice sociale.", "pt": "Discussões focadas em questões de justiça social.", "id": "Diskusi yang berfokus pada masalah keadilan sosial.", "bn": "সামাজিক ন্যায়বিচারের বিষয়গুলিতে দৃষ্টি নিবদ্ধ করে আলোচনা।"},
		},
		{
			Kind:         payloads.EventKindMentalWellnessRetreat,
			DisplayOrder: 64,
			Name:         utils.LocalizedString{"en": "Mental Wellness Retreat", "tr": "Zihinsel Sağlık İnzivası", "es": "Retiro de Bienestar Mental", "he": "ריטריט בריאות הנפש", "ar": "خلوة العافية العقلية", "zh": "心理健康静修", "ja": "メンタルウェルネスリトリート", "hi": "मानसिक कल्याण रिट्रीट", "de": "Mental-Wellness-Retreat", "th": "รีทรีตสุขภาพจิต", "ru": "Ретрит по психическому здоровью", "pl": "Rekolekcje zdrowia psychicznego", "fr": "Retraite de bien-être mental", "pt": "Retiro de Bem-Estar Mental", "id": "Retret Kesehatan Mental", "bn": "মানসিক সুস্থতা রিট্রিট"},
			Description:  utils.LocalizedString{"en": "Retreats focusing on mental health and wellness.", "tr": "Ruh sağlığı ve zindeliğe odaklanan inzivalar.", "es": "Retiros centrados en la salud mental y el bienestar.", "he": "ריטריטים המתמקדים בבריאות הנפש ובריאות כללית.", "ar": "خلوات تركز على الصحة العقلية والعافية.", "zh": "专注于心理健康和保健的静修。", "ja": "メンタルヘルスとウェルネスに焦点を当てたリトリート。", "hi": "मानसिक स्वास्थ्य और कल्याण पर केंद्रित रिट्रीट।", "de": "Retreats mit Fokus auf psychische Gesundheit und Wellness.", "th": "รีทรีตที่เน้นสุขภาพจิตและความเป็นอยู่ที่ดี", "ru": "Ретриты, посвященные психическому здоровью и благополучию.", "pl": "Rekolekcje koncentrujące się na zdrowiu psychicznym i dobrym samopoczuciu.", "fr": "Retraites axées sur la santé mentale et le bien-être.", "pt": "Retiros focados em saúde mental e bem-estar.", "id": "Retret yang berfokus pada kesehatan mental dan kebugaran.", "bn": "মানসিক স্বাস্থ্য এবং সুস্থতার উপর দৃষ্টি নিবদ্ধ করে পশ্চাদপসরণ।"},
		},
	}
	for _, ek := range eventKinds {
		err := db.Clauses(clause.OnConflict{
			UpdateAll: true,
		}).Create(&ek).Error
		if err != nil {
			return err
		}
	}
	return nil

}
