package docs

import "core/constants"

func ActionDocuments() []ActionDoc {
	return []ActionDoc{
		{
			Action:      constants.CMD_INITIAL_SYNC,
			Tag:         "System",
			Summary:     "Initial sync",
			Description: "Returns bootstrap data such as preferences, languages, event kinds, report kinds, and other client startup data.",
			Auth:        AuthNone,
		},
		{
			Action:      constants.CMD_LINK_METADATA,
			Tag:         "System",
			Summary:     "Fetch link and oEmbed metadata",
			Description: "Fetches Open Graph, Twitter Card, and discovered oEmbed 1.0 metadata for a public URL.",
			Auth:        AuthNone,
			Params:      []Param{stringParam("url", "Plain or URL-encoded public absolute URL to inspect.", true)},
		},
		{
			Action:      constants.CMD_GET_VAPID_PUBLIC_KEY,
			Tag:         "System",
			Summary:     "Get VAPID public key",
			Description: "Returns the server public key used by browser push subscriptions.",
			Auth:        AuthNone,
		},
		{
			Action:      constants.CMD_SET_VAPID_SUBSCRIBE,
			Tag:         "System",
			Summary:     "Save push subscription",
			Description: "Stores the authenticated user's Web Push subscription. The subscriptions field must be a JSON string with endpoint and keys.p256dh/auth.",
			Auth:        AuthRequired,
			Params: []Param{
				stringParam("subscriptions", `JSON string: {"endpoint":"...","keys":{"p256dh":"...","auth":"..."}}.`, true),
			},
		},
		{
			Action:      constants.CMD_PAYMENT_METHODS,
			Tag:         "System",
			Summary:     "Fetch payment methods",
			Description: "Returns configured payment methods and package metadata.",
			Auth:        AuthNone,
		},
		{
			Action:      constants.CMD_GET_NOTIFICATIONS,
			Tag:         "System",
			Summary:     "Fetch notifications",
			Description: "Returns notification records for the authenticated user.",
			Auth:        AuthRequired,
		},

		{
			Action:      constants.CMD_AUTH_REGISTER,
			Tag:         "Auth",
			Summary:     "Register user",
			Description: "Creates a user and returns the created user plus JWT token. recaptchaToken is preferred; captcha is accepted as a fallback.",
			Auth:        AuthNone,
			Params: []Param{
				stringParam("name", "User display or profile name.", true),
				stringParam("nickname", "Unique username/nickname.", true),
				stringParam("password", "Plain text password to hash server-side.", true),
				enumParam("domain", "Domain identifier or host.", true, "coolvibes", "coolvibes.lgbt", "coolvibes.app", "coolvibes.io", "kewlswap.com", "kewlswap.io", "kewlswap.app"),
				stringParam("email", "Optional email address.", false),
				stringParam("captcha", "Captcha token fallback.", false),
				stringParam("recaptchaToken", "Google reCAPTCHA token.", false),
				stringParam("referralCode", "Optional referrer public user id, username, email, or display name.", false),
			},
		},
		{
			Action:      constants.CMD_AUTH_LOGIN,
			Tag:         "Auth",
			Summary:     "Login user",
			Description: "Authenticates by username, email, or nickname and returns the user plus JWT token.",
			Auth:        AuthNone,
			Params: []Param{
				stringParam("nickname", "Username, email, or nickname.", true),
				stringParam("password", "Plain text password.", true),
			},
		},
		{
			Action:      constants.CMD_AUTH_CHECK,
			Tag:         "Auth",
			Summary:     "Check auth token",
			Description: "Returns the authenticated user loaded from the bearer token.",
			Auth:        AuthRequired,
		},
		{
			Action:      constants.CMD_AUTH_USER_INFO,
			Tag:         "Auth",
			Summary:     "Fetch authenticated user info",
			Description: "Returns the current authenticated user with loaded relations.",
			Auth:        AuthRequired,
		},

		{
			Action:      constants.CMD_USER_FETCH_PROFILE,
			Tag:         "Users",
			Summary:     "Fetch user profile",
			Description: "Fetches a public profile by nickname or username. One of nickname or username is required.",
			Auth:        AuthNone,
			Params: []Param{
				stringParam("nickname", "Profile nickname lookup.", false),
				stringParam("username", "Profile username lookup fallback.", false),
			},
		},
		{
			Action:      constants.CMD_SEARCH_LOOKUP_USER,
			Tag:         "Search",
			Summary:     "Lookup users by prefix",
			Description: "Returns up to 15 users matching the query in username or display name, with prefix matches ranked first.",
			Auth:        AuthNone,
			Params:      []Param{stringParam("query", "Username prefix.", false)},
		},
		{
			Action:      constants.CMD_SEARCH_GLOBAL,
			Tag:         "Search",
			Summary:     "Search people, events, posts, and places",
			Description: "Returns grouped public search results. scope may limit the response to one result group.",
			Auth:        AuthNone,
			Params: []Param{
				stringParam("query", "Search text. At least 2 characters.", true),
				enumParam("scope", "Result group to return.", false, "all", "people", "events", "posts", "places", "locations"),
				intParam("limit", "Maximum results per group. Defaults to 20.", false, 20),
			},
		},
		{
			Action:      constants.CMD_SEARCH_TRENDS,
			Tag:         "Search",
			Summary:     "Fetch trending hashtags",
			Description: "Returns recently used hashtags using the common filter fields.",
			Auth:        AuthNone,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_USER_GET_NOTIFICATIONS,
			Tag:         "Users",
			Summary:     "Fetch user notifications",
			Description: "Returns notifications for the authenticated user with time cursor pagination.",
			Auth:        AuthRequired,
			Params: []Param{
				stringParam("cursor", "RFC3339 timestamp cursor.", false),
				intParam("limit", "Maximum item count. Default 100.", false, 100),
			},
		},
		{
			Action:      constants.CMD_USER_UPDATE_PREFERENCES,
			Tag:         "Users",
			Summary:     "Update user preference flag",
			Description: "Turns a preference item on or off for the authenticated user.",
			Auth:        AuthRequired,
			Params: []Param{
				uuidParam("id", "Preference item UUID.", true),
				intParam("bit_index", "Preference bit index.", true, nil),
				boolParam("enabled", "Whether the bit should be enabled.", true),
			},
		},
		{
			Action:      constants.CMD_UPDATE_USER_PROFILE,
			Tag:         "Users",
			Summary:     "Update user profile",
			Description: "Updates profile, password, and location fields for the authenticated user. Empty fields are passed through to the use case.",
			Auth:        AuthRequired,
			Params:      updateProfileParams(),
		},
		{
			Action:      constants.CMD_USER_FETCH_ENGAGEMENTS,
			Tag:         "Users",
			Summary:     "Fetch user engagements",
			Description: "Returns engagement detail rows for a user and engagement type with RFC3339 cursor pagination.",
			Auth:        AuthRequired,
			Params: []Param{
				enumParam("engagement_type", "Engagement kind to fetch.", true, engagementKinds()...),
				intParam("user_id", "Target user's public id.", true, nil),
				stringParam("cursor", "RFC3339 timestamp cursor.", false),
				intParam("limit", "Maximum item count. Default 100.", false, 100),
			},
		},
		{
			Action:      constants.CMD_USER_UPLOAD_AVATAR,
			Tag:         "Users",
			Summary:     "Upload avatar",
			Description: "Uploads a new avatar image for the authenticated user.",
			Auth:        AuthRequired,
			Params:      []Param{fileParam("avatar", "Avatar file.", true)},
		},
		{
			Action:      constants.CMD_USER_UPLOAD_COVER,
			Tag:         "Users",
			Summary:     "Upload cover",
			Description: "Uploads a new cover image for the authenticated user.",
			Auth:        AuthRequired,
			Params:      []Param{fileParam("cover", "Cover file.", true)},
		},
		{
			Action:      constants.CMD_USER_UPLOAD_STORY,
			Tag:         "Users",
			Summary:     "Upload story",
			Description: "Uploads a story media file for the authenticated user.",
			Auth:        AuthRequired,
			Params:      []Param{fileParam("story", "Story media file.", true)},
		},
		{
			Action:      constants.CMD_USER_DELETE_PROFILE,
			Tag:         "Users",
			Summary:     "Delete user profile",
			Description: "Deletes a user record by user_id after auth. Current repository implementation expects user_id.",
			Auth:        AuthRequired,
			Params:      []Param{intParam("user_id", "Target user public id.", true, nil)},
		},
		{
			Action:        constants.CMD_USER_CHECK_IN,
			Tag:           "Users",
			Summary:       "Create check-in",
			Description:   "Creates a check-in post for the authenticated user using content, media, and location form fields.",
			Auth:          AuthRequired,
			UseContent:    true,
			SuccessStatus: 201,
		},
		{
			Action:      constants.CMD_USER_CHECK_IN_FETCH,
			Tag:         "Users",
			Summary:     "Fetch check-ins",
			Description: "Fetches check-in posts using the common filters. post_kind is forced to checkin server-side.",
			Auth:        AuthRequired,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_USER_FETCH_STORIES,
			Tag:         "Users",
			Summary:     "Fetch stories",
			Description: "Fetches story posts/media using common filters.",
			Auth:        AuthNone,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_USER_FETCH_NEARBY_USERS,
			Tag:         "Users",
			Summary:     "Fetch nearby users",
			Description: "Fetches users ordered by distance when latitude and longitude or authenticated user location are available.",
			Auth:        AuthOptional,
			UseFilters:  true,
		},

		userPostListDoc(constants.CMD_USER_POSTS, "Fetch user posts", "Fetches top-level posts for user_id. post_kind should be supplied for the current repository filter."),
		userPostListDoc(constants.CMD_USER_POST_REPLIES, "Fetch user replies", "Fetches reply posts for user_id. post_kind should be supplied for the current repository filter."),
		userPostListDoc(constants.CMD_USER_POST_MEDIA, "Fetch user media", "Fetches media uploaded by user_id."),
		userPostListDoc(constants.CMD_USER_POST_LIKES, "Fetch user liked media", "Current router maps this action to the media fetch handler."),
		userPostListDoc(constants.CMD_USER_POST_BOOKMARKS, "Fetch user bookmarked media", "Current router maps this action to the media fetch handler."),

		interactionDoc(constants.CMD_USER_FOLLOW, "Follow user", "Creates a follow engagement.", "followee_id"),
		interactionDoc(constants.CMD_USER_UNFOLLOW, "Unfollow user", "Removes a follow engagement.", "followee_id"),
		interactionDoc(constants.CMD_USER_TOGGLE_FOLLOW, "Toggle follow", "Toggles follow state and returns updated user.", "followee_id"),
		{
			Action:      constants.CMD_USER_LIKE,
			Tag:         "Users",
			Summary:     "Like user",
			Description: "Toggles like state for the target user and returns the resulting status.",
			Auth:        AuthRequired,
			Params: []Param{
				intParam("likee_id", "Target user public id.", true, nil),
				intParam("user_id", "Legacy alias for likee_id.", false, nil),
			},
		},
		interactionDoc(constants.CMD_USER_DISLIKE, "Dislike user", "Toggles dislike state.", "likee_id"),
		interactionDoc(constants.CMD_USER_TOGGLE_LIKE, "Toggle user like", "Toggles like state.", "likee_id"),
		interactionDoc(constants.CMD_USER_TOGGLE_DISLIKE, "Toggle user dislike", "Toggles dislike state.", "likee_id"),
		interactionDoc(constants.CMD_USER_BLOCK, "Block user", "Blocks a user.", "blocked_id"),
		interactionDoc(constants.CMD_USER_UNBLOCK, "Unblock user", "Unblocks a user.", "blocked_id"),
		interactionDoc(constants.CMD_USER_TOGGLE_BLOCK, "Toggle user block", "Toggles block state.", "blocked_id"),
		interactionDoc(constants.CMD_USER_TOGGLE_SUBSCRIBE, "Toggle user subscribe", "Toggles subscription state.", "subscribed_id"),

		{
			Action:      constants.CMD_POST_CATEGORIES,
			Tag:         "Posts",
			Summary:     "Fetch post categories",
			Description: "Returns taxonomy pillars with clusters for post categories.",
			Auth:        AuthNone,
			UseFilters:  true,
		},
		{
			Action:        constants.CMD_POST_CREATE,
			Tag:           "Posts",
			Summary:       "Create post",
			Description:   "Creates a post/status/event/video using contentable form fields. kind controls the post kind when valid.",
			Auth:          AuthRequired,
			UseContent:    true,
			SuccessStatus: 201,
			Params: []Param{
				enumParam("kind", "Post kind override.", false, postKinds()...),
			},
		},
		{
			Action:      constants.CMD_POST_VOTE,
			Tag:         "Posts",
			Summary:     "Vote poll choice",
			Description: "Toggles or creates a vote for a poll choice.",
			Auth:        AuthRequired,
			Params: []Param{
				uuidParam("choice_id", "Poll choice UUID.", true),
				intParam("weight", "Vote weight. Default 1.", false, 1),
				intParam("rank", "Rank value for ranked polls. Default 0.", false, 0),
			},
		},
		postFilterDoc(constants.CMD_POST_BANANA, "Banana post", "Toggles banana engagement for post_id."),
		postFilterDoc(constants.CMD_POST_LIKE, "Like post", "Toggles like engagement for post_id."),
		postFilterDoc(constants.CMD_POST_DISLIKE, "Dislike post", "Toggles dislike engagement for post_id."),
		postFilterDoc(constants.CMD_POST_BOOKMARK, "Bookmark post", "Toggles bookmark engagement for post_id."),
		postFilterDoc(constants.CMD_POST_VIEW, "View post", "Adds a view engagement for post_id."),
		postFilterDoc(constants.CMD_POST_DELETE, "Delete post", "Deletes a post by post_id when authorized."),
		{
			Action:      constants.CMD_POST_REPORT,
			Tag:         "Posts",
			Summary:     "Report post",
			Description: "Creates a report record for a post. Send report_kind_key, or the legacy reason field. Reports are reviewed through the moderation actions.",
			Auth:        AuthRequired,
			Params: []Param{
				intParam("post_id", "Post public id.", true, nil),
				stringParam("report_kind_key", "Report kind key returned by system.initial_sync. Required unless reason is sent.", false),
				stringParam("reason", "Legacy report kind key or free-text reason. Free text is stored as an 'other' report.", false),
				stringParam("description", "Additional report details.", false),
			},
		},
		{
			Action:      constants.CMD_USER_REPORT,
			Tag:         "Users",
			Summary:     "Report user",
			Description: "Creates a report for another user. Send report_kind_key, or the legacy reason field. A user cannot report their own account.",
			Auth:        AuthRequired,
			Params: []Param{
				intParam("user_id", "Reported user's public id.", true, nil),
				stringParam("report_kind_key", "Report kind key returned by system.initial_sync. Required unless reason is sent.", false),
				stringParam("reason", "Legacy report kind key or free-text reason. Free text is stored as an 'other' report.", false),
				stringParam("description", "Additional report details.", false),
			},
		},
		{
			Action:      constants.CMD_MODERATION_REPORTS_FETCH,
			Tag:         "Moderation",
			Summary:     "Fetch reports",
			Description: "Returns pending post and user reports by default. Only moderator, admin, and super_admin users can access it.",
			Auth:        AuthRequired,
			Params: []Param{
				enumParam("status", "Report status filter. Defaults to pending; use all to include every status.", false, append(reportStatuses(), "all")...),
				enumParam("content_type", "Reported target type.", false, "post", "user"),
				intParam("post_id", "Reported post public id.", false, nil),
				intParam("user_id", "Reported user public id.", false, nil),
				intParam("reporter_id", "Reporter public user id.", false, nil),
				intParam("limit", "Page size. Defaults to 20 and is capped by the API maximum.", false, 20),
				stringParam("cursor", "Cursor returned by the previous response, or an RFC3339 timestamp.", false),
			},
		},
		{
			Action:      constants.CMD_MODERATION_REPORT_RESOLVE,
			Tag:         "Moderation",
			Summary:     "Resolve report",
			Description: "Updates a post or user report status and can optionally change a reported post's publish state. Only moderator, admin, and super_admin users can access it.",
			Auth:        AuthRequired,
			Params: []Param{
				uuidParam("report_id", "Report UUID. The id field is accepted as an alias.", true),
				enumParam("status", "New report status.", true, "reviewed", "rejected", "actioned"),
				stringParam("resolution", "Moderator note or resolution text.", false),
				boolParam("publish_post", "Optional explicit publish state for the reported post.", false),
				boolParam("hide_post", "Shortcut that sets publish_post to false when true.", false),
			},
		},
		{
			Action:      constants.CMD_MODERATION_POST_HIDE,
			Tag:         "Moderation",
			Summary:     "Hide reported post",
			Description: "Unpublishes a post by public id and marks pending reports for that post as actioned. Only moderator, admin, and super_admin users can access it.",
			Auth:        AuthRequired,
			Params: []Param{
				intParam("post_id", "Post public id.", true, nil),
				stringParam("resolution", "Moderator note or resolution text.", false),
			},
		},
		{
			Action:      constants.CMD_MODERATION_POST_UNHIDE,
			Tag:         "Moderation",
			Summary:     "Restore hidden post",
			Description: "Publishes a post by public id and marks pending reports for that post as reviewed. Only moderator, admin, and super_admin users can access it.",
			Auth:        AuthRequired,
			Params: []Param{
				intParam("post_id", "Post public id.", true, nil),
				stringParam("resolution", "Moderator note or resolution text.", false),
			},
		},
		{
			Action:      constants.CMD_POST_TIP,
			Tag:         "Posts",
			Summary:     "Tip post",
			Description: "Transfers a decimal amount from the authenticated user to the post author and returns the remaining balance.",
			Auth:        AuthRequired,
			Params: []Param{
				intParam("post_id", "Post public id.", true, nil),
				stringParam("amount", "Decimal tip amount.", true),
			},
		},
		{
			Action:      constants.CMD_POST_FETCH,
			Tag:         "Posts",
			Summary:     "Fetch post",
			Description: "Fetches a post by post_id public id, post_id UUID, or slug.",
			Auth:        AuthNone,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_POST_GET,
			Tag:         "Posts",
			Summary:     "Fetch post by slug",
			Description: "Fetches a post tree by slug.",
			Auth:        AuthNone,
			Params:      []Param{stringParam("slug", "Post slug.", true)},
		},
		timelineDoc(constants.CMD_POST_TIMELINE, "Fetch timeline", "Returns timeline posts ordered by public id descending."),
		timelineDoc(constants.CMD_POST_SEARCH, "Search posts", "Searches published posts by search/q and common filters."),
		timelineDoc(constants.CMD_POST_VIBES, "Fetch vibes timeline", "Returns a media-focused post/status timeline."),

		{
			Action:      constants.CMD_MATCH_GET_UNSEEN,
			Tag:         "Matches",
			Summary:     "Fetch unseen match users",
			Description: "Returns up to 10 users not yet seen by the authenticated user.",
			Auth:        AuthRequired,
		},
		{
			Action:      constants.CMD_MATCH_CREATE,
			Tag:         "Matches",
			Summary:     "Record match view/reaction",
			Description: "Records a reaction toward target public_id and returns whether it matched.",
			Auth:        AuthRequired,
			Params: []Param{
				intParam("public_id", "Target user public id.", true, nil),
				enumParam("reaction", "Reaction type.", false, "like", "dislike", "favorite", "bookmark", "matched", "superlike"),
			},
		},
		matchCursorDoc(constants.CMD_MATCH_FETCH_MATCHED, "Fetch matched users", "Fetches matched users after an optional RFC3339 cursor."),
		matchCursorDoc(constants.CMD_MATCH_FETCH_PASSED, "Fetch passed users", "Fetches passed users after an optional RFC3339 cursor."),
		{
			Action:      constants.CMD_MATCH_FETCH_LIKED,
			Tag:         "Matches",
			Summary:     "Fetch liked users",
			Description: "Fetches liked users. This handler reads cursor and limit from query parameters.",
			Auth:        AuthRequired,
			Params: []Param{
				{Name: "cursor", In: "query", Type: "string", Format: "date-time", Description: "RFC3339 timestamp cursor."},
				{Name: "limit", In: "query", Type: "integer", Format: "int64", Description: "Maximum item count. Default 10.", Default: 10},
			},
		},

		{
			Action:      constants.CMD_TYPING,
			Tag:         "Chat",
			Summary:     "Send typing event",
			Description: "Sends a typing=true event for the authenticated user in a chat.",
			Auth:        AuthRequired,
			Params:      []Param{uuidParam("chat_id", "Chat UUID.", true)},
		},
		{
			Action:      constants.CMD_CHAT_CREATE,
			Tag:         "Chat",
			Summary:     "Create chat",
			Description: "Creates a private, group, or channel chat. Current handler parses a single participant_ids[] UUID.",
			Auth:        AuthRequired,
			Params: []Param{
				enumParam("type", "Chat type.", true, "private", "group", "channel"),
				uuidParam("participant_ids[]", "Participant UUID. Current handler expects one value.", true),
			},
		},
		{
			Action:      constants.CMD_CHAT_MESSAGE_READ,
			Tag:         "Chat",
			Summary:     "Mark chat messages read",
			Description: "Marks one or more message ids as read. Use repeated message_ids values or message_ids[] values.",
			Auth:        AuthRequired,
			Params: []Param{
				uuidParam("chat_id", "Chat UUID.", true),
				{Name: "message_ids[]", In: "form", Type: "string", Format: "uuid", Array: true, Required: true, Description: "Message UUID values."},
				{Name: "message_ids", In: "form", Type: "string", Format: "uuid", Array: true, Required: false, Description: "Alias accepted by the handler."},
			},
		},
		{
			Action:      constants.CMD_SEND_MESSAGE,
			Tag:         "Chat",
			Summary:     "Send chat message",
			Description: "Creates a chat message post in chat_id using contentable form fields and optional media.",
			Auth:        AuthRequired,
			UseContent:  true,
			Params:      []Param{uuidParam("chat_id", "Chat UUID.", true)},
		},
		{
			Action:      constants.CMD_FETCH_CHATS,
			Tag:         "Chat",
			Summary:     "Fetch chats",
			Description: "Returns chats for the authenticated user.",
			Auth:        AuthRequired,
		},
		chatIDDoc(constants.CMD_FETCH_MESSAGES, "Fetch chat messages", "Fetches messages by chat_id."),
		chatIDDoc(constants.CMD_DELETE_CHAT, "Delete chat", "Deletes a chat for the authenticated user."),
		chatMessageDoc(constants.CMD_DELETE_MESSAGE, "Delete message", "Deletes a message in a chat."),
		chatMessageDoc(constants.CMD_DELETE_MESSAGE_FOR_USER, "Delete message for user", "Marks a message deleted for the authenticated user."),
		chatMessageDoc(constants.CMD_DELETE_MESSAGE_FOR_ALL, "Delete message for all", "Marks a message deleted for all participants."),
		chatIDDoc(constants.CMD_DELETE_CHAT_FOR_USER, "Delete chat for user", "Marks a chat deleted for the authenticated user."),
		chatIDDoc(constants.CMD_DELETE_CHAT_FOR_ALL, "Delete chat for all", "Marks a chat deleted for all participants."),
		chatMessageDoc(constants.CMD_PIN_MESSAGE, "Pin message", "Pins a message in a chat."),
		chatMessageDoc(constants.CMD_UNPIN_MESSAGE, "Unpin message", "Unpins a message in a chat."),
		chatIDDoc(constants.CMD_CLEAR_CHAT_HISTORY_FOR_USER, "Clear chat history for user", "Clears chat history for the authenticated user."),
		chatIDDoc(constants.CMD_CLEAR_CHAT_HISTORY_FOR_ALL, "Clear chat history for all", "Clears chat history for all participants."),

		{
			Action:        constants.CMD_PLACE_CREATE,
			Tag:           "Places",
			Summary:       "Create place",
			Description:   "Creates a place post using contentable form fields, location, and optional media.",
			Auth:          AuthRequired,
			UseContent:    true,
			SuccessStatus: 201,
		},
		{
			Action:      constants.CMD_PLACE_FETCH,
			Tag:         "Places",
			Summary:     "Fetch nearby places",
			Description: "Fetches nearby place posts using location and cursor filters.",
			Auth:        AuthOptional,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_PLACE_CATEGORIES,
			Tag:         "Places",
			Summary:     "Fetch place categories",
			Description: "Returns place taxonomy categories.",
			Auth:        AuthNone,
			UseFilters:  true,
		},

		{
			Action:        constants.CMD_NEWS_CREATE,
			Tag:           "News",
			Summary:       "Create news",
			Description:   "Creates an unpublished news post using contentable form fields and optional media.",
			Auth:          AuthRequired,
			UseContent:    true,
			SuccessStatus: 201,
		},
		{
			Action:      constants.CMD_NEWS_FETCH,
			Tag:         "News",
			Summary:     "Fetch news",
			Description: "Fetches news posts using common filters.",
			Auth:        AuthOptional,
			UseFilters:  true,
		},

		{
			Action:        constants.CMD_CLASSIFIEDS_CREATE,
			Tag:           "Classifieds",
			Summary:       "Create classified",
			Description:   "Creates a classified post using contentable form fields and optional media. Handler requires an authenticated user.",
			Auth:          AuthRequired,
			UseContent:    true,
			SuccessStatus: 201,
		},
		{
			Action:      constants.CMD_FETCH_JOB_OFFERS,
			Tag:         "Classifieds",
			Summary:     "Fetch job offers",
			Description: "Fetches job_offer posts using common filters.",
			Auth:        AuthOptional,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_FETCH_JOB_SEARCH,
			Tag:         "Classifieds",
			Summary:     "Fetch job searches",
			Description: "Fetches job_search posts using common filters.",
			Auth:        AuthOptional,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_CLASSIFIEDS_FETCH,
			Tag:         "Classifieds",
			Summary:     "Fetch classified",
			Description: "Fetches a classified post by post_id.",
			Auth:        AuthOptional,
			Params:      []Param{intParam("post_id", "Classified public post id.", true, nil)},
		},

		{
			Action:      constants.CMD_USER_FETCH_BROADCASTERS,
			Tag:         "Broadcasts",
			Summary:     "Fetch live broadcasters",
			Description: "Fetches live users using common filters. Same handler as broadcast.fetch.",
			Auth:        AuthOptional,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_BROADCASTS_FETCH,
			Tag:         "Broadcasts",
			Summary:     "Fetch broadcasts",
			Description: "Fetches live users using common filters.",
			Auth:        AuthOptional,
			UseFilters:  true,
		},
		{
			Action:      constants.CMD_BROADCASTS_CREATE,
			Tag:         "Broadcasts",
			Summary:     "Create external broadcast",
			Description: "Proxies a createBroadcast request to the configured external live API.",
			Auth:        AuthOptional,
			Params:      []Param{stringParam("streamDescription", "Broadcast description.", false)},
		},
		{
			Action:      constants.CMD_BROADCASTS_VIEW,
			Tag:         "Broadcasts",
			Summary:     "View external broadcast",
			Description: "Proxies a viewBroadcast request to the external live API.",
			Auth:        AuthOptional,
			Params:      []Param{stringParam("broadcastId", "External broadcast id.", true)},
		},
		{
			Action:      constants.CMD_BROADCASTS_JOIN,
			Tag:         "Broadcasts",
			Summary:     "Request guest broadcast join",
			Description: "Proxies a guest join request to the external live API.",
			Auth:        AuthOptional,
			Params: []Param{
				stringParam("broadcastId", "External broadcast id.", true),
				stringParam("streamClientId", "External stream client id.", true),
			},
		},
		{
			Action:      constants.CMD_BROADCASTS_LIKE,
			Tag:         "Broadcasts",
			Summary:     "Like external broadcast",
			Description: "Proxies a likeBroadcast request to the external live API.",
			Auth:        AuthOptional,
			Params: []Param{
				stringParam("broadcastId", "External broadcast id.", true),
				stringParam("viewerId", "External viewer id.", true),
				intParam("numLikes", "Number of likes to send.", true, nil),
			},
		},
	}
}

func commonFilterParams() []Param {
	return []Param{
		stringParam("user_id", "User UUID or public id depending on handler.", false),
		stringParam("post_id", "Post UUID or public id depending on handler.", false),
		intParam("limit", "Page size. Defaults to 20 and is capped at 100 in ParseFilters.", false, 20),
		intParam("cursor", "Int64 cursor, usually public_id.", false, nil),
		stringParam("search", "Search text.", false),
		stringParam("q", "Search text alias.", false),
		stringParam("slug", "Slug filter.", false),
		stringParam("pillar", "Taxonomy pillar slug.", false),
		stringParam("cluster", "Taxonomy cluster slug.", false),
		stringParam("category", "Category slug.", false),
		stringParam("name", "Name filter.", false),
		stringParam("city", "City filter.", false),
		stringParam("country", "Country filter.", false),
		numberParam("latitude", "Latitude in decimal degrees.", false),
		numberParam("longitude", "Longitude in decimal degrees.", false),
		numberParam("distance", "Distance cursor/value in meters.", false),
		enumParam("post_kind", "Post kind filter.", false, postKinds()...),
	}
}

func contentablePostParams() []Param {
	return []Param{
		intParam("parentPostId", "Parent post public id for replies/comments.", false, nil),
		stringParam("title", "Post title.", false),
		stringParam("slug", "Requested slug; server normalizes it.", false),
		stringParam("summary", "Short summary.", false),
		stringParam("language", "Language code. Falls back to user's default language.", false),
		stringParam("content", "Main text content.", false),
		enumParam("audience", "Audience visibility.", false, "public", "followers", "private", "friends", "mutuals"),
		{Name: "hashtags[]", In: "form", Type: "string", Array: true, Description: "Hashtag values. Repeat the field for multiple values."},
		{Name: "mentions[]", In: "form", Type: "string", Array: true, Description: "Mentioned usernames, emails, or nicknames. Repeat the field for multiple values."},
		fileArrayParam("images[]", "Image files. Repeat the field for multiple files.", false),
		fileArrayParam("videos[]", "Video files. Repeat the field for multiple files.", false),
		stringParam("extras", "JSON string stored as post extras.", false),
		stringParam("polls[0].id", "Optional poll client id for the first poll.", false),
		stringParam("polls[0].question", "Poll question. Increase the index for additional polls.", false),
		stringParam("polls[0].duration", "Poll duration string.", false),
		enumParam("polls[0].kind", "Poll kind.", false, "single", "multiple", "ranked", "weighted"),
		intParam("polls[0].max_selectable", "Maximum selectable options for multiple/weighted polls.", false, 1),
		stringParam("polls[0].options[0]", "First poll option. Increase the option index for more options.", false),
		stringParam("polls[0].ranks[0]", "Initial rank value for ranked polls.", false),
		stringParam("polls[0].weights[0]", "Initial weight value for weighted polls.", false),
		stringParam("event[title]", "Event title. When present, an event payload is created.", false),
		stringParam("event[description]", "Event description.", false),
		stringParam("event[date]", "Event date in YYYY-MM-DD format.", false),
		stringParam("event[time]", "Event time in HH:mm format.", false),
		stringParam("event[kind]", "Event kind key.", false),
		intParam("event[capacity]", "Event capacity. Parsed by form but currently not persisted.", false, nil),
		boolParam("event[is_paid]", "Whether the event is paid.", false),
		numberParam("event[price]", "Event price.", false),
		stringParam("event[currency]", "Event currency code.", false),
		boolParam("event[is_online]", "Whether the event is online.", false),
		stringParam("event[online_url]", "Online event URL.", false),
		stringParam("location[address]", "Location address.", false),
		numberParam("location[lat]", "Location latitude.", false),
		numberParam("location[lng]", "Location longitude.", false),
		stringParam("location[country_code]", "ISO country code.", false),
		stringParam("location[region]", "Region/state.", false),
		stringParam("location[city]", "City.", false),
		stringParam("location[zip_code]", "ZIP code.", false),
		stringParam("location[province]", "Province.", false),
		stringParam("location[town]", "Town/district.", false),
		stringParam("location[postcode]", "Postcode.", false),
		stringParam("location[country]", "Country name.", false),
	}
}

func updateProfileParams() []Param {
	return []Param{
		stringParam("username", "New username.", false),
		stringParam("password", "Legacy password field.", false),
		stringParam("current_password", "Current password for password changes.", false),
		stringParam("new_password", "New password.", false),
		stringParam("new_password_confirmation", "New password confirmation.", false),
		stringParam("email", "Email address.", false),
		stringParam("displayname", "Display name.", false),
		stringParam("bio", "Profile bio.", false),
		stringParam("website", "Website URL.", false),
		stringParam("date_of_birth", "Date of birth.", false),
		enumParam("privacy_level", "Profile privacy level.", false, "public", "friends_only", "followers_only", "mutuals_only", "private"),
		stringParam("location[contentable_type]", "Location owner type.", false),
		stringParam("location[country_code]", "ISO country code.", false),
		stringParam("location[address]", "Location address.", false),
		stringParam("location[city]", "City.", false),
		stringParam("location[country]", "Country.", false),
		stringParam("location[region]", "Region.", false),
		stringParam("location[timezone]", "Timezone name.", false),
		stringParam("location[display]", "Display location string.", false),
		numberParam("location[latitude]", "Latitude in decimal degrees.", false),
		numberParam("location[longitude]", "Longitude in decimal degrees.", false),
	}
}

func userPostListDoc(action, summary, description string) ActionDoc {
	return ActionDoc{
		Action:      action,
		Tag:         "Users",
		Summary:     summary,
		Description: description,
		Auth:        AuthOptional,
		UseFilters:  true,
		Params:      []Param{intParam("user_id", "Target user public id.", true, nil)},
	}
}

func interactionDoc(action, summary, description, field string) ActionDoc {
	return ActionDoc{
		Action:      action,
		Tag:         "Users",
		Summary:     summary,
		Description: description,
		Auth:        AuthRequired,
		Params:      []Param{intParam(field, "Target user public id.", true, nil)},
	}
}

func postFilterDoc(action, summary, description string) ActionDoc {
	return ActionDoc{
		Action:      action,
		Tag:         "Posts",
		Summary:     summary,
		Description: description,
		Auth:        AuthRequired,
		UseFilters:  true,
		Params:      []Param{intParam("post_id", "Post public id.", true, nil)},
	}
}

func timelineDoc(action, summary, description string) ActionDoc {
	return ActionDoc{
		Action:      action,
		Tag:         "Posts",
		Summary:     summary,
		Description: description,
		Auth:        AuthNone,
		UseFilters:  true,
	}
}

func matchCursorDoc(action, summary, description string) ActionDoc {
	return ActionDoc{
		Action:      action,
		Tag:         "Matches",
		Summary:     summary,
		Description: description,
		Auth:        AuthRequired,
		Params: []Param{
			stringParam("cursor", "RFC3339 timestamp cursor.", false),
			intParam("limit", "Maximum item count. Default 10.", false, 10),
		},
	}
}

func chatIDDoc(action, summary, description string) ActionDoc {
	return ActionDoc{
		Action:      action,
		Tag:         "Chat",
		Summary:     summary,
		Description: description,
		Auth:        AuthRequired,
		Params:      []Param{uuidParam("chat_id", "Chat UUID.", true)},
	}
}

func chatMessageDoc(action, summary, description string) ActionDoc {
	return ActionDoc{
		Action:      action,
		Tag:         "Chat",
		Summary:     summary,
		Description: description,
		Auth:        AuthRequired,
		Params: []Param{
			uuidParam("chat_id", "Chat UUID.", true),
			uuidParam("message_id", "Message UUID.", true),
		},
	}
}

func postKinds() []string {
	return []string{
		"status",
		"timeline",
		"place",
		"classified",
		"job_offer",
		"job_search",
		"generic",
		"news",
		"story",
		"chat",
		"message",
		"post",
		"event",
		"checkin",
		"video",
	}
}

func reportStatuses() []string {
	return []string{
		"pending",
		"reviewed",
		"rejected",
		"actioned",
	}
}

func engagementKinds() []string {
	return []string{
		"touch",
		"banana",
		"carrot",
		"coffee",
		"kiss",
		"like_given",
		"like_received",
		"dislike_given",
		"dislike_received",
		"matched",
		"referral",
		"view_given",
		"view_received",
		"post",
		"comment",
		"follower",
		"following",
		"blocked_by",
		"blocking",
		"view",
		"subscribed_by",
		"subscribing",
		"bookmark",
		"rating",
		"tip",
		"gift",
		"report",
		"deposit",
		"withdraw",
		"message_deleted_for_me",
		"message_deleted_for_all",
		"chat_deleted_for_me",
		"chat_deleted_for_all",
		"chat_mark_message_read",
	}
}
